### ISSUE TITLE
Glyph Closure using SingleSubstFormat1 has O(N^2) worst case performance.

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#1083]
Example that triggers the worst case:
- Font wtih a SingleSubstFormat1 that covers glyphs 1-65535. Delta is large say 32,000.
- Start the closure with a single glyph.
- The closure function on SingleSubstFormat1 will add a couple glyphs to the set including 1 that overflows and is behind the current position in the for loop.
- In hb_ot_layout_lookups_substitute_closure since a few glyphs were added we'll need to iterate over all of the lookups again.
- This repeats many times adding only a small number of glyphs on each iteration.

I've put together a potential fix here: https://github.com/googlefonts/harfbuzz/commit/67fa62dd45f089d22a1bb4c797d8cb27961a9b10
- This falls back to a different algorithm in SingleSubstFormat1 if an overflow is detected. The alternate algorithm is O(N*LOG(N)) and will fully complete the SingleSubstFormat1 closure, whereas the existing algorithm wont.

I tested this against the fuzzer reported timeout and it resolves it.

**Comment by behdad** [comment]
Your proposed fix is correct in that it closes over the lookup faster.  However, in actual shaping each lookup is only applied once.  So we don't want to do that.  The reason we have a while loop is that we don't know what order lookups are applied, because shaper can have multiple stages.  Within each stage lookups are applied in their index order.  So, I suggest:
- Limit number of times the while loop loops. `#define HB_CLOSURE_MAX_STAGES 8` (only if it's not defined; see other `_MAX_` defines.
- We should also separate input glyphset and output glyphset that the glyph_closure methods work with.

**Comment by garretrieger** [comment]
Fuzzer's reporting the timeouts are fixed.
