### ISSUE TITLE
Mis-Shaping Chakma Maayyaa U+11134

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#1105]
https://github.com/googlei18n/noto-fonts/issues/1263 (reported by @bivuti) sounds like an Harfbuzz issue; see there for details.

**Comment by punchcutter** [comment]
Yes, U+11134 needs a USE override to be Gemination_Mark instead of Pure_Killer. That will give it use category CMAbv which in USE cluster validation is allowed before the other marks. The other thing we should do is remove the `decompose_use` special-casing for Chakma split-vowels.  At the same time we need to make sure we update the other USE overrides as mentioned here: https://github.com/harfbuzz/harfbuzz/issues/539, but @dscorbett makes a good point in https://github.com/harfbuzz/harfbuzz/pull/982 that we shouldn't necessarly override everything to VBlw.
