### ISSUE TITLE
Implementing Text Box - One Glyph Two Chars 

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [harfbuzz/harfbuzz#1149]
I'm Currently working with **harfbuzz** and **freetype** in OpenGL 2 to render Persian text.

It was going great until I wanted to implement a text box and add the text selection feature.
The Problem is the glyph **"لا"** which is two chars but one glyph and when I select the whole two chars get selected because **they're one glyph.**

Is there a fix so it becomes two different glyphs (seems impossible for some fonts cause they're kinda in each other)

![lalaland](https://user-images.githubusercontent.com/10983665/45016963-7f4b4b00-b03b-11e8-822e-9599660308e7.png)

**Comment by Erfan-Ahmadi** [comment]
I found out that this glyph cluster size is 2, how can i disable harfbuzz merging 2 characters into one glyph?

**Comment by khaledhosny** [comment]
What you need is not disabling the ligature (because this will break the look of the fonts), but handling cursor positioning inside them. What application do, is count the number of characters in the ligature (based on the cluster values), then divide the width of the glyph by the number of grapheme clusters and use that to position the cursor.
