### ISSUE TITLE
[aat] Combining grave placement confusion in RTL with Times.ttc

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1349]
As @ebraminio helpfully found when going through the test results, we see one confusion between CT and HarfBuzz AAT on combining grave placement in RTL.

Compare https://chromium-review.googlesource.com/c/chromium/src/+/1275945/34/third_party/WebKit/LayoutTests/platform/mac-mac10.10/fast/text/selection/complex-text-rtl-selection-repaint-expected.png

CoreText:

```
$ ../test/shaping/hb-unicode-encode U+006D,U+0300,U+0075,U+0073 | ./hb-shape /System/Library/Fonts/Times.ttc  --direction=rtl --shaper=coretext
[s=3+797|ugrave=2+1024|m=0+1593]
```

HB AAT:

```
$ ../test/shaping/hb-unicode-encode U+006D,U+0300,U+0075,U+0073 | ./hb-shape /System/Library/Fonts/Times.ttc  --direction=rtl --shaper=ot --font-funcs=ot
[s=3+797|u=2+1024|mgrave=0+1593]
```

**Comment by behdad** [comment]
This is CoreText bug and an unimportant one.  The U+0300 clearly belongs to U+006D, so that's where HarfBuzz puts it.  That's because we flip the order of graphemes in the string.  CoreText, apparently, just flips the whole string, causing U+0300 to appear after U+0075...

Forced-direction is not important.  Closing.
