### ISSUE TITLE
ABI break when updating from 1.9.0 to 2.0.x

### ISSUE THREAD

**Issue by jjardon** [harfbuzz/harfbuzz#1359]
Hi, we have detected the following ABI break when trying to upgrade: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/619#note_114502810, I will paste here:
```
┌─────────────────────────────────────────────────┐
│ ABI Break: libharfbuzz-icu.so.0:libharfbuzz-icu │
└─────────────────────────────────────────────────┘

Functions changes summary: 0 Removed, 1 Changed (2 filtered out), 0 Added functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

1 function with some indirect sub-type change:

  [C]'function UScriptCode hb_icu_script_from_script(hb_script_t)' at hb-icu.cc:53:1 has some indirect sub-type changes:
    parameter 1 of type 'typedef hb_script_t' has sub-type changes:
      underlying type 'enum __anonymous_enum__' at hb-common.h:159:1 changed:
        type size hasn't changed
        1 enumerator change:
          '__anonymous_enum__::_HB_SCRIPT_MAX_VALUE' from value '4294967295' to '2147483647' at hb-common.h:176:1
```

Is this expected?

**Comment by behdad** [comment]
You can ignore this.

**Comment by bochecha** [comment]
@behdad hi, can you give us a bit more details on the reason why this can be ignored?

For example, if this is a type you consider private, then we could configure our ABI check to completely ignore this type, so that future changes to it don't raise an error.

Basically, whenever we can find rules for ignoring whole classes of ABI changes which don't break apps, it's always better than just ignoring a single change. :slightly_smiling_face:

**Comment by behdad** [comment]
> @behdad hi, can you give us a bit more details on the reason why this can be ignored?
> 
> For example, if this is a type you consider private, then we could configure our ABI check to completely ignore this type, so that future changes to it don't raise an error.
> 
> Basically, whenever we can find rules for ignoring whole classes of ABI changes which don't break apps, it's always better than just ignoring a single change. slightly_smiling_face

The type is definitely public.  As the report says, it didn't change size, so that's not an ABI break.  The value `_HB_SCRIPT_MAX_VALUE` is however private as signaled by the underscore prefix.  It was set to 0xFFFFFFFF before to ensure the enum receives an unsigned int type.  However, as discussed in length in bug https://github.com/harfbuzz/harfbuzz/issues/504 and before, ISO C does not allow that.  So, the code was not standard compliant . So we change it.

**Comment by bochecha** [comment]
Thanks for the details. :slightly_smiling_face:
