### ISSUE TITLE
[aat] Skip default-ignorables in state machine?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1367]
Logic would be similar to OT: if and only if a default-ignorable glyph does not have a class set in the state machine (ie. CLASS_OUT_OF_BOUNDS=1), then we'd skip it.

@jfkthame thoughts?

**Comment by jfkthame** [comment]
How would this interact with state machine actions that potentially affect several glyphs?

E.g. suppose we have a sequence P*QRS, where the * is a default-ignorable; and we have an Indic-rearrangement machine that marks the sequence beginning at P and ending at S, having ignored the *, and applies Indic rearrangement verb 4 (ABx => xAB).

Will the default-ignorable glyph, as the second glyph in the range, be treated as "B" for the purposes of the verb, so the result is QRSP*; or will it be ignored, so that we get either RSP*Q or *RSPQ depending on whether it moves (does it?) along with its surrounding glyphs?

ISTM there's enough unclear about this that we probably shouldn't go there, at least until we're pushed in that direction by real-world use cases.

**Comment by behdad** [comment]
> ISTM there's enough unclear about this that we probably shouldn't go there, at least until we're pushed in that direction by real-world use cases.

The Rearrangement lookup is the only one that needs special handling.  The Ligature one happily works.  For Rearrangement, I can implement the same logic when picking up glyphs to be reordered.

Anyway, wanted to file this here and experiment with.
