### ISSUE TITLE
Remove coretext_aat shaper

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1478]
Right now that is still picking up AAT fonts if coretext is enabled.  Time to remove I think.  Dominik, are we safe from Chrome's point of view?

**Comment by behdad** [comment]
@drott

**Comment by drott** [comment]
If you don'd mind, I'd prefer for it to pass one stable release, according to
https://storage.googleapis.com/chromium-find-releases-static/c67.html#c67f53b0b70f33c47159d37f7e59bb44399b0d09 Chrome enabled HarfBuzz-native AAT shaping in 72. And according to https://www.chromium.org/developers/calendar the estimated stable release date for 72 is mid January, and for 73 is mid-March 2019. 

So since 72 is not in stable yet, I would like to see if anything breaks when it hits stable, and during that time be able to switch back to CoreText-AAT if needed without having to roll back to an old HarfBuzz as a whole.

So, I'd say - if there is no rush, I'd say regarding removal, we can revisit this in March 2019 then.

No objections for deprioritizing hb-coretext shaper choice, if there is a well-tested way to  invoke the old coretext-aat-preferred behavior until March 2019.

**Comment by behdad** [comment]
Can we lower the priority?  That would be trivially-revertible.

**Comment by behdad** [comment]
Upon thinking more, I don't want to remove it.  Just change priority.

**Comment by khaledhosny** [comment]
If we moved it after default shaper, it will be effectively unused (except for clients that select shapers explicitly), so why keep it (we might want to keep the `coretext` shaper, similar to `uniscribe` and `directwrite` ones, but `coretext_aat` would be of little use).

**Comment by behdad** [comment]
> If we moved it after default shaper, it will be effectively unused (except for clients that select shapers explicitly), so why keep it (we might want to keep the `coretext` shaper, similar to `uniscribe` and `directwrite` ones, but `coretext_aat` would be of little use).

`coretext_aat` can still be used by clients to route only AAT fonts to CoreText.

**Comment by khaledhosny** [comment]
Of course, but why? To be future-proof in case AAT grew new stuff HarfBuzz does not support?

**Comment by behdad** [comment]
> Of course, but why? To be future-proof in case AAT grew new stuff HarfBuzz does not support?

No, more like to emulate current behavior.

**Comment by ebraminio** [comment]
I think what we can do immediately with no doubt and before the release is to lower its priority and after public availability of Chrome 72 we can decide if we want to remove whole coretext_aat (which I am in favor of), so am uploading a patch for it

**Comment by ebraminio** [comment]
As if a client wants 100% compatibility with CoreText, they better to use whole "coretext" backend or CoreText itself directly anyway, we are however only keeping it just as we promised to Chromium :) (but they have to call hb_shape_full instead if something went horribly wrong)

**Comment by ebraminio** [comment]
Uploaded #1488

**Comment by ebraminio** [comment]
> No, more like to emulate current behavior.

No need to as they can handle it themselves using hb_shape_full.

**Comment by behdad** [comment]
> > No, more like to emulate current behavior.
> 
> No need to IMHO as they can handle it themselves using `hb_shape_full` and `hb_aat_layout_has_*`.

They can't, without sniffing whether the font is AAT and changing the shaper list based on that.

**Comment by ebraminio** [comment]
> They can't, without sniffing whether the font is AAT and changing the shaper list based on that.

What I was referring to also, why not, clients can do that if they want as we've provided easy to use API for that also. From our Chromium experience, a client that want metrics compatibility with CoreText (which Chrome UI used to), needs the CoreText itself actually but maybe with our nice [or not] API, something we can consider unsupported now.
