### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by crazybytes** [harfbuzz/harfbuzz#1485]
The Illuminati makes the whole computerworld rotten.
How the hell do you compile this shit with Cygwin for windows?
Otherwise hand over a script how to compile.
You create a jungle of rotten software that is corrupted to the bone.

**Comment by behdad** [comment]
That's some good stuff you've been sniffing...

**Comment by crazybytes** [comment]
You only building trash that can not be compiled.
Supply a manual.
And fuck you.

Op ma 17 dec. 2018 om 04:11 schreef Behdad Esfahbod <
notifications@github.com>:

**Comment by ebraminio** [comment]
Hey there, if the only thing you need is having something equivalent to HarfBuzz in Windows, you can try Uniscribe, provided without any binary or compile cost. https://maxradi.us/documents/uniscribe/

If you want to have access to harfbuzz and other common foss libraries like glfw glew pango freetype ... with a great ease in Visual Studio (and now, Windows even), definitely checkout https://github.com/microsoft/vcpkg (this bit, was mentioned in project's BUILD.md among many other things)

You can however install harfbuzz in cygwin just with `setup-x86_64.exe -g -q -P libharfbuzz-devel`, the easiest way I can imagine. (or setup-x86.exe, it should be available in your cygwin installation folder)

If you still need *building* in cygwin (which can be avoided), this is the prerequisites, 
`setup-x86_64.exe -g -q -P cygwin-devel,libfreetype-devel,libcairo-devel,libicu-devel,gcc,gcc-g++,libglib2.0-devel,pkg-config,python2'`

After that, issue `./autogen.sh --with-freetype --with-glib --with-cairo --with-icu`, ([reference](https://github.com/harfbuzz/harfbuzz/blob/00e51a10832965f4c1d65a6d71c9582782f02c2b/appveyor.yml#L45)). It should work, otherwise, try the other ways.

Have a nice day!
