### ISSUE TITLE
Should harfbuzz itself handle letter-spacing?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1487]
Continuing from #64, if tracking is the same as letter spacing, https://en.wikipedia.org/wiki/Letter-spacing#Letter-spacing_with_fixed_spaces now that we have logic for handling size dependent letter-spacing, isn't better to handle the size independent in HarfBuzz in future also, considering things like which script to not apply, which features to disable, things like #1310? (cc: @bungeman)

(perhaps a super idea also, maybe applying Kashida for Arabic at the same place instead of regular spacing, so clients willing to have Kashida for justification for Arabic just to apply a correct letter spacing instead)

**Comment by bungeman** [comment]
If I'm not mistaken, tracking and kerning are both glyph based and css wants both even in the letter spacing case. It is explicitly called out in the css specification that letter spacing is in addition to any kerning or tracking. As far as css is concerned, letter spacing is not intended to change any positioning features, only substitution features.

The case of #1310 is about confusing high level policy (disabling particular features because of what they do typographically) with low level mechanism (the spec says that 'clig' is required to be on for 'khmr'). In other words, features seem to be generally grouped into "policy" features (like 'liga') that are expected to be toggled by users and "mechanism" features (like 'pref') which are expected to be mostly of concern to the shaper. In this case 'clig' got caught in the middle. There's no real distinction, just convention. Note that this is also about substitution features.

**Comment by ebraminio** [comment]
> tracking and kerning are both glyph based

Ours is grapheme based, as Mozilla's was cluster based https://github.com/mozilla/gecko-dev/blob/3564dfde3b125878dc5a04fe92629fc5195942df/gfx/thebes/gfxFont.cpp#L686

> css wants both even in the letter spacing case

I am not saying this in a contradicting way I think

**Comment by ebraminio** [comment]
> The case of #1310 is about confusing high level policy.

That case is similar to things happen in [`JSTF`](https://docs.microsoft.com/en-us/typography/opentype/spec/jstf), disabling a feature because of spacing (justification on that case), that is why justification, letter spacing and tracking looks similar to me, even being so different from high level and how applied, they all seem need a correct and careful implementation.

Interestingly https://www.w3.org/TR/css-text-3/#cursive-tracking refers to Kashida elongation as a correct way of applying of letter-spacing, what I way saying also.

**Comment by bungeman** [comment]
The Mozilla code to which you link is about adjusting advances between clusters when guessing what to do when creating synthetic bold advances, and doing so as a post-shaping step. Since the synthetic bold font is essentially a new font (in a custom format), wouldn't it be a much better design to override all of the hb_font callbacks and adjust the advances, bounds, etc in the callback? In other words, this synthetic font is not fully a TrueType/OpenType font anymore so the default 'ot' implementations need to be overriden to provide the correct information.

The only way I could see for the Mozilla code to be correct is if on the drawing side the exact same logic is used and the fake bolding applies to whole clusters and not glyphs, which could look very strange. Unless the fake bolding is doing something other than more or less stoking the outlines I can't see how blindly adjusting the advance width is helpful, since it would tend to break up the joining in cursive scripts?

**Comment by ebraminio** [comment]
> wouldn't it be a much better design to override all of the hb_font callbacks and adjust the advances, bounds, etc in the callback?

I didn't write the code, nor collaborated on it :)

You know, my goal and concern here is to find a usecase that our clients have and see if we can abstract and implement it correctly inside the library and provide it in a straightforward way. We used to think about providing a function to know what to do with letter-spacing, #64, but I was more interested on something that we can set as hb_buffer property so we can overload it with Kashida justification (my main interest).

**Comment by bungeman** [comment]
I see, so this is a different approach but similar request to 586 and 1469? Since the effect of letter spacing may change based on the script and require further shaping HarfBuzz could add a 'glyph' spacing or 'cluster spacing' attribute so such code could be shared. Such code could add the letter spacing or add kashida as needed. This part seems complex enough, but isn't quite right either because there may be more inter cluster space than just letter spacing (like justification, which may be in addition to letter spacing).

However, I don't see how this plays directly into justification, since that may be a combination of glyph substitutions, glyph positioning substitutions, letter spacing, word spacing, variable axis tweaking, size tweaking, taking over and under hangs into account, etc. It seems that the interface a user would want is to try to go through its own justification steps to create a line as good as it can, but still have enough information to say "ok, now fill in the kashida, if any". If the clusters were marked with 'kashida after' and 'kashida before' and there were a call to 'fillInKashida' which would stick them in (or provide the information needed to draw them). Note that the user would need to know in advance if line initial or final kashida/extensions (or normal medial kashida/extensions for that matter) were available in order to do their own justification, but I think this is all they would need to know. Essentially, let the user know where/if they can add their own space, then let them join things up after they do.

I suppose what I'm saying is that justification is not a well defined process and it isn't just poking some space between glyphs and maybe filling in the space. It seems premature to try to bake it in to a fundamental library or try to do it greedily. Instead it seems like a good time to provide whatever information a user may need to know to do as much of their own justification policy as they can.

**Comment by ebraminio** [comment]
> I see, so this is a different approach but similar request to 586 and 1469?

I tested MS algorithm on https://github.com/ebraminio/kashida/ provided an experimental API that can provides Kashida justification https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-directwrite.h#L33 using DirectWrite https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-directwrite.cc#L688-L765 and revived the part was used to that inside harfbuzz https://github.com/harfbuzz/harfbuzz/compare/master...ebraminio:kashida so am making some progress also other than filing bugs and complaining :) (and implemented initial versions of `trak` handling in hb). However, am still trying to figure how we can go ahead so it occurred to me if justification can be modeled like letter-spacing.

> However, I don't see how this plays directly into justification, since that may be a combination of glyph substitutions, glyph positioning substitutions, letter spacing, word spacing, variable axis tweaking, size tweaking, taking over and under hangs into account, etc.

Right. I understand

> It seems that the interface a user would want is to try to go through its own justification steps to create a line as good as it can, but still have enough information to say "ok, now fill in the kashida, if any". 

One can not just add Kashida to a buffer as if we want to add Kashida to «ولا», the text should be shaped again so لا be decomposed to ل +‌ ا first then a Kashida added to it ولـــــا. As you said justification is combination of different things... apparently letter-spacing is also seen something not that simple which you went for disabling `clig` and other features for having letter-spacing and reached to that issue in Khmer, my observation that made me think they are the same, which now I think is not.

> Instead it seems like a good time to provide whatever information a user may need to know to do as much of their own justification policy as they can.

We can do such without considering the font and it will become something like my request at #586.

Or we can do that like `GetJustificationOpportunities` `JustifyGlyphAdvances` `GetJustifiedGlyphs` of https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-directwrite.cc#L690 and hopefully that can handle AAT's [`just`](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6just.html) also. This however feels against harfbuzz philosophy to not separate GetGlyphs/GSUB GetGlyphPlacements/GPOS into separate calls but feels what you are referring to.

**Comment by khaledhosny** [comment]
> (perhaps a super idea also, maybe applying Kashida for Arabic at the same place instead of regular spacing, so clients willing to have Kashida for justification for Arabic just to apply a correct letter spacing instead)

Certainly not, letter-spacing for justification is pretty poor solution most of the time and is not equivalent to kashida justification at any level, conflating the two is just not called for.

**Comment by khaledhosny** [comment]
> Interestingly https://www.w3.org/TR/css-text-3/#cursive-tracking refers to Kashida elongation as a correct way of applying of letter-spacing, what I was saying also.

I’m pretty sure that the only OK solution here is ignoring letter-spacing, applying kashida in place of letter-spacing would be clients second guessing there users. Fortunately no client actually does this.

**Comment by ebraminio** [comment]
> perhaps a super idea also

I wanted to say super bad idea idea :P. OK so, let's close this.

**Comment by ebraminio** [comment]
Related about the issue,
* https://bugs.chromium.org/p/chromium/issues/detail?id=942012
* https://bugs.webkit.org/show_bug.cgi?id=195745
* https://bugzilla.mozilla.org/show_bug.cgi?id=1342835

**Comment by ebraminio** [comment]
Related https://youtu.be/WCDO-fqPwEg?t=792

**Comment by yisibl** [comment]
Good news—Chrome and Firefox have recently fixed it.
