### ISSUE TITLE
[Regression] df32eaae42b505b00d seems to break shaping 'ਮਾੲਿਅਾ' with "Nirmala UI" 

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1516]
Bisecting shows that

running:
```
util/hb-view ~/Downloads/Nirmala.ttf "ਮਾੲਿਅਾ "
```

after df32eaae42b505b00de4a8b5efce9ab948bed847
"[indic] Disallow vowel mark combinations that spoof other vowel marks"
 has broken output:

![nirmala_regression](https://user-images.githubusercontent.com/1021784/50485706-0ebba600-09ff-11e9-9c97-471cc707a8b1.png)

I am not sure whether "ਮਾੲਿਅਾ" is a valid sequence according to that commit, but this shaping breakage has been reported as an issue in https://bugs.chromium.org/p/chromium/issues/detail?id=917711#c7.

At one commit before, 1b8d5e999192035c08f918aa1fcfcebdea67d82e - the result looks like this:

![nirmala_good](https://user-images.githubusercontent.com/1021784/50486131-1d0ac180-0a01-11e9-90a0-b72f5cd9637a.png)

**Comment by jfkthame** [comment]
The text sequence there is `U+0A2E,U+0A3E,U+0A72,U+0A3F,U+0A05,U+0A3E`, which includes the subsequence `U+0A72,U+0A3F` to represent ਇ (`U+0A07`). This is one of the sequences explicitly called out in Table 12-16 of Unicode 11.0 as "do not use".

Similarly, `U+0A05,U+0A3E` is listed as an incorrect representation of ਆ (`U+0A06`).

So these are exactly the kind of mis-encodings that Unicode says should not be used, and #1019 implemented those rules.

**Comment by drott** [comment]
Thanks for the analysis. For reference, Table 12-16 can be found in: http://www.unicode.org/versions/Unicode11.0.0/ch12.pdf and reads:

<img width="500" alt="12_16" src="https://user-images.githubusercontent.com/1021784/50487627-cd7bc400-0a07-11e9-84b8-55e990319e92.png">

So I suppose we close this as WontFix and I inform the reporter about the recommended encodings?

**Comment by drott** [comment]
> So these are exactly the kind of mis-encodings that Unicode says should not be used, and #1019 implemented those rules.

Does this mean you will insert dotted-circles for those in future versions of Firefox, too?

**Comment by inderpreet99** [comment]
I'm the one that opened this request on chromium bug tracker.

Not sure if Unicode chose those specific sequences as strictly "Do Not Use".

It adds an extra bit of complexity when writing unicode Gurmukhi. You have to think before needing these combination of characters. You must decide if there is a combo/atomic character or build them as you would with any other Gurmukhi characters that needs those diacritic marks.

A lot of sites on the Internet are going to look slightly because regular Punjabi/Gurmukhi speakers/writers do not understand this underlying complexity. They're not aware Unicode decided to build combo characters instead of building them on the fly as we do for all the other Gurmukhi characters needing diacritics.

Realistically, one should be able to build these characters on the fly if necessary. I don't see why we need to strictly enforce this rule.

**Comment by jfkthame** [comment]
> > So these are exactly the kind of mis-encodings that Unicode says should not be used, and #1019 implemented those rules.
> 
> Does this mean you will insert dotted-circles for those in future versions of Firefox, too?

I'd expect so, unless people make a strong argument that the Unicode recommendation is bad and should not be implemented, and harfbuzz reverts it.

It might be worth raising this on the Unicode Indic mailing list (indic@unicode.org) to see what others think.

> Realistically, one should be able to build these characters on the fly if necessary. I don't see why we need to strictly enforce this rule.

The trouble is that this results in two distinct, non-canonically-equivalent spellings for the same visual element, which leads to problems of searching, comparison, etc.

**Comment by drott** [comment]
Wordpad on Windows 10 also displays dotted circles.

**Comment by behdad** [comment]
Close?

**Comment by jfkthame** [comment]
I think so. This seems to be a widely-implemented behavior, and it agrees with Unicode recommendations. If users disagree with the current recommendation regarding how these text elements should be encoded, this is something to take up with the Unicode committee. Any potential changes should be discussed and agreed there first, not tweaked piecemeal by individual implementations.
