### ISSUE TITLE
Remove GSUB/GPOS lookup recursion depth limit

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1543]
The max_ops counter is enough to disable stalls.  No need for recursion depth limit.  Well, I mean, yeah, we don't want to stack overflow.  So, maybe not remove but increase the limit to large value (1024?).

And even better, implement tail call optimization.

**Comment by behdad** [comment]
Also see https://twitter.com/Litherum/status/1104439589719072769

@Litherum can you elaborate?  The defaults should give you plenty of ops.
```
hb-buffer.hh:#ifndef HB_BUFFER_MAX_OPS_FACTOR
hb-buffer.hh:#define HB_BUFFER_MAX_OPS_FACTOR 64
hb-buffer.hh:#ifndef HB_BUFFER_MAX_OPS_MIN
hb-buffer.hh:#define HB_BUFFER_MAX_OPS_MIN 1024
```

**Comment by litherum** [comment]
Oh, I increased the recursion depth, but for longer numbers I was hitting some other limit, so rather than trying to determine which other limit it was, I just raised all the limits, and the problem went away. So there were at least two limits which needed to be raised for this font to work: recursion depth and something else.

**Comment by behdad** [comment]
I see.  I'll get to test it eventually and make it work by default.  Thanks.

**Comment by behdad** [comment]
We should move the max-ops accounting further down into buffer private methods ideally and less spread out through the code.

**Comment by behdad** [comment]
I've increased the recursion depth to 64 now. Unlimited would not be advisable.
