### ISSUE TITLE
hb_face_create() with an empty blob

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#1572]
I was expecting the code below to print 1, but it prints 0; even though `hb_face_create()` is essentially returning an empty face, it is still not equal to `hb_face_get_empty ()`. Is this expected?

```C
#include <stdio.h>
#include <hb.h>

int
main (int argc, char** argv)
{
  printf("%d\n", hb_face_create (hb_blob_get_empty (), 0) == hb_face_get_empty ());
}
```

**Comment by behdad** [comment]
It used to be that way, but I changed it, because, a face created using an empty blob can still be meaningfully used for certain tasks.  The hb-fc-list does that I think.  Whereas if we returned the empty face then it would be inert and refuse shaping with it.

I can't make up my mind, maybe creating a blob for zero bytes should also return a new instance instead of returning the nil instance.

**Comment by khaledhosny** [comment]
For my case, I was trying to catch for faces created from non-existing file. But I think what I actually need is a general check “is this an SFNT font” since that what I care about, and checking for table tags might be a more robust check for my specific case.
