### ISSUE TITLE
Shaping for Malayalam ര്‍ possibly incorrect in some cases

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#1599]
Starting at https://github.com/harfbuzz/harfbuzz/commit/2f1f961cc0f0f907916b4b00342d8a2dda8b4ee1 ര്‍ began shaping as ര് in one of our fonts. Reproduction:

[NotoSansSouthAsian-Regular.zip](https://github.com/harfbuzz/harfbuzz/files/2908613/NotoSansSouthAsian-Regular.zip)

util/hb-view --language=ml NotoSansSouthAsian-Regular.ttf "ര്‍"

Prior to the above commit, hb-view produces the expected output. It does work correctly in NotoSansMalayalam-Regular.ttf.

**Comment by dscorbett** [comment]
It is a font bug. Prior to that commit, the language code "ml" was converted to 'MLR ' (Malayalam Reformed); since that commit, "ml" is converted to 'MAL ' or 'MLR ', whichever the font supports, which in this case is 'MAL '. If the text is tagged "ml", the shaper only applies lookups that support 'MAL '. This particular bug happens because the 'locl' lookup only supports 'dflt'.  The fix is to remove 'MAL ' from all lookups. That way the shaper will use 'dflt' for Malayalam text regardless of the tagged language.

**Comment by khaledhosny** [comment]
I think the font is now working as intended.

Before this commit `ml` BCP 47 tag would map only to `MLR ` OpenType tag, but now it maps to both `MAL ` and `MLR ` (as it should, judging by https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags). The font has lookups for the `MAL ` tag and they are now activated when `ml` language is used, previously they were just ignored.

**Comment by khaledhosny** [comment]
Didn’t see @dscorbett before posting mine :)

**Comment by garretrieger** [comment]
Thank you for the help. I'll try the fixes that you suggested.
