### ISSUE TITLE
[variations] Support multiple axes with same tag

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1673]
Currently doesn't work.

**Comment by behdad** [comment]
Needs no API change though.

**Comment by jfkthame** [comment]
Do renderers actually support fonts having multiple axes with the same tag? I guess I've always assumed axis tags needed to be distinct, though now that you mention it, I don't know that the spec says anything about this.

**Comment by behdad** [comment]
> Do renderers actually support fonts having multiple axes with the same tag? I guess I've always assumed axis tags needed to be distinct, though now that you mention it, I don't know that the spec says anything about this.

The geniuses that discovered this trick claim that it works in Firefox and Chrome.  Which might mean just CoreText, or CoreText and FreeType.  cc @drott @lemzwerg FYI.  We should check FreeType.

But yeah, this would allow higher-order polynomial interpolations.  I'm going to recommend that spec allow this as long as at most one axis per tag is non-HIDDEN.

**Comment by lemzwerg** [comment]
Is there a sample font for this?

**Comment by behdad** [comment]
> Is there a sample font for this?

I'll send you privately.

**Comment by justvanrossum** [comment]
Fwiw, this is a nice write-up, and links to a test font: https://bungeman.github.io/hoi.html

**Comment by lemzwerg** [comment]
Indeed, thanks!  And the demo font seems to exhibit a problem with FreeType: If you test with `ftmulti` (from current git), there is a jump of the point glyph at 'Weight' value 450...

**Comment by justvanrossum** [comment]
I also see the jump with FreeType 2.10.2.

**Comment by lemzwerg** [comment]
It' an artifact of the font, I guess – if you manually enter value 450 into Samsa, you see exactly the same jump.  @bungeman, can you have a look, please?

**Comment by bungeman** [comment]
Yes, the example font purposely has the 'bad' way to encode multiple curves into a single contour on the 'negative' side of the axes. In fact that's why it has that strange range on the negative side, so that the most viewers would actually hit the discontinuity (it's really easy to make a font which doesn't show the discontinuity in most viewers since the viewer may not be able to exactly hit the point).

That discontinuity is the motivation for the 'second attempt' which is demonstrated on the 'positive' side of the axes which doesn't have any discontinuity between curves on the contour. So yes, this jump is expected. Maybe should be more explicit about that in the 'example' text.

**Comment by lemzwerg** [comment]
Thanks!
