### ISSUE TITLE
Type1 kerning deprecated?

### ISSUE THREAD

**Issue by smilingthax** [harfbuzz/harfbuzz#1682]
Since 47030b1855f04c0d75899ffb6f5021fea3c19b90, kerning of Type1 fonts does not seem to work any more ... (i.e. when, after `FT_New_Face(...)`, the corresponding AFM/PFM metrics/kerning file was also loaded, using `FT_Attach_File`).

Even more, `hb_font_funcs_set_glyph_h_kerning_func` is now deprecated (so I can't simply inject my own hook), but AFAICT no alternative was proposed...

My hope was, that by using harfbuzz, I could get rid of my old typesetting/kerning pipeline, but now I have to fall back to it to keep compatibility with old font formats (using latin scripts), and only use harfbuzz to gain good support of non-latin scripts ?

**Comment by behdad** [comment]
Umm. Yeah, okay.  I can put those back.  Would be enough for you if I revert that commit?

**Comment by smilingthax** [comment]
Well, only the parts in `src/hb-ft.cc` of the commit are needed (tested with current HEAD).
That seems to be the best option for now -- unless there is some upcoming Type1-support directly in harfbuzz that I haven't heard about (?).

The other thing I currently do in my old pipeline, is to return the last glyph codepoint and allow passing it back in at the next call to the kerning engine, as "pre"-first glyph codepoint, so that kerning still works across segments, when I break up the sequence for some reasons (e.g. color change, ...).
AFAIUI, this approach will already break down for non-latin scripts (i.e. when complex shaping is required)... but I thought about using the deprecated `hb_font_get_glyph_h_kerning` method to emulate my existing API, while having harfbuzz under the hood (and without having to call freetype directly), where complex shaping is not needed (different project which uses the same pipeline)... 

My main concern is that, when I have to use deprecated methods from harfbuzz to replace my existing code, the deprecated methods could be removed in any new version of harfbuzz, and then I'm stuck without any viable alternative (besides reviving my old pipeline).

**Comment by behdad** [comment]
I don't inherently have anything against adding Type1 support, if, say, Adobe was to contribute that (cc @blueshade7).  The multi-file setting is troublesome though.  I know some were pissed off when LibreOffice switched to hb-ot-font and lost Type1 support.  cc @khaledhosny 

Re kerning at run boundaries, as you said it's a hack and doesn't work with anything else.  For color etc changes you should shape the entire text and apply attributes separately.  In theory we can apply kerning at run boundaries since we have the pre/post context text.  We can, in theory, do the cmap mapping on those, ignore them for shaping, but include them for kerning.  Huge hack IMO, but probably would produce desired results when it has any effect at all.  cc @jfkthame who I believe is opposed to this :). cc @drott 

I'm not sure if I prefer to undeprecate kerning API, or keep it deprecated by put the FT impl back.  Maybe I undeprecate it and document it as needed to provide only non-OpenType/TrueType kerning.  We definitely don't plan to remove deprecated API anytime.  But yeah, I'll undeprecate it.  You have a good point.

**Comment by khaledhosny** [comment]
I still get the occasional LibreOffice bug report about Type 1 support, though I don’t personally miss it. Type 1 support i HarfBuzz won’t help LibreOffice at this point, though, as lots of other Type 1 related code was dropped (Type 1 needed to be handled differently at almost every step in the pipeline).

**Comment by blueshade7** [comment]
FWIW, Adobe is dropping support of Type 1 fonts from their own apps, e.g., Photoshop, InDesign.

**Comment by behdad** [comment]
Thanks. I'll just revert patch and depreciation here.

**Comment by behdad** [comment]
Okay I reverted the deprecations and the hb-ft part.  I should have just undeprecated the `h_kerning` part.  But was easier to do it for all.
