### ISSUE TITLE
Way for font to keep default-ignorable codepoint

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1786]
Currently we remove default-ignorables no matter what glyph or substitutions.  Would be nice to let font decide to show such a character.  This is being requested by the new Mongolian encoding model.  @lianghai asked me last night.

I think we should NOT remove those glyphs if any substitution happened to them.  We have that info already.

**Comment by dscorbett** [comment]
Alternatively, I think the Mongolian FVSes shouldn’t be default ignorable: in the new model, they don’t act default ignorable anymore, because the font is never supposed to ignore them.

**Comment by behdad** [comment]
I agree in general.  At the same time I think would be good to have this feature for whatever the font needs it.

**Comment by SClikes** [comment]
Please don't remove glyphs. You can change fonts or characters. If you do it again and again then it will harmful for your account.

**Comment by lianghai** [comment]
(Just a clarification in case people pick up an unnecessary fight later: We’re keeping the current Unicode Mongolian encoding model—which was defined in a very vague way, while the thing we’ve been working on is a comprehensible and standardizable shaping spec that should’ve been there since the beginning.)

> I think we should NOT remove those glyphs if any substitution happened to them. We have that info already.

This proposal sounds interesting. (I suppose stuff like ZWJ and ZWNJ are not a concern to this generalization because they need special treatment anyway?)

> Alternatively, I think the Mongolian FVSes shouldn’t be default ignorable: …

Well, yeah, I don’t even think this `Default_Ignorable_Code_Point` value is well understood at UTC. Shaping engines probably shouldn’t rely on it at all…

But yes, I’ve been thinking that I should try to get FVSes out of the `Default_Ignorable_Code_Point` set in Unicode 13.0 anyway.

**Comment by behdad** [comment]
> > I think we should NOT remove those glyphs if any substitution happened to them. We have that info already.
> 
> This proposal sounds interesting. (I suppose stuff like ZWJ and ZWNJ are not a concern to this generalization because they need special treatment anyway?)

Their effect takes place regardless.

**Comment by khaledhosny** [comment]
Already done in #2886
