### ISSUE TITLE
[graphite2] Threadsafety?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1829]
The code in hb-graphite2.cc, in particular `hb_graphite2_get_table` and `hb_graphite2_release_table`  looks suspicious.  One *cannot* safely remove a linked-list element and destroy it as another thread might be traversing the list at the same location...  We should just keep all tables and destroy them at the end.

This might be the cause for https://bugzilla.redhat.com/show_bug.cgi?id=1689037

cc @mhosken

**Comment by behdad** [comment]
Going to revert e4e74c2751ac24178086cce2811d34d8019b6f85 since seems to be causing crashes:
https://bugzilla.redhat.com/show_bug.cgi?id=1689037#c32

**Comment by behdad** [comment]
I'm not quite sure *why* we hit this in anaconda.  But it's clear that this is causing the issue.

**Comment by mhosken** [comment]
The way harfbuzz loads a graphite face, (using preloadAll), all font tables are released by the time the gr_make_face_with_ops call returns. This means that the engine is single threaded for the purposes of loading a face. But after that access may be multithreaded since none of its face data is written to during segment creation and also no tables are requested or released during segment creation. I'm not sure if that helps.

I'm not sure why two different threads would be accessing the same data blob of tables given all read and write to that linked list is inside the one function gr_make_face_with_ops, which is a single function thread.

**Comment by behdad** [comment]
I'm not familiar with graphite2 code to comment.  But clearly old code used to work and new work was buggy.  Can we just close this?  Any reason why the new code was preferable?

**Comment by mhosken** [comment]
No. Just trying to be tidy. Feel free to revert.

**Comment by behdad** [comment]
I reverted already.  While I like to get to the bottom of what's happening, I won't have time for it.  Closing, unless someone wants to investigate.
