### ISSUE TITLE
Please support bitmap fonts

### ISSUE THREAD

**Issue by z0z0z** [harfbuzz/harfbuzz#1897]
pango 1.44 dropped support for bitmap fonts

They blamed harfbuzz and said to make an issue report here.

People pretty mad about it, lot of people staying on pango 1.43 because 1.44 intentionally dropped support for bitmap fonts.

https://gitlab.gnome.org/GNOME/pango/issues/386

**Comment by khaledhosny** [comment]
HarfBuzz internal font fuctions are nit going to support non-OpenType fonts. Clients wishing to support other fonts can use different font functions implementation (like the FreeType font functions provided by HarfBuzz). Pango decision to stop supporting non-0penType fonts is result from not wanting to use FreeType, rather than a switch to HarfBuzz (Pango always used HarfBuzz).

**Comment by andreygursky** [comment]
Just to clarify. @behdad suggested in https://gitlab.gnome.org/GNOME/pango/issues/386#note_575021, it would be a matter of time to implement this. And if someone would do this, it would need to be merged in Harfbuzz.

**Comment by khaledhosny** [comment]
”HarfBuzz font functions” would mean doing it in Pango, not in HarfBuzz proper. Pango already overrides HarfBuzz font functions, and can support any font format not directly supported by HarfBuzz this way (as it was the case already when it was still using FreeType-based font functions).

**Comment by andreygursky** [comment]
@khaledhosny, thanks for clarifying.
