### ISSUE TITLE
Problem with Meinrad font

### ISSUE THREAD

**Issue by mestaritonttu** [harfbuzz/harfbuzz#1918]
From https://bugs.documentfoundation.org/show_bug.cgi?id=122836
https://www.saintmeinrad.org/media/1511/meinrad-chant-font-package_windows.zip

Comment from Khaled:
> The font has 3 cmap subtables (the stuff that maps characters to glyphs). Two map 0xF0?? range and one maps ASCII range. The layout engines needs to pick one of the three and HarfBuzz is picking the 0xFF?? one apparently, so ASCII input does not work.

**Comment by bungeman** [comment]
This font has three cmaps of the following types in the following order

Format 4 platform 0 enc 0 lang 0 0xFF?? (Unicode 1.0)
Format 6 platform 1 enc 0 lang 0 0x?? (Mac Roman)
Format 4 platform 3 enc 0 lang 0 0xFF?? (Windows Symbol)

Testing with

hb-shape MEINRADA.TTF "abc"
[.notdef=0+500|.notdef=1+500|.notdef=2+500]

however, if I remove the Unicode 1.0 format cmap then

hb-shape MEINRADA_no4000cmap.TTF "abc"
[Asmall=0+84|Bsmall=1+21|Csmall=2+252]

This works because the Windows Symbol cmap is selected and it has the fun rule where any 0xFF?? mapping also applies to 0x??. HarfBuzz currently prefers the Unicode 1.0 cmap table to the Windows Symbol table, which produces the observed results. It appears this is done in cmap::find_best_subtable, where (0, 0) is preferred just ahead of (3, 0).

This should at least explain what is happening. However, I have no idea what the right thing to do is. Some applications may go digging through all available cmaps to look for mappings while others just use the 'best' cmap (and applications may disagree on which is 'best').

**Comment by behdad** [comment]
We should prefer symbol cmap if available.  I'll fix that.

**Comment by behdad** [comment]
FWIW, Ned confirmed that CoreText does *not* prefer Symbol to Unicode cmap subtable. And I tested with `hb-shape --shaper=coretext` and confirmed that.

Not sure what that means for us at this point. Just documenting.
