### ISSUE TITLE
How to use/implement font fallback using HarfBuzz?

### ISSUE THREAD

**Issue by ActuallyaDeviloper** [harfbuzz/harfbuzz#1957]
I am wondering what the proper recommended way is to implement a 'fallback font' mechanism using HarfBuzz. My situation is that I have a list of 'backup fonts' and I want to use those whenever glyphs are missing in the main font. My question is what is the best way to achieve that using HarfBuzz.

Checking the internet did not proof very helpful. I tried to see what other people are doing and the Pango library appears to be using `hb_face_collect_unicodes`. However, is this the recommended way? I am wondering because input codepoints don't necessarily correspond directly to the output glyphs. For example isn't it possible that a font is missing the `á` codepoint but has both `a` and the diacritic as a combining character? In this case wouldn't  `hb_face_collect_unicodes` wrongly suggest to me that `á` isn't supported by the font? Also according to my initial testing `hb_face_collect_unicodes` misses new lines, default ignorables and returns an empty set for bitmap fonts.

Do I have to handle these cases myself or is there a better way to do fallback aware shaping?
And if this is the way to do it, what cases do I precisely need to handle to not reject characters that actually would work fine?

**Comment by khaledhosny** [comment]
Applications usually do it in one of the following ways:
1. Determine font character coverage (by e.g. using `hb_face_collect_unicodes()`) and use fallback fonts when shaping characters outside of this coverage (iterating on the fallback fonts using their own character coverages).
2. Shape the text first, then detect the ranges of characters not supported (e.g. that has glyph index 0), and loop on fallback fonts and shape with them until no unsupported characters are left.

The first is more commonly used, but it has the drawbacks you mentioned. The later is superior (when shaping with Harfbuzz since HarfBuzz will try NFC and NFD normalization forms of unsupported characters before giving up), but can be slower when there are many fallabck fonts, so some optimizations are needed.

Either way, it is always preferable to shape grapheme clusters using the same font, so when seeing an unsupported character one should make sure the whole grapheme cluster it is part of is shaped by the same font.

**Comment by ActuallyaDeviloper** [comment]
Thank you for your response! I have now implemented the second method suggested and it seems to be working so far.

Now I am just wondering whether it's save for me to rely on missing characters to be 0. What if there is a replacement character like U+FFFD in the font?

**Comment by khaledhosny** [comment]
The missing character index is whatever the font functions return for missing characters, which is 0 in the font functions maintained by HarfBuzz.

The replacement character is a regular character and if the font has a glyph for it HarfBuzz will use. Unless the input already has U+FFFD, HarfBuzz will only insert it in case of encoding errors (the choice of replacement character is customizable as well).

**Comment by ActuallyaDeviloper** [comment]
Okay, great, thank you. Then I will just leave it the way it is.
