### ISSUE TITLE
Move CFF subsetters to _subset2 and make it the default

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1981]
AFAICS CFF tables are the only _subset users and with moving those to _subset2 we can drop the  weird 2 suffix, curious to know anything is blocking that change? @blueshade7

**Comment by blueshade7** [comment]
Just I am tied up by some other task, unlikely to be able to work on it soon myself.
_subset2 would substantially simplify CFF/CFF2 subsetting I believe. I wish I had it when I started working on it, but wasn't, unfortunately.

**Comment by ebraminio** [comment]
Feel free to put some time for it anytime you like, I will also try myself. Thank you very much :)

**Comment by blueshade7** [comment]
I gave it some thought.

Currently CFF/CFF2 subsetters based on `_subset` run in two-phases. During the first phase, sub-tables are generated determining each size & offset, finally the total size.
By using `_subset2`, some of this can be done in one phase.

Table offsets fixed at 2 or 4-bytes in length (thanks to myself) can use the existing mechanism of`hb_serialize_context_t::add_link` & `resolve_links`.
_length_ of Private dict may need an extension to this.

INDEX data, such as CharStrings or Subrs still need to be generated in two-phases, I believe, since the offset size (1 thru 4) cannot be determined until the total size is known. Fixing its size at 4-byte can be prohibitively wasteful. Using the original size may not work with desubroutinized CharStrings (and again can be wasteful).

iter syntax must be handy at various places.

**Comment by blueshade7** [comment]
created `subset2-cff` branch for this work

**Comment by ebraminio** [comment]
Thank you very much, just saw it, looks nice and complete actually, feel free to submit, will merge it if you don't have any concern, thanks!

**Comment by blueshade7** [comment]
The current impl is still written a-la `_subset`, calculating sub-table offsets in first pass, serializing in second pass, not benefitting much from calling `_subset2`. I am planning to rewrite them with `push`/`pop_pack`/`add_link` as much as possible.
There is some awkwardness in doing so though. By the time calling `add_link` for an offset serialized in a Dict, the corresponding sub-table needs to be packed & `objidx` must be known, i.e., tables need to be serialized bottom-up, in reverse order from the way it is currently written.
Another thing is that calculating hash while packing a huge singleton sub-table like CharStrings seems a waste, as it will be unlikely shared.

**Comment by ebraminio** [comment]
Oh now I see, understandable. Just if this won't kill the motivation to continue the mentioned rewrites I'd say let's have the patch so we can drop *2 suffix if you agree.

**Comment by blueshade7** [comment]
No problem about merging what I have now to master then continue work from there. I will create PR.

**Comment by ebraminio** [comment]
Thank you so much :)

**Comment by ebraminio** [comment]
Fixed by #2153 and #2226 (and others that are linked above). Thanks!
