### ISSUE TITLE
Difference in behavior between HarfBuzz and DirectWrite

### ISSUE THREAD

**Issue by sharoncorrell** [harfbuzz/harfbuzz#2000]
My understanding is that behavior of Harfbuzz and DirectWrite should be identical. I'm seeing a difference when I try to add glyph reordering directly in the OpenType FEA code.

(I am having to implement some reordering in the OpenType directly due to the fact that this font needs to be usable in InDesign which does not support Lepcha reordering.)

My guess about what is happening is that either (1) automatic reordering is happening at a different place in the two engines, which makes the two reordered glyphs end up in a different place relative to each other, or (2) the rules controlling reordering are different.
[ReorderBug.zip](https://github.com/harfbuzz/harfbuzz/files/3678743/ReorderBug.zip)

Also it appears that when I use `languagesystem DFLT dflt` in my FEA code instead of `languagesystem lepc DFLT`, the resulting font does not perform automatic reordering in Harfbuzz (as I would expect) but it still does reordering in DirectWrite. I am testing Harfbuzz in hb-shape on a Linux bionic VM and DirectWrite in Notepad on Windows 10 (v 1903)

**Comment by mhosken** [comment]
This bug boils down to a miscategorisation of U+1C29 which should be VPre but was changed to VPst during a spate of Vpre --> VPst fixes. This one got erroneously fixed (in rev ceef311dc). Please simply revert the change such that U+1C29 becomes VPre.

**Comment by behdad** [comment]
Thanks Martin.

**Comment by dscorbett** [comment]
MinBug.txt contains ⟨ᰀᰧᰵ⟩ <U+1C00, U+1C27, U+1C35>, so why do you mention U+1C29, @mhosken?

**Comment by sharoncorrell** [comment]
I think you can ignore that example. After more research, it is only 1C29 that is wrong.

**Comment by dscorbett** [comment]
The USE spec says that a VOWEL_PRE should be reordered before the base glyph, but U+1C29 has Indic_Positional_Category=Top_And_Left in Unicode 12.1, so it is a VOWEL_PRE_POST and _not_ reordered. HarfBuzz implements it accordingly. However, using the OP’s Mingzat-Regular.ttf in Notepad in Windows Server 2019, I confirm that the vowel sign in ⟨ᰀᰩ⟩ _is_ reordered. This is because the USE spec is missing some overrides; see https://github.com/harfbuzz/harfbuzz/issues/1012#issuecomment-429726755. I’ll make a PR to add them to HarfBuzz.

**Comment by dscorbett** [comment]
I decided to just fix U+1C29. Some of the other overrides I linked to are questionable.
