### ISSUE TITLE
Make HB_BUFFER_FLAG_DO_NOT_INSERT_DOTTED_CIRCLE run-time configurable

### ISSUE THREAD

**Issue by norbusan** [harfbuzz/harfbuzz#2036]
It would be nice to be able override the default `HB_BUFFER_FLAG_DO_NOT_INSERT_DOTTED_CIRCLE=0` via environment variables or some similar approach. In particular because luaharfbuzz does not exhibit this part of the API, as well as for precompiled programs that cannot be easily changed.

The reason for the request is that with some fonts and consonant stack in Tibetan and Bangla (at least) these lovely dotted circles pop in instead of a consonant stack.

**Comment by behdad** [comment]
That would help some users, yes.  But not the best way to address this issue.  I prefer fixing the shaping instead.

**Comment by norbusan** [comment]
Agreed with that 100%, but we have to think of those who are stuck with library versions they cannot update, don't have permissions, or the ability. I can compile myself a new harfbuzz anytime, but ...

**Comment by zauguin** [comment]
@norbusan Especially looking from a TeXnician perspective I don't like the idea of affecting things like this through environment variables.
It only leads to documents which no longer give reliable, portable rendering because they now depend on the environment of the user.

This especially is a problem because I don't see any case where `HB_BUFFER_FLAG_DO_NOT_INSERT_DOTTED_CIRCLE` is in any way system-specific, at most it might be document specific: If you have a document which creates dotted circles in unexpected places, you might want to disable them for this specific document or possibly for this specific font/situation. You do not want your document to magically break again on other systems just because they use another environment. (I'm actually thinking about overwriting `HB_OPTIONS` in LuaLaTeX to avoid such problems with the AAT option)

If luaharfbuzz doesn't expose some API, the better fix IMO is [to expose the API](https://github.com/ufyTeX/luaharfbuzz/pull/46) and allow applications to decide by themself how to handle these options.

**Comment by norbusan** [comment]
@zauguin indeed, I agree completely - that was actually the first place I looked into, but then somehow decided to ask here. Thanks also for preparing the patch and PR, very much appreciated!

Thus, I think this issue can be closed since it actually should be done in luaharfbuzz. Thanks.
