### ISSUE TITLE
Version of hb-subset that doesn't depend on GLib

### ISSUE THREAD

**Issue by dnfield** [harfbuzz/harfbuzz#2074]
I'd like to build hb-subset in an environment ([Flutter Engine](https://github.com/flutter/engine)) that doesn't currently have a good way to build GLib.  It also looks like GLib is only used for options parsing (and file reading/string manipulation?).

I'd be willing to take a crack at rewriting either `options.hh` and `options.cc` (or, alternatively, rewriting `utils/hb-subset.cc` to depend on a different but compatible options parser) to not use GLib.  

Would you be open to a patch that does that? Are there compatibility requirements that I should know about?  In particular, are existing tests good enough to cover breakages there?

Alternatively, I'm going to have to look at pulling in GLib to the build environment and creating the relevant build rules etc.

Related: https://github.com/flutter/flutter/issues/43642

**Comment by behdad** [comment]
I'm open to porting entirety of `util/` to something smaller than glib.  C++ stdlib is a possibility, just very slightly complicates our build since we go out of our way to tell autoconf to /not/ link to that.

And yes, we use glib exactly for just what you said.

We also like to port test/api away from GLib to googletest or something else, ideally importing it in tree instead of depending on external installation.

Thanks in advance!  Would be easier if we discuss the direction before you go ahead and implement.

We don't have tests for the commandline utilities themselves.  But getting the option-parsing close-enough shouldn't be that hard.

**Comment by behdad** [comment]
Also, you can definitely use the subsetter library without the commandline tool.

**Comment by dnfield** [comment]
I did consider writing our own wrapper around the subsetter library, but it'd be preferable to just use the one from here if possible. What's the best way to discuss direction?

**Comment by behdad** [comment]
Just tell us here what you suggest replacing with, we agree, you send pull request, we review and merge. :). Thank you!

**Comment by dnfield** [comment]
I dug into this a bit more.  I was hoping the options parsing would be semi-trivial to replace - it's not super hard but it would take me longer than just writing my own utility at this point (https://github.com/flutter/engine/compare/master...dnfield:font_subset).

I may come back to this if that turns out to be a bad option for us for some reason, but for now I don't have plans to address this further.
