### ISSUE TITLE
Reading vf-glyf extents without allocating memory

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2095]
We are using a [vector in glyf-vf extents reading](https://github.com/harfbuzz/harfbuzz/blob/57b1534198ae07c840010cff5af7997c5f738e88/src/hb-ot-glyf-table.hh#L929) so are allocating memory while reading extents for variable glyphs in glyf table, my question is given how glyf and gvar work is it possible to make this process without allocating any memory? This is more important to me as the proposed glyph decomposition API uses more of that glyf extents reading code path so like to know if is possible in theory to go without allocating memory here, or, is it only possible for non-vf-glyf ones so should have a separate code path for that? (If that is even possible also) 

Thanks

**Comment by blueshade7** [comment]
IMO, allocating various memory blocks is a natural implementation for unpacking deltas in gvar and flattening composite glyph points.

A possible practical solution (workaround) would be to reserve static arrays on stack and use them if data fit in.

`hb_vector_t` used to have such static array in it, but we got rid of it because of a ctor/dtor issue when element is a complex object IIRC, and nesting vector leads to size explosion.

Since in this case element is simple and not nested, maybe we might want to revive such a vector as a variant?

**Comment by ebraminio** [comment]
Ok, so guessing we are good here, if I am following https://github.com/raphlinus/font-rs/blob/master/src/font.rs correctly iterating `glyf` components works without allocation(?) but guess handling gvar isn't possible this way, do you agree with my conclusion?

**Comment by blueshade7** [comment]
Yes, iterating over composite glyph points without flattening into array is possible I think. No allocation for run-length encoded deltas and inferred deltas in `gvar` is practically near-impossible I think.

If your objective is not _absolutely no allocation_, but _most of the time no allocation_ for a better performance etc, then you could use static arrays as explained above.

FYI, TrueType spec was originally designed to let the font declare the maximum number of points etc in `maxp` table so that a font engine can pre-allocate that much memory upfront and reuse for all glyphs. This table became a source of many security issues however. Apple is not using it I believe, so is HarfBuzz.

**Comment by ebraminio** [comment]
Great, thank you so much

**Comment by ebraminio** [comment]
Closing this but referencing to it in future given your great input. Thank you very much
