### ISSUE TITLE
hb_inc_bimap_t improvements

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2096]
Change in https://github.com/harfbuzz/harfbuzz/pull/2091 is wrong.

Calling `add` on a null object should silently do nothing.  Callsites should not need to check.

`add_set` can be called `extend` to reflect Python naming, and should accept any iterator of `hb_codepoint_t`, not just set.

**Comment by blueshade7** [comment]
I am not sure what you mean. Maybe you are mentioning some related issue, not this particular PR which specifically fixes a crash caused by `hb_set_t::add()` being called with `this`=nullptr.
https://github.com/harfbuzz/harfbuzz/blob/a32ecc15aec6518f5a126fb8f3643e563327f74d/src/hb-ot-var-hvar-table.hh#L188-L189
When `outer` is out of range, `->add` is called upon nullptr.

Maybe you are suggesting to add `if (unlikely(this==nullptr)) return;` to `hb_set_t::add()`?
I don’t see such checks elsewhere though.
