### ISSUE TITLE
[subset] feature closure takes long time with a fuzzed font

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2191]
This issue was originally reported by oss-fuzz as: https://crbug.com/oss-fuzz/19802
Also mentioned in #2186.

subset-fuzzer takes a few minutes to complete when run locally with the fuzzed font: 
[clusterfuzz-testcase-minimized-hb-subset-fuzzer-6276691949518848.zip](https://github.com/harfbuzz/harfbuzz/files/4243304/clusterfuzz-testcase-minimized-hb-subset-fuzzer-6276691949518848.zip)

Time appears to be spent in function:
https://github.com/harfbuzz/harfbuzz/blob/f00eb4ebfa02dea593c4842a7672aa2640a6bbf2/src/hb-ot-layout.cc#L1253
trying to collect all features from all languages, each fuzzed to become a very large number.

Since OT spec defines 600+ languages and 130+ features at this time of writing, probably it would make sense to set a limit on each, with some extra room to grow.

**Comment by blueshade7** [comment]
Actually another oss-fuzz timeout issue https://crbug.com/oss-fuzz/18529 turned out to be similar in that its fuzzed font contains 2054 scripts and 2648 feature indices. This is not so excessive as 19802 so closure completes in reasonable time, but takes a hit during GSUB serialization. Additionally, output subset GSUB table becomes very large exceeding the initial estimate output size and even the input file size, retrying six times in `_subset2` until it eventually fails.

Setting limits on the numbers of scripts and feature indices should work as a fix for this one too.

**Comment by garretrieger** [comment]
FYI, current script and language limits are defined here: https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout-common.hh#L56 for scripts it's currently 500. I don't believe we have a limit on features yet. Adding that would probably help out.

**Comment by blueshade7** [comment]
https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/fonts/clusterfuzz-testcase-hb-subset-fuzzer-5717414645334016 also takes long as its GSUB has 17672 features.

**Comment by blueshade7** [comment]
The two places where setting a limit may be required are:
https://github.com/harfbuzz/harfbuzz/blob/c400cb8863abb5f894e021da5d524c1e28b1e980/src/hb-ot-layout-common.hh#L475-L476
and
https://github.com/harfbuzz/harfbuzz/blob/c400cb8863abb5f894e021da5d524c1e28b1e980/src/hb-ot-layout-common.hh#L873-L874
 feature indices or lookup indices are directly read from a fuzzed table into each kind of index set by calling `hb_set_t::add_indexes_to()` bloating the set as the result.

**Comment by blueshade7** [comment]
One possibility is something like:
```
#define HB_MAX_FEATURES 500

 void add_feature_indexes_to (hb_set_t *feature_indexes) const 
 {
  if (unlikely ((featureIndex.len > HB_MAX_FEATURES)
             || (feature_indexes->get_population () > HB_MAX_FEATURES)) return;
  featureIndex.add_indexes_to (feature_indexes);
} 
```
How's that?

**Comment by blueshade7** [comment]
Let me explain my reasoning.

This test is intended to catch cases where an index set is _likely_ to become _much_ larger than the limit. Ideally, `add_index_to()` should check population of the set each time adding an index to the set, but `get_population()` is not a cheap call and an exact test is unnecessary to catch a fuzzed font.

The condition `featureIndex.len > HB_MAX_FEATURES` may be risking a chance of rejecting an index table containing the same index repeatedly, but a sane font shouldn't be built like that.

A single condition `feature_indexes->get_population () > HB_MAX_FEATURES` *after* adding indices to the set would ensure counting unique indices, but damage may have been already done to the set by that time.

The same condition before adding an index table to the set is to catch a case where a set has already exceeded the limit as the result of accumulation from multiple index tables, and to prevent adding more.

**Comment by garretrieger** [comment]
Seems like what we're trying to limit is the number of add() calls to the feature index set. So we should track and limit that directly. As you noted the total number of unique features isn't that important since a fuzzed font can re-use a small set of indices many times and still slow things down.

I recommend adding a visited feature index count to  hb_collect_features_context_t (https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout.cc#L979) similar to what we have there for language and script. Then just before add_feature_indexes gets called (https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout.cc#L1051) increment the count with the number of feature indices contained in the LangSys and don't call add_feature_indexes if the limit has been exceeded.

**Comment by blueshade7** [comment]
> I recommend adding a visited feature index count to hb_collect_features_context_t […] similar to what we have there for language and script.

I am not sure what you are suggesting here. Language and script are where (multiple) feature indices are collected from, so preventing to re-visit the same language/script saves effort. In comparison, feature indices are the collected result. Checking if a particular index is already visited before adding it to feature_indexes set does not save any. Also, the visited feature index count is already available as `feature_indexes.get_population ()`. No need to count it separately. Checking if it is likely to exceed the limit before calling `add_feature_indexes_to()` is almost identical to what I proposed above.

**Comment by blueshade7** [comment]
I am inclining to merge two conditions in my above check into one: `featureIndex.len + feature_indexes->get_population () > HB_MAX_FEATURES`. Simpler, but on the down side, if `feature_indexes` contains the same set of indices in `featureIndex`, this condition is halving the limit in effect. To counteract, we can set the limit high, or use `HB_MAX_FEATURES*2` in the condition.

There is only one call to `LangSys::add_feature_indexes_to()` in `langsys_collect_features()` so a check could be in caller or callee, but there are two calls to `Feature::add_lookup_indexes_to()`, so I guess better to have a check in callees for conciseness & consistency.

I am going to create a pull request for this.

What values (and names) should I use for `HB_MAX_FEATURES` and `HB_MAX_LOOKUPS`? Suggestions?

**Comment by garretrieger** [comment]
Here's what I was thinking, hopefully this code illustrates the concept better: https://github.com/harfbuzz/harfbuzz/commit/d7b26f94a4ee1688802e7d4b5d61e3bf4985b4a1

The reason we don't want to use feature_indices->get_population() is that tracks the number of unique feature indices. It's possible to have a font which has thousands of features indices referenced from LangSys's but all indices have the same value. In that case feature_indices->get_population() is going to be 1 and limiting based on that will be ineffective. Second, as you mentioned  feature_indices->get_population() is slow, it requires a full scan of the set to compute if the set has been modified since the last call. This approach counts up l.featureIndex.len which is going to be much faster.

Set add()/has() calls have logarithmic complexity and are likely where most of the time computing the collection is spent, so my change specifically limits the number of set add() operations to a maximum number.

**Comment by garretrieger** [comment]
Timed, my proposed approach and it reduces time to run that fuzzer input from ~4.5s to ~0.5s.

**Comment by blueshade7** [comment]
Now I see. Since you already have the code, can you take over, or do you want me to do it?

I noticed that boolean result returned by `visited_feature_indices()` may be better to be opposite, as it returns false when limit exceeded, `visited()` for script and langsys work the other way.

**Comment by garretrieger** [comment]
Sure can do, I'll turn this into a PR.

**Comment by blueshade7** [comment]
thanks
