### ISSUE TITLE
[subset] lookup closure needs limiting

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2224]
oss-fuzz reports as https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21025 that hb-subset-fuzzer is timing out in `hb_ot_layout_lookups_substitute_closure()` with lookup counts in GSUB table fuzzed to become very large numbers.

[clusterfuzz-testcase-minimized-hb-subset-fuzzer-5662792105590784.zip](https://github.com/harfbuzz/harfbuzz/files/4283032/clusterfuzz-testcase-minimized-hb-subset-fuzzer-5662792105590784.zip)

**Comment by garretrieger** [comment]
I'll put together a PR to add some limits similar to what I did for features.

**Comment by ebraminio** [comment]
As https://github.com/harfbuzz/harfbuzz/pull/2246#issuecomment-598091890 can you have a look at https://crbug.com/oss-fuzz/21091 also? Thanks!

**Comment by ebraminio** [comment]
Oh I see https://github.com/harfbuzz/harfbuzz/pull/2247 why failed, our shape fuzzer has lower timeout bar, perhaps we should also lower closure limit even more.

**Comment by garretrieger** [comment]
I tested a few real fonts with large numbers of lookups and the highest lookup index count I could find was ~10,000 so I'd be wary of lowering the limit (20,000) much further.

**Comment by garretrieger** [comment]
If the timeout continues to be an issue I'll run another profile on the test case and see if there's any other fixes that can be made to speed things up.

**Comment by ebraminio** [comment]
> I tested a few real fonts with large numbers of lookups and the highest lookup index count I could find was ~10,000 so I'd be wary of lowering the limit (20,000) much further.

You are right.

> If the timeout continues to be an issue I'll run another profile on the test case and see if there's any other fixes that can be made to speed things up.

Just that we can't upload testcase of https://crbug.com/oss-fuzz/21091 to the repo but I wish we could.

**Comment by ebraminio** [comment]
Either we have a oss-fuzz delay or https://crbug.com/oss-fuzz/21025 and https://crbug.com/oss-fuzz/21091 are not considered fixed by #2246 (see my timing https://github.com/harfbuzz/harfbuzz/pull/2246#issuecomment-598091890 here) so other workarounds are needed also apparently.

**Comment by ebraminio** [comment]
Was a oss-fuzz delay, thanks!

**Comment by ebraminio** [comment]
another closure lookup timeout https://oss-fuzz.com/testcase-detail/5713850117914624 

@garretrieger can you have a look? Thanks!

**Comment by garretrieger** [comment]
Yeah will do.

**Comment by garretrieger** [comment]
Alright, this ones a bit strange. Profile shows time is spent in the glyph closure for Chaining Contextual Substitutions. However, tuning the max lookup indices down has no affect on the run time.

For some context Chain Context Sub's have three tiers of one to many relationships which eventually points to a bunch of lookup indices. So my theory is there's a single chain rule with a huge number of lookup indices underneath it all which recurse back into similar chain rules. Since we use depth first search during the closure we immediately recurse down to max recurse depth where each level of the recursion is a huge chain rule. The lookup limit is then hit dealing with the lowest level chain rule. However, we've still  got all of the massive chain rules above which have been started and despite lookup limit being reached the closure code for each of those will still fully expand and attempt to recurse into each individual lookup. This has the effect of far exceeding the overall lookup limit.

To fix we'll need to update the chain context closure code to check for lookup limit being exceeded while it's expanding out all of it's sub lookups and bail out of the process early if the limit is hit.

**Comment by ebraminio** [comment]
@garretrieger another closure failure but is caught by "hb-shape-fuzzer" https://oss-fuzz.com/testcase-detail/5158673602314240 please have a look if you got some free time :)

The just subset fuzzer caught issues seems however unrelated to this one, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21503 feel free to open a new issue for any of them.

Thanks!

**Comment by garretrieger** [comment]
The shape fuzzer is the same problem, but this time for Context instead of Chain Context. PR #2294 should fix it. Looking into the hb-subset-fuzzer which appears to be happening during subsetting.
