### ISSUE TITLE
Rendering multi Tibetan vowel u  does not match Uniscribe

### ISSUE THREAD

**Issue by FFFlyFish** [harfbuzz/harfbuzz#2238]
For example, Tibetan string  "U+0F45  U+0F74 U+0F74 U+0F74" ,the follow 3 vowel u is vertical layout, but Uniscribe is horizontal.

https://stackoverflow.com/questions/60616119/support-tibetan-vowel-u-by-harfbuzz

**Comment by jfkthame** [comment]
HarfBuzz does not enforce all the same limitations on vowel-mark combinations as Uniscribe. The use of a repeated u-vowel (or other vowel mark) on a single base letter is not normal in Tibetan writing, AFAIK, but from a text-encoding point of view there's no reason it should be impossible, and the resulting rendering is quite logical.

(In general, rendering engines should not try to enforce the orthographic/spelling conventions of a particular language, as this may prevent users doing otherwise-reasonable things - whether for a different language, or for unusual literary effects, or whatever - with the available characters.)

So I don't think we want to change HarfBuzz behavior here. It's known to be more accepting of some unconventional sequences - that's by design.

**Comment by ebraminio** [comment]
Resolved as https://stackoverflow.com/questions/60616119 also, so :)
