### ISSUE TITLE
[meson] build ragel artifacts

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2242]
our meson port doesn't have building HB_BASE_RAGEL_GENERATED_sources from HB_BASE_RAGEL_sources equivalent but it should.

**Comment by tp-m** [comment]
How are these supposed to work?

It looks like the generated sources are actually checked into git, so would it be ok to hide them behind a custom target so they can be updated manually as/when needed? Or we only generate them if `ragel` is found and otherwise use the checked-into-git versions?

If we make `ragel` a hard dependency that would be unfortunate for building on Windows and pretty much all non-Linux OS.

**Comment by khaledhosny** [comment]
Currently `configure.ac` checks for ragel with `AM_MISSING_PROG`, so only when `ragel` executable is needed to regenerate the files a warning will be issued. This makes it harder to miss updating the generated files while still not requiring ragel when building from tarball.

**Comment by tp-m** [comment]
Right, just haven't entirely figured out yet under what circumstances it would actually be considered 'neeed' and via what mechanism in `Makefile.am`. Would it be done as part of disting or when?

**Comment by khaledhosny** [comment]
Currently it would be the regular timestamp checking of make.

**Comment by behdad** [comment]
For a developer, we assume they have ragel, and we want everything to automatically regenerate and work as they edit the ragel sources.

When built from tarball, we don't want to require ragel.

Note that currently we have a bug such that the timestamps from the tarball may confuse `make` into thinking that the ragel sources are newer than the bundled generated file.  We couldn't find any easy solution to that.

**Comment by tp-m** [comment]
Took a stab at this here: https://github.com/tp-m/harfbuzz/commits/meson-ragel-gen

But it breaks `make check` on autotools because `check-includes.sh` doesn't like the fact that I changed the includes for the generated headers to angle brackets (which is required to make them get picked up from the build dir in Meson and probably cmake too, and probably autotools too if one uses builddir != srcdir there, though I guess no one does that for development).

What is the rationale/background for this check?

The installed `hb-*.hh` header files are hidden in a `harfbuzz` subdir so can't really be accidentally picked up from the system include dirs.

**Comment by khaledhosny** [comment]
> and probably autotools too if one uses builddir != srcdir there, though I guess no one does that for development

I always do out-of-tree builds, no issue with includes from the generated files. `make distcheck` does an out-of-tree build as well, so it would have caught such an issue.

**Comment by tp-m** [comment]
How do you know it's actually using the generated files in those cases? Everything will just continue to work fine if it picks up the pre-existing files, no? I only caught it because I put `#error`s into the checked in headers to double-check it's picking up the right ones.

**Comment by tp-m** [comment]
I feel extremely stupid asking this, because I must be missing something really obvious, but: how do I actually make autotools check for and pick up the `ragel` binary?

For me it doesn't even check for it, `configure` just defaults to the `missing` script (i.e. `configure` doesn't even contain code to check for it afaict).

I suspect this is because maintainer mode is not enabled, but `configure.ac` doesn't even contain `AM_MAINTAINER_MODE` and `configure` doesn't list any `--{disable,enable}-maintainer-mode` option either.

**Comment by ebraminio** [comment]
Any chance with Meson to write to source directory instead build dir so no need to turn `#include ""` to `#include <>`?

**Comment by tp-m** [comment]
> Any chance with Meson to write to source directory

That's a big no-no really. It could be hidden behind a custom target, but I wouldn't want to do that as part of the normal build.

Perhaps we could move these pre-generated files into a subdirectory or different directory, then we could just add the extra include if rygel is not available? Then the `#include <>` wouldn't be needed.

**Comment by khaledhosny** [comment]
We want to update the files in the source tree, otherwise committing them would be error prune. The idea of having the generated files in the source tree is to allow users like Chrome (that does not use our build system) to build directly from Git checkout without pre-configuration.

**Comment by ebraminio** [comment]
> That's a big no-no really. It could be hidden behind a custom target, but I wouldn't want to do that as part of the normal build.

I think we need some flexibility here, we used to not have generated in repo even but changed with https://github.com/harfbuzz/harfbuzz/commit/abc82b4 and https://github.com/harfbuzz/harfbuzz/commit/b91e8da3

**Comment by tp-m** [comment]
Either way, can anyone shed some light on my autotools question?

**Comment by tp-m** [comment]
> can anyone shed some light on my autotools question?

PBKAC - the missing script is just always doing the check at compile time, not configure time, and always writes to the srcdir when updating.

Anyway, I'm sure we can find a solution that satisfies all requirements in some way.

**Comment by ebraminio** [comment]
have uploaded a draft here #2357

**Comment by ebraminio** [comment]
As #2357 but not ideal, let's merge and see what else we can do as the general direction apparently considered correct per https://github.com/mesonbuild/meson/issues/7156
