### ISSUE TITLE
c370da45 causes regressions for Chrome printing in BlueBeam Revu viewer software

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2356]
Please see https://bugs.chromium.org/p/chromium/issues/detail?id=1071958 for details.

c370da45, which according to the commit description, removes the EncodingRecord for an empty CMAP type 4 table causes regressions in BlueBeam Revu viewer software.

Since I assume the expected subset space saving for this change to be rather small, can we revert this change or find a solution that's compatible with the above viewer software?

I can't directly assign to @qxliu76 - (not registered as contributor in this repo yet?) - assigning to Garret as proxy. Thanks in advance.

**Comment by garretrieger** [comment]
Alright, so I believe what's happening here is that Chrome requests a subset using glyph ids only. Currently the subsetting code for cmap only uses the set of unicode codepoints requested to determine which mappings to keep/drop. Since only glyph ids were requested that means everything in the cmap gets dropped and due to the above change then the encoding record also gets dropped. This must cause issues for the affected pdf viewer which probably assumes the existence of at least one cmap sub table.

To fix we should update cmap subsetting to retain any mappings that point to glyph ids in the set of explicitly requested glyphs. This matches what fontTools does: https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L2179.

**Comment by garretrieger** [comment]
@qxliu76 can you update cmap subsetting to do that?

**Comment by behdad** [comment]
> To fix we should update cmap subsetting to retain any mappings that point to glyph ids in the set of explicitly requested glyphs. This matches what fontTools does

Sounds good to me.  Thanks.

**Comment by drott** [comment]
@qxliu76, @garretrieger thanks for fix proposal and working on it. Would it be possible to revert c370da45 on master while we wait for the fix?

**Comment by garretrieger** [comment]
Yes, should be fine to revert in the meantime. @qxliu76 can you send out a PR for the revert?

**Comment by drott** [comment]
Thanks, rolling the revert into Chromium.

**Comment by drott** [comment]
@garretrieger @qxliu76 - thanks for making these changes. Just to clarify, this is expected to be safe to roll into Chromium without regressing again?

**Comment by qxliu76** [comment]
> @garretrieger @qxliu76 - thanks for making these changes. Just to clarify, this is expected to be safe to roll into Chromium without regressing again, or does this require changes in how Chromium uses hb for subsetting?

I did not run Chromium regressions. Could you help to check if the issue is fixed in your regressions?

**Comment by ebraminio** [comment]
> Just to clarify, this is expected to be safe to roll into Chromium without regressing again, or does this require changes in how Chromium uses hb for subsetting?

Yes, it should be

> I did not run Chromium regressions. Could you help to check if the issue is fixed in your regressions?

It was somehow a manual test, per https://bugs.chromium.org/p/chromium/issues/detail?id=1071958#c14 Bluebeam Vu also exhibits the issue also which guess is this one https://download.cnet.com/Bluebeam-Vu/3000-18497_4-75710370.html but I couldn't run it on Wine so a Windows machine will be needed I guess.

But it should be fine I believe. Thanks for the all works @qxliu76 and @drott
