### ISSUE TITLE
"لَمَّا" shapes incorrectly with "Geeza Pro.ttc"

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2358]
$ ~/dev/harfbuzz/util/hb-view /System/Library/Fonts/GeezaPro.ttc  "لَمَّا"

![LAM_MEEM_ALEF](https://user-images.githubusercontent.com/1021784/79871435-0144df00-83ed-11ea-8a32-77c02b9cbe96.png)

**Comment by drott** [comment]
CC @jfkthame

**Comment by jfkthame** [comment]
Yeah, I get the same broken rendering in Firefox, too. Disabling harfbuzz for AAT fonts (so that we shape with CoreText), it looks OK (although we don't get the initial lam-meem ligature; this seems to be blocked by the presence of the <064E,0651> combination on the meem).

FWIW, the rendering remains broken even if you drop U+0651 from the string, but removing either one of the U+064E characters resolves it.

I don't really know much about the AAT implementation in harfbuzz, that's basically @behdad's code.

**Comment by behdad** [comment]
Umm. Is really hard to debug.

**Comment by behdad** [comment]
After the ligation we get two fatha glyphs in a row.  I'm guessing the kern state machine fails at that and we don't handle failure the way CoreText does.  We should jump back to baseline maybe...

**Comment by drott** [comment]
Btw, this was with Geeza Pro from Mac OS 10.14, but seems to reproduce similarly on Mac OS 10.15.

**Comment by behdad** [comment]
Yes I can reproduce just fine (even on 10.11).  Asked Ned for help and he sent me some logs.  I'll try to debug.

**Comment by drott** [comment]
Forgot to mention, spun off from https://crbug.com/1071154

**Comment by jfkthame** [comment]
@behdad or @ebraminio Would one of you be able to tag a release that includes this fix sometime soon? That'd be helpful to people who prefer to take a specific release rather than cherry-picking fixes. Thanks!

**Comment by ebraminio** [comment]
Sure, specially since resource fork improvements, will draft a release for it today, thanks

**Comment by ebraminio** [comment]
Done
