### ISSUE TITLE
Hangul "가속도" rendering issue in LibreOffice

### ISSUE THREAD

**Issue by pnemade** [harfbuzz/harfbuzz#2400]
Hi,

We got downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1833858 where all the information is available. Can upstream please confirm if the reported bug is rendering issue from harfbuzz or font file DroidSansFallbackFull.ttf ?

Environment: Fedora 32 with harfbuzz-2.6.4 and google-droid-fonts packages

**Comment by khaledhosny** [comment]
Broken font, it provides Hangul Jamo but almost not precomposed Hangul syllables, which lead to the rendering being seen.

**Comment by nim-nim** [comment]
So Droid is supporting Hangul in decomposed form only. I’m sure you know as well as me that the Unicode consortium is against precomposed codepoints, and considers them legacy leftovers.

So, is Harbuzz set on not supporting shaping the canonical Unicode.org form of Hangul?

Because if that is the case the decomposed Hangul codepoints probably need some filtering at the fontconfig level. At least to avoid marking a font file like Droid that only includes decomposed Hangul as suitable for Korean locales.

**Comment by khaledhosny** [comment]
The font neither have pre-composed glyphs nor any [Hangul OpenType features](https://docs.microsoft.com/en-us/typography/script-development/hangul) (or any features for that matter, apart from an erroneous `vert` feature), so there is nothing for HarfBuzz to shape with. It is clear that the font is not usable for Hangul.

**Comment by behdad** [comment]
Yeah I think DroidSansFallback was just that: fallback font to show individual characters.

**Comment by tagoh** [comment]
Hmm, if so, should does harfbuzz make sure if a font has otlayout:hang in capability or not?

**Comment by tagoh** [comment]
or try to check it in a different way?

**Comment by jfkthame** [comment]
The issue here seems to be specific to that version of DroidSansFallback; I've got other copies around (not sure where they come from, probably various Android devices) that don't exhibit the same problem. It's also specific to applications that use a harfbuzz-shaping-based font selection algorithm, which believes that the Hangul syllable codepoints are supported because the font has characters for their decomposed components. In an application that just looks directly at the font's character coverage, this font will not be selected for the precomposed syllables and so the issue doesn't arise.

**Comment by nim-nim** [comment]
Fedora is using upstream’s latest DroidSansFallbackFull.ttf file.

If you want to see the horrible hack we use to extract it from the 2 GiB of upstream git repo, read
https://src.fedoraproject.org/rpms/google-droid-fonts/blob/master/f/getdroid.sh

But, anyway, there is the font file itself, and the generic problem it exhibits. It would be good if our text stack was resilient WRT such font files, since we can not control the font files users install on their systems

**Comment by nim-nim** [comment]
Just for fun, here is the latest upstream commit to this file
https://github.com/aosp-mirror/platform_frameworks_base/commit/2d8961d99f3aa559dbd4b78b716ab36c456b43e1#diff-1af15229479eecd4ef75845dc9f9cbab

**Comment by behdad** [comment]
> Hmm, if so, should does harfbuzz make sure if a font has otlayout:hang in capability or not?

No.

**Comment by roozbehp** [comment]
DroidSansFallback had been outdated and unmaintained for years now. Please stop using it. Switch to Noto.

**Comment by tagoh** [comment]
Hmm, okay. just out of curiosity, can I ask you the reason why not? I think such broken fonts not satisfying requirements to get things work should be excluded from applications though, I'm pondering how/where would be implemented.

This may be off topic for harfbuzz if it is fontconfig matter but just want to hear some comments on the idea.

I could add some code points for precomposed glyphs in ko.orth on fontconfig though, that may be wrong direction to fix this since it works just fine if a font supports hang script tag right?

"lang" property in fontconfig cache is determined from the sort of glyph coverage though, we have "charset" property representing same in the broad sense. so if this is fontconfig matter, I may want to drop ko from lang if neither of precomposed glyphs and hang script tag is available?

Please let me know if there are any better idea.

**Comment by nim-nim** [comment]
@roozbehp Of course we also ship Noto but Noto is a giant that presents its own challenges, that’s why some users (and apps like ghostscript) prefer Droid as lighter fallback font

**Comment by jfkthame** [comment]
> I could add some code points for precomposed glyphs in ko.orth on fontconfig though

I think this would be reasonable. If a font does not support the precomposed Hangul syllables, which are by far the most common way for Korean text to be encoded, it's unlikely the font was really designed/intended for Korean use.

**Comment by behdad** [comment]
> I think such broken fonts not satisfying requirements to get things work should be excluded from applications though, I'm pondering how/where would be implemented.

Yes, by not installing them.  Stop trying to detect what's broken.  Not our job (fontconfig, harfbuzz) to detect and remove broken fonts.

**Comment by behdad** [comment]
> Please let me know if there are any better idea.

You are still trying to detect a broken font as such.  Stop trying is my recommendation.

**Comment by lukehutch** [comment]
> If you want to see the horrible hack we use to extract it from the 2 GiB of upstream git repo, read
> https://src.fedoraproject.org/rpms/google-droid-fonts/blob/master/f/getdroid.sh

Sorry for the Fedora-specific comment, but @nim-nim, it sounds like you are a Fedora developer? Can you please consider removing Droid Sans Fallback from Fedora? It is picked up by default by Chrome as a fallback sans serif font if it is installed, and the fallback frequently breaks Hangeul display on the Web.

**Comment by lukehutch** [comment]
I added this comment to the Fedora bug, but I'll copy it here for consideration, since it may involve HarfBuzz (I don't know where the responsibilities for font fallback selection and shaping lie these days, after all the Pango/FontConfig/HarfBuzz changes over the years...):

Droid Sans Fallback is often selected as the sans fallback font by Chrome on Fedora, and since the droid-sans-fonts package is default on Fedora (or at least a dependency of many other packages), this font frequently breaks Web browsing in Korean on Fedora -- so it's a pretty visible bug.

Even within a single sentence, some words (words starting with 가) fall back to Droid Sans Fallback, and some fall back to Noto Sans CJK. See a depiction of this pattern here:

https://github.com/harfbuzz/harfbuzz/issues/3003

The reason for this is probably that 가 is the pronunciation of the first jamo in the Korean alphabet, so it is used when spelling out bullet points etc. (equivalent to A, B, C, ...), and I'm guessing that Droid Sans Fallback contains the phonetic spelling of each jamo such as 가. So the fallback decision is made based on the first character in each word (at least in Google Docs, which probably calls the font measuring API for each word in a sentence, triggering a fallback decision for each word).

This indicates that the fallback logic can be improved. Currently the fallback determination seems to be being made based on the first Unicode codepoint in a span of text submitted for shaping. Is that a correct assumption?

**Comment by behdad** [comment]
> Hmm, okay. just out of curiosity, can I ask you the reason why not?

In HarfBuzz we *do* go out of our way to fix rendering with broken fonts.. *if* that can be done. With this font, it can't be fixed since the font just doesn't have shapes for the proper rendering.

> I think such broken fonts not satisfying requirements to get things work should be excluded from applications though,

We agree on that part.

> I'm pondering how/where would be implemented.

On the distribution level.

Detecting broken fonts, be it in harfbuzz or fontconfig, is inherently inexact science. What about true "fallback" fonts that just want to display the individual jamo? Any heuristic that also would block that would be wrong. Plus, there's no reason a valid font has to use the `hang` script tag instead of `DFLT`.

So, if you do choose to detect and blacklist that font, you should do it on the particular font's signature (name, hash, etc), instead of characteristic (no precomposed, no `hang` script, etc).

But if you are going to do that, why bake it into fontconfig, instead of have Fedora blacklist it in their fontconfig config since they know they are shipping broken font? As @jfkthame said, there seems to be other versions of this font that might not have broken Hangul.

The fontconfig config shipped in Fedora by the DroidSansFallback package can strip it form the Hangul language. I believe that's doable with fontconfig language.

> This may be off topic for harfbuzz if it is fontconfig matter but just want to hear some comments on the idea.
> 
> I could add some code points for precomposed glyphs in ko.orth on fontconfig though,

That sounds the right approach to me, so I agree with @jfkthame on that. Since most systems choose font based on `cmap` coverage (Chrome / LibreOffice being the exception), any legit Korean font will still support precomposed jamo.

> that may be wrong direction to fix this since it works just fine if a font supports hang script tag right?

Only in Chrome / LibreOffice etc. Not in traditional font-selection implementations.

> "lang" property in fontconfig cache is determined from the sort of glyph coverage though, we have "charset" property representing same in the broad sense. so if this is fontconfig matter, I may want to drop ko from lang if neither of precomposed glyphs and hang script tag is available?

I would not check for `hang` script. It's a misconception that layout scripts are required for correct rendering.

> This indicates that the fallback logic can be improved. Currently the fallback determination seems to be being made based on the first Unicode codepoint in a span of text submitted for shaping. Is that a correct assumption?

Not particularly. To put it simply though: it picks the first font that supports those characters, in the font list reported by fontconfig. Hence my suggestions above.

**Comment by lukehutch** [comment]
> Detecting broken fonts, be it in harfbuzz or fontconfig, is inherently inexact science. What about true "fallback" fonts that just want to display the individual jamo? Any heuristic that also would block that would be wrong.

Well it's definitely wrong to use a jamo-only font as the default Korean fallback font (or a jamo-only font that also happens to include the jamo pronunciation syllables 가, 나, 다, 라, 마, 바, 사, 아, 자, 차, 카, 타, 파, 하, but no other fully-composed characters, like Roboto Sans Fallback), if there is another font installed (like Noto Sans) that can render fully-composed hangeul characters *in addition to* isolated jamo. So even if Harfbuzz can't fix broken fonts, a smarter font fallback algorithm needs to be used to display Korean well.

Which library may be able to fix the broken behavior for this, in the case of Chrome and LibreOffice, given that they don't use `cmap` coverage?

**Comment by behdad** [comment]
> Which library may be able to fix the broken behavior for this, in the case of Chrome and LibreOffice

HB doesn't know anything about font fallback. The fix will involve Fontconfig. But I don't think fontconfig itself should change. The Droid Sans Fallback in Fedora should ship configuration that instruct fontconfig to know that this font is not adequate for rendering Hangul text.

**Comment by behdad** [comment]
Well, or, as Akira suggested, adding some precomposed jamo to ko.orth in fontconfig would also fix it.

You don't need to chase the bug anymore. All relevant parties are on this thread already.

**Comment by tagoh** [comment]
To record my thought, I totally agree with Behdad on it. no need to make any changes on fontconfig nor harfbuzz for this.
This is off-topic here but I'm not a package owner of google-droid-fonts in Fedora though, I could make a Pull Request for that there. let's see.

**Comment by tagoh** [comment]
Hm, DroidSansFallbackFull.ttf which is shipped in the supported versions of Fedora so far, doesn't have ko lang coverage. I think this issue should be gone now?
You may want to make sure if you have the latest version of google-droid-sans-fonts installed or try to find out a local copy of DroidSansFallback.ttf on your fonts dirs perhaps?

**Comment by lukehutch** [comment]
@tagoh I tested this -- I installed the latest package in Fedora Rawhide (google-droid-sans-fonts-20200215-9.fc34.noarch.rpm), and indeed something has changed. Now in LibreOffice all text *except* the 가 character displays as pure jamo.

![image](https://user-images.githubusercontent.com/811305/121059470-bcaa0d80-c77e-11eb-8869-8bd02f2e18c7.png)

However the Chrome behavior is unchanged: only words that start with 가 display in jamo.

![image](https://user-images.githubusercontent.com/811305/121059611-e5320780-c77e-11eb-9daf-e96c71c1be9b.png)

Also looking back it my earlier comment, my theory that it was the phonetic pronunciation of jamo was incorrect -- it in actually only the 가 syllable that displays this way in Chrome (or that triggers the fallback) -- the other syllables display as individual jamo.

![image](https://user-images.githubusercontent.com/811305/121059872-3215de00-c77f-11eb-8651-255483b959ec.png)

**Comment by invisibleroads** [comment]
As a workaround, you can disable google-droid-sans-fonts altogether.

Adding the following configuration to `~/.config/fontconfig/fonts.conf` fixed the issue in Fedora 42:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <rejectfont>
    <glob>/usr/share/fonts/google-droid-sans-fonts/*</glob>
  </rejectfont>
</fontconfig>
```

Thanks to https://802.11ac.net/2022/06/10/fedora-korean-font/ for the tip.
