### ISSUE TITLE
hb_font_funcs_t::glyph_contour_point is not implemented for --font-funcs ot ?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2454]
If I've tested it correctly, `hb_font_funcs_t::glyph_contour_point` with `--font-funcs ot` always returns `0 0`. When tested under debugger, it simply jumps to `hb_font_get_glyph_contour_point_nil` and that's it.

It's mainly used by `hb_font_t::get_glyph_contour_point_for_origin`, which is rarely (if never) used, so it may be overlooked. Or is it intentional?

**Comment by ebraminio** [comment]
Correct, it isn't implemented.

**Comment by ebraminio** [comment]
#2456

**Comment by behdad** [comment]
So my main opposition for this was that this callback is used for adjusting positions in a setup that has hinting. Since hb-ot doesn't do hinting, it's moot to implement this. Also, since most our users are advised to set ppem to 0, this won't be called from GPOS and as such, will be just unused code.

Note that there's no other use to this callback for the user. The callback is not useful for getting the glyph outline whatsoever... And point numbers are technically undefined for CFF so any font relying on that is noncompliant. If this *was* a feature we wanted to push forward moving forward I would be supportive of doing things beyond what spec requires. But since like hinting this is something we are trying to get rid of, I'm not very enthused.

That said, after writing this other issue:

  https://github.com/harfbuzz/harfbuzz/issues/2512

I think I'm /maybe/ supportive of doing this for glyf/gvar but not cff.

Another problem, obviously, is performance. Getting lig-carets for a ligature might load a full glyph outline with its variations multiple times. That's horrible. If ppem is not zero, any mark attachment during shaping can cause a full glyph outline load with its variations as well. Those are issues I have with this.

For those very reasons GDEF also has the `AttachList` table, which lists the points for each glyph that are used in such a way, such that a system like Windows can load the glyph once and cache the positions of all needed points once.  Unless you are also proposing such a cache, I'm still uncomfortable...

Again, so much work for so little. But might be doable.  Here's how:
- Create a cache object for this that can be allocated on the stack and passed down as needed.
- Use a fresh cache in `hb_ot_layout_get_ligature_carets`, such that the glyph outline is loaded just once.
- Use a fresh cache is `hb_ot_apply_context_t`, such that per `hb_shape` call each glyph is loaded at most once.

I actually like that.

The cache can be simply `hb_hashmap_t<uint16_t, hb_hashmap_t<uint16_t, hb_pair_t<uint16_t, uint16_t>>>`.

**Comment by behdad** [comment]
> always returns `0 0`.

You mean it always returns false. That's very different. :)  This was intentional, yes. But read my other comment please. Thanks!

**Comment by RazrFalcon** [comment]
Actually, I've hit it when porting kerx:

https://github.com/harfbuzz/harfbuzz/blob/26111a11ad1a648f8075b5289c05c48126cc2d3f/src/hb-aat-layout-kerx-table.hh#L520

And since Apple fonts doesn't use CFF, it's still kinda valid. Obviously, it's up to you to decide. 
On the other hand, there are no fonts that use action type 0, afaik.

I was simply surprised that this isn't implemented and thought maybe I've messed something up during porting.

**Comment by RazrFalcon** [comment]
As for the possible fix, it doesn't really matter for me. I will port any solution you've decide on.

**Comment by behdad** [comment]
Yep. Thanks. I think we should proceed with what I suggested and then disable it in `HB_MINI`.

**Comment by behdad** [comment]
I'm leaning towards marking this wontfix.
