### ISSUE TITLE
[util] Option to load font using freetype

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#248]
That would make woff work.  Right now, it looks like it works, but GSUB/GPOS fail because our sfnt-reader fails to load tables.

**Comment by KrasnayaPloshchad** [comment]
I think both HarfBuzz and FreeType should include an entry for this.

**Comment by SuNK30** [comment]
Hi, Can i using harfbuzz lid for loading font (create a face and font)?
Note: I do not use freetype lib.
thanks.

**Comment by SuNK30** [comment]
I think hb_face_create and hb_ft_face_create function 
https://github.com/behdad/harfbuzz/blob/02bfd965af588640250c47f344ad3096c8a373e0/src/hb-face.cc#L161
https://github.com/behdad/harfbuzz/blob/382e4f880b881cda5f8e5a404be562a9997b0f58/src/hb-ft.cc#L519
the same
hb_font_create and hb_ft_font_create function
https://github.com/behdad/harfbuzz/blob/382e4f880b881cda5f8e5a404be562a9997b0f58/src/hb-font.cc#L1121
https://github.com/behdad/harfbuzz/blob/382e4f880b881cda5f8e5a404be562a9997b0f58/src/hb-ft.cc#L601
the same
So there necessarily using freetype lib for loading font?
Thanks.

**Comment by behdad** [comment]
I also like supporting woff directly, but that will pull in gzip dependency.  Maybe that's not a problem?

**Comment by KrasnayaPloshchad** [comment]
> I also like supporting woff directly, but that will pull in gzip dependency.

That may need to allow to build with decompression library other than gzip.

**Comment by bungeman** [comment]
I recently ran across this while investigating why certain system installed fonts (registered by FontConfig) were not working in Chromium on Linux. It appears that someone changed a file extension from `.woff` to `.ttf` to evade initial screening. Then in Blink's [HarfBuzzFace::CreateFace()](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/shaping/harfbuzz_face.cc;l=367;drc=924ddf7fffcdc465838e48a40b08ed41bf480a5c) a first attempt is made to `hb_face_create` directly from the data (which is still woff) wrapped in an `hb_blob`. If that fails for any reason the code then tries to `hb_face_create_for_tables`. The issue here is that the first call (to `hb_face_create`) appears to work but then things fail later. If the initial call were to fail (or if one comments out the call to `hb_face_create`) then everything works out since the rest of the system does know how to get at the table data (in this case through FreeType, though it could be through other means).

It looks like this is because `OpenTypeFontFile::sanitize` returns `true` if the magic number of the data isn't one of the known font magic numbers. Either this should return `false` in this case (since no real sanitation has been done) or `hb_face_create` should also call `get_face_count` and reject fonts that have zero faces. More generally it would probably be a good idea to compare the result of `get_face_count` against the `index` passed to `hb_face_create` so that requesting non-existing `index` fails.

**Comment by bungeman** [comment]
Taking a closer look, the current API doesn't really provide a means for returning an error from `hb_font_create`, which seems to go way out of its way to never even return NULL. Perhaps it would be possible to add a `hb_face_format` or something like that which could return an `Unknown` value if the the data wasn't recognized. Even something like `hb_face_is_valid` or something like that would be helpful. At the moment the easiest work around from the outside is to call `hb_gace_get_glyph_count` and see if it comes back 0.

Other than this it's already more or less possible to 'load' a font using FreeType, since one can implement all the appropriate callbacks on the buffer. However, because of the behavior of `hb_font_create` it's difficult to know if one should try to do so, or try loading with `hb_font_create_with_tables` instead.

**Comment by behdad** [comment]
> The issue here is that the first call (to `hb_face_create`) appears to work but then things fail later.

Right. That's intentional in a way; such that font formats we do not understand still pass through.

We've been adding `_or_fail()` versions of some API, like: https://github.com/harfbuzz/harfbuzz/pull/3026
but I think in this case you're better off calling `hb_face_count()` on the blob.

**Comment by behdad** [comment]
> Right.. I think in this case you're better off calling `hb_face_count()` on the blob.

We should document this.

@bungeman would that, if documented, address your concern and use-case?

**Comment by behdad** [comment]
> That would make woff work. Right now, it looks like it works, but GSUB/GPOS fail because our sfnt-reader fails to load tables.

Maybe `util/` should do that internally as well!

**Comment by bungeman** [comment]
I ended up using `hb_gace_get_glyph_count() == 0` since it was checking the face and doing some minimal checking (that the `maxp` table exists, etc). It seems `hb_face_count()` should be ok as a pre-check to use instead. That's also useful since it returns how many faces HarfBuzz believes are in the data, so this can be checked against the requested index passed to `hb_face_create()`.

I think it would be great to document that one should call `hb_face_count()` before calling `hb_face_create()` and check that the index being requested actually exists first, since otherwise `hb_face_create()` will appear to succeed but produce an "invalid" hb_font.

**Comment by behdad** [comment]
Closing as I don't see this happening; if anything we have moved away from FreeType...
