### ISSUE TITLE
"Harfbuzz version too old" Erorr in Applications

### ISSUE THREAD

**Issue by GalGreenfield** [harfbuzz/harfbuzz#2574]
Hello, in some applications that I understand use Harfbuzz I get this error: 
> Harfbuzz version too old (1.2.7)

What version is it referring to - the one the application uses? The one installed on my machine?

**Comment by ebraminio** [comment]
> What version is it referring to - the one the application uses? The one installed on my machine?

Maybe either of them? Are you using Slackware 14.2 by any chance? 1.2.7 is definitely too old so guess you should forward this to people that have provided the software binaries for you, packagers or anyone that have embedded harfbuzz in their software as harfbuzz is easy to embed and even Chromium and Firefox don't use the one from the distro but use an embedded one.

**Comment by khaledhosny** [comment]
The messages comes from Pango. The issue happens when an application statically links to an old version of HarfBuzz but dynamically let nos to a version of Pango that was built against a newer version of HarfBuzz.

These are almost always Electron applications and it is an application bug, the fix is for the application to update Electron.
