### ISSUE TITLE
Reconsider deprecating CMake build as it is useful on Windows/VS

### ISSUE THREAD

**Issue by wangqr** [harfbuzz/harfbuzz#2586]
The main argument is that resolving dependencies on Windows is way easier in CMake than meson. Take ICU for example,
* In CMake,
  * Run CMake configure
  * See ICU disabled, toggle `HB_HAVE_ICU` (I don't expect I can remember the correct option name, but CMake has user interface so no need to remember it)
  * See error message complaining ICU not found
  * Set `ICU_INCLUDE_DIR` `ICU_LIBRARY` and rerun configure (If harfbuzz used CMake provided FindICU, then setting `ICU_ROOT` is enough. This is available since CMake 3.7. Maybe harfbuzz tries to keep backward compatibility with really old distros?)
* In meson,
  * Run meson setup
  * See ICU disabled, rerun meson setup with `--wipe -D icu=enabled` (I need to check meson_options.txt to find out the option name)
  * See error message complaining ICU not found
  * Open meson.build, search for ICU related `find_library`, manually edit that part and add `dirs`
  * Rerun meson setup with `--wipe -D icu=enabled`

Setting a path in CMake (CUI/GUI available) and let it keep it in CMakeCache.txt is just easier than editing meson.build and worrying about the changes being overwritten or cause merge conflict after `git pull`.

If you wonder why meson could not find package by itself, that's because meson uses pkg-config, which no one uses on Windows except in Cygwin or MSYS2/MinGW. See mesonbuild/meson#4029 .

---

Other advantage of CMake includes a much mature Visual Studio backend. Meson [officially says](https://mesonbuild.com/Using-with-Visual-Studio.html) VS backend is not recommended for serious work:
> At the time of writing the Ninja backend is more mature than the VS backend so you might want to use it for serious work.

For example you can simply toggle Release / Debug build within VS if the project is generated by CMake. But when using meson it has to be decided at setup time. You have to do `meson setup` in 2 different directories if you want both.

**Comment by ebraminio** [comment]
Guess we can keep parts of cmake port for a longer period of time but remove things not needed for embedders, and make cmake dependent to meson lists instead Makefile.source to make decision about autotools to not interfere with cmake. So feel free to explain what has been your exact usecase (parts of harfbuzz you while in cmake) so we know what parts aren't needed, I think subset, util/, instrospection, and maybe install logic also is unrelated to most embedders anyway.

Would be nice also if you could check whether you aren't better to use one file `src/harbuzz.cc` directly in your project and what obstacles that would have to better study of cmake uses. Our cmake port uses `src/harfbuzz.cc` internally for a long time so most embedders also should be fine with it.

Not exactly related to what you asked here but about the previous discussion, vcpkg already has projects using meson instead cmake, https://github.com/microsoft/vcpkg/blob/8bfdf64a925d75433e721a687930c4d2d5f5620f/ports/fribidi/portfile.cmake can you check feasibility of using meson port there, or actually, I just remembered I was working on one but faced with some issue :) let me upload it, https://github.com/microsoft/vcpkg/commit/681a100df21ad6bcf909894860b8c40ffcc6f6cc the problem is `vcpkg_check_features` should give enabled/disabled instead on/off for meson and there are some issue on install parts as lack of `vcpkg_fixup_cmake_targets` equivalent for meson, otherwise it is working locally at least as far as I can say.

**Comment by wangqr** [comment]
> [...] what has been your exact usecase [...] so we know what parts aren't needed,

I'm build harfbuzz.dll and harfbuzz-icu.dll using MSVC and use them in other project. So I need the include files, the .dll and the stub .lib.

> Would be nice also if you could check whether you aren't better to use one file src/harbuzz.cc directly

This is also doable. But in my opinion toggling features in CMake is easier in CMake than maintaining `.props` files in visual studio that has corresponding `HAVE_*` macro, include paths, and linking library.

> vcpkg already has projects using meson instead cmake

That's great! I am still testing vcpkg.cmake toolchain but it is good to know meson build will work on vcpkg.

**Comment by ebraminio** [comment]
> I'm build harfbuzz.dll and harfbuzz-icu.dll using MSVC and use them in other project. So I need the include files, the .dll and the stub .lib.

Just am curious, any specific reason you need hb-icu? We have a bulitin unicode providers nowadays and encourage use of it so nice to know any specific reason to not use that.

> This is also doable. But in my opinion toggling features in CMake is easier than maintaining .props files in visual studio that has corresponding HAVE_* macro, include paths, and linking library.

Of course it is but it has maintaining cost for us, that's why I am interested to help on your specific case to see what best can be done. Is your project opensource?

> That's great! I am still testing vcpkg.cmake toolchain but it is good to know meson build will work on vcpkg.

Exactly. So let's push for that.

**Comment by wangqr** [comment]
I just tried the harfbuzz[icu] 2.6.6 in vcpkg and it can be used in my use case. So I'm closing this issue for now.

> We have a bulitin unicode providers nowadays and encourage use of it.

Unfortunately it's an internal tool and it's not written by me. Thanks for the information and I'll see if we can drop that dependency.
