### ISSUE TITLE
no configure script since 2.7.0

### ISSUE THREAD

**Issue by dmilith** [harfbuzz/harfbuzz#2617]
In all previous versions autotools generated configure script was provided, now it's not?

**Comment by alerque** [comment]
The primary build system has switched to Meson. The transition started back in 2.6.5 as experimental, was stabilized over a few releases with both systems in parallel and is now the primary way to build. See all the release notes on the last few releases plus [this wiki page](https://github.com/harfbuzz/harfbuzz/wiki/Notes-on-migration-to-meson).

The Automake system is still available and *can* be used, but you need to use `autoreconf` yourself to generate the `configure` script from `configure.ac` and other sources. In a full GNU Automake style release a source package would be generated with this step done. Since that isn't being generated any more you need to do it yourself if you want an Automake only build.

In the mean time even if you use the still-possible Automake build as a stop-gap, please migrate your builds to Meson ;-)

**Comment by dmilith** [comment]
Ok, thanks for info!

**Comment by alerque** [comment]
Also see #2587.

**Comment by ebraminio** [comment]
@alerque, thanks for this well explanation of the situation :pray: and things have went smoothly AFAICT thanks to all people have helped so far.
