### ISSUE TITLE
Wrong kerning between two characters in a specific font

### ISSUE THREAD

**Issue by photopea** [harfbuzz/harfbuzz#2645]
In the font below, when you type "38", harfbuzz creates a different kerning between characters than e.g. Adobe Photoshop. Here you can see Harfbuzz at the top and Photoshop at the bottom.

![image (3)](https://user-images.githubusercontent.com/15955558/90422613-69fe4880-e0bb-11ea-98d5-84b1af1a8601.png)
[VeersNumeric.zip](https://github.com/harfbuzz/harfbuzz/files/5085696/VeersNumeric.zip)

**Comment by alerque** [comment]
Your testing of Harfbuzz is broken, because it seems to work fine. Here is a render using SILE, which uses Harfbuzz for shaping:

```
\begin{document}
\font[filename=VeersNumeric.otf,size=6em]
38
\end{document}
```

![image](https://user-images.githubusercontent.com/173595/90423733-a9319700-e0c5-11ea-85c5-527af36bdb14.png)

You can even see this in a terminal using the `hb-view` program:

```console
$ hb-view VeersNumeric.otf 38
```

![image](https://user-images.githubusercontent.com/173595/90423853-e138da00-e0c5-11ea-9625-a025faf380e4.png)

**Comment by khaledhosny** [comment]
The font uses old-style `kern` table (instead of GPOS pair pos lookups), since you use WASM-compiled HarfBuzz, do you have `HB_NO_OT_KERN` set? It disables support for `kern` table.

**Comment by photopea** [comment]
Oh, I am very sorry. The problem was really in my build of Harfbuzz. Thanks a lot for such quick response :)
