### ISSUE TITLE
Malformed text in Brahmic-script Indic languages due to u0905 u0945

### ISSUE THREAD

**Issue by shuanlo** [harfbuzz/harfbuzz#2651]
Probably due to the change introduced in https://github.com/harfbuzz/harfbuzz/commit/df32eaae42b505b00de4a8b5efce9ab948bed847
text that until recently rendered correctly ceased to do so. 
This is affecting users and content that use the Brahmic scripts.

For example, Maharashtra Times, one of the largest Marathi-language newspapers, is still using the word ""अॅपमुळे"", and it does not render correctly.
https://maharashtratimes.com/gadget-news/science-technology/why-chinese-apps-are-dangerous-know-how-to-cause-harm/articleshow/76441045.cms

We think it is important for users to be able to continue to read content that is, unfortunately, still using the non-unicode compliant characters. Perhaps by implementing some form of normalization within Harfbuzz.

**Comment by khaledhosny** [comment]
Uniscribe does not insert a dotted circle.

**Comment by khaledhosny** [comment]
Reverting df32eaa indeed removed the dotted circle, but this this was an intentional change to address #1019 then I assume Uniscribe/DirectWrite is the one at fault here. CC @PeterCon.

**Comment by PeterConstable** [comment]
The sequence 0905 0945 is not one of the ones listed in Table 12.1 of the Unicode spec. As the text element being represented by 0905 0945 is graphetically/structurally sound and reasonable, and given that there is no other available representation in Unicode, this sequence should be supported.

Btw, when making references to sources such as Maharashtra Times, it would be helpful to provide links to examples of attested usage.

If Uniscribe/DWrite is not supporting this sequence, then that is a bug in MS's Indic shaping engine. As I'm not working at MS at this time, I can't investigate or file bugs. But I can try to mention it to them. (I keep hoping MS will make their shaping library OSS so that such things would be easier to investigate/bug/fix.)

**Comment by dscorbett** [comment]
Actually, [Table 12-1](https://www.unicode.org/versions/Unicode12.0.0/ch13.pdf#page=7) of <em>The Unicode Standard</em> version 13.0 deprecates the sequence <U+0905, U+0945> in favor of U+0972 DEVANAGARI LETTER CANDRA A. It is meet and right to insert a dotted circle into the sequence.

**Comment by PeterConstable** [comment]
Ah! My bad: I was badly mis-reading Table 12.1 just now, and dscorbett is correct (thanks!). 

And I'm guessing based on this that MS's Indic engine does *not* have a bug.

**Comment by khaledhosny** [comment]
> Or is there an issue that MS's implementation _isn't_ inserting a dotted circle?

Yes, Uniscribe/DirectWrite do not insert the dotted circle, HarfBuzz and Core Text insert it.

**Comment by PeterConstable** [comment]
Tried copying  ""अॅपमुळे"" into some Windows 10 components (Notepad = Uniscribe; Start search = XAML/Write) and there is no dotted circle inserted. So that appears to be a bug.

I sent mail to some MS folk about this.

**Comment by AEApple** [comment]
It seems like poor user experience to not render <U+0905, U+0945> as the joined character since then all previously created content which was created with the deprecated sequence will appear broken to users.

**Comment by behdad** [comment]
@jfkthame what do you think?

**Comment by jfkthame** [comment]
I'm a bit conflicted about this; on the one hand, accepting `<U+0905, U+0945>` (etc) and rendering as the joined form is an obvious spoofing risk; but on the other hand, in early versions of Unicode it used to be the only way that text unit could be encoded -- U+0972 was added in Unicode 5.1, whereas U+0905 and U+0945 date back to Unicode 1.1 -- so it's entirely reasonable that there is such data in existence.

Unicode now says the sequence "should not be used", but it's not really fair to users to break the rendering of existing data. For the purpose of a shaping engine, I'm inclined to think that we should accept these sequences and render them in the "expected" form. This is actually what the Unicode Standard *assumes* will happen, I think, which is why it takes the trouble to spell out which encodings "should" and "should not" be used. If only one of the options resulted in the "correct" rendering, the question of which to use wouldn't arise.

Other processes, such as IDN resolution, may well want to apply stricter constraints so as to minimize the risk of spoofing by use of such "deprecated" spellings, but I don't think that's the shaping engine's (or font's) responsibility.

**Comment by behdad** [comment]
Okay, so which sequences should be allowed now? @dscorbett any idea?

**Comment by dscorbett** [comment]
Ideally, none of the sequences would be allowed that Unicode says should not be used. Maybe we can just allow specific wrong sequences that are very common. Other than <U+0905, U+0945> I don’t know whether there are any.

Right now, `HB_NO_OT_SHAPE_COMPLEX_VOWEL_CONSTRAINTS` controls whether this feature is enabled. There could be a new setting between enabled and disabled: mostly enabled with certain compatibility exceptions. That might be more complex than it’s worth.

**Comment by behdad** [comment]
> Right now, `HB_NO_OT_SHAPE_COMPLEX_VOWEL_CONSTRAINTS` controls whether this feature is enabled. There could be a new setting between enabled and disabled: mostly enabled with certain compatibility exceptions. That might be more complex than it’s worth.

Most of the compile config we have is to save binary size. I don't believe in giving the client app control over behavior since there's no good way for them to choose what to do with it. We should just decide what's best and make it the behavior.

**Comment by behdad** [comment]
Closing since we didn't get more reports about this or similar issues.
