### ISSUE TITLE
hb_font_make_immutable crashes on NULL

### ISSUE THREAD

**Issue by misos1** [harfbuzz/harfbuzz#2656]
Seems most functions can handle if NULL is passed as `hb_font_t` like `hb_font_reference` and `hb_font_create_sub_font`.

**Comment by behdad** [comment]
This is intentional.

> Seems most functions can handle if NULL is passed as `hb_font_t` like `hb_font_reference`

The `reference`, `destroy`, `[sg]et_user_data` are our "lifecycle API" and accept `NULL`. Most other API doesn't as one shouldn't be having a NULL by the time they call into other API. They should at worst have a pointer to the `empty` object as returned by our API upon failure.

> and `hb_font_create_sub_font`.

That one is different: a `NULL` there means "no parent".

**Comment by behdad** [comment]
Curious to hear how you hit this.

**Comment by misos1** [comment]
I was just curious whether is safe (not causing aborts) to return NULL instead of empty object.

**Comment by behdad** [comment]
> I was just curious whether is safe (not causing aborts) to return NULL instead of empty object.

I see. I reserved NULL for applications to use while they have not initialized an object yet.
