### ISSUE TITLE
[ci] Upload win32 build artifacts

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2663]
For tagged builds, we want to upload the win32 build artifacts to the releases page. Latest build lacks them because I don’t have a working MingW setup, but CI is building them already so we should make use of that.

**Comment by khaledhosny** [comment]
cc @alerque in case you are interested in helping with this.

**Comment by alerque** [comment]
I would ... and will ... but walking out the door for a few days of travel and probably won't be able to have a look until next week. You can assign this to me but if somebody else beats me too it that's fine too.

**Comment by behdad** [comment]
> I would ... and will ...

Thanks. Granted you permissions you would need.

**Comment by alerque** [comment]
I'm back and working on this.

I've manually renamed and uploaded the Win32 artifact as built by Circle CI [from the 2.7.2 release commit](https://circleci.com/gh/harfbuzz/harfbuzz/151329?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). I'm working on an automated release posting now.

While I'm doing Win32, is there any reason not to introduce the same functionality for the current source dist package being uploaded manually?

**Comment by khaledhosny** [comment]
> While I'm doing Win32, is there any reason not to introduce the same functionality for the current source dist package being uploaded manually?

That would be ideal.

**Comment by alerque** [comment]
Success—or closer to it. I have the Win32 build artifacts posting to tagged releases, at least on my forked copy of this repo.

To make it work for this repo we need an API secret. Actually we *can* use mine (and I already started setting it up that way for now) — but this is a little bit of security exposure. Theoretically anyone with commit access to this repo could modify the CI job to either exfiltrate my API key or just use it directly against my account. It only has access to some API calls on my public repos so no private stuff is at stake, but for example it could be used to modify releases for other public projects I have access too. Not something I expect committers to this project to do, but on principle that's not necessary exposure surface. The same would be true for pretty much any other individual I know of with access here.

If there is a Github user that *only* has access to this project under which we could setup a personal access token such that the `public_repo` scope would only apply to this project and not a host of others that would be ideal.

Yes I do realize that Circle CI already has a deploy key to the Harfbuzz organization, but as far as I know that can only be used for Git/SSH access, not API access to post a file to the release. If somebody knows a way to use that authentication for this action I'd be happy to adapt.

**Comment by alerque** [comment]
By the way one alternative would be to do the release build / artifact publication jobs in a separate workflow from the test build jobs. I could setup the same thing in GitHub Actions instead of Circle CI and side-step the whole authentication problem.

**Comment by behdad** [comment]
> > While I'm doing Win32, is there any reason not to introduce the same functionality for the current source dist package being uploaded manually?

Sorry for chiming in late. In the future with meson there won't be any need for separate artefacts.

Until then, I actually prefer that one of us have to upload the tarball. Otherwise there's no way to verify the authenticity of the tarball.

**Comment by alerque** [comment]
> In the future with meson there won't be any need for separate artefacts.

I realize that too, but until then this reduces the effort required to release and reduces the changes of mistakes. The work is already done to make it happen...

> Until then, I actually prefer that one of us have to upload the tarball. Otherwise there's no way to verify the authenticity of the tarball.

Authenticity or validity? On both counts I would actually argue the CI generated artifacts are *much* more trustworthy than hand built and uploaded artifacts. Because you aren't including signatures or even checksums for verification there is no way for an end user to know if a build you posted manually is a match with what has a verifiable history in the repository. Any of a large collection of people are currently able to swap out artifact files on any release with virtually zero paper trail. The GitHub UI does not expose who attached files, not does it notify anybody when there are changes.

At least with CI built assets and there is one recourse: you can download the artifact from Circle and the one from GitHub and confirm that it has not been tampered with.

I cannot think of any authenticity issue that is better rather than worse in the current scheme of things. For that to matter somebody would have to be signing something (GPG, Signify, Minisign, etc.). Even if we were to get that going, it is also possible to sign CI built packages. The CI can post them attached to draft releases, somebody can verify and sign, then mark as published.

**Comment by behdad** [comment]
> On the authenticity front, because you aren't including signatures or even checksums for verification there is no way for an end user to know if a build you posted manually is a match with what has a verifiable history in the repository. Any of a large collection of people are currently able to swap out artifact files on any release with virtually zero paper trail. The GitHub UI does not expose who attached files, not does it notify anybody when there are changes. At least with CI built assets and there is one recourse: you can download the artifact from Circle and the one from GitHub and confirm that it has not been tampered with. Anybody can audit and _see_ what code the CI runner is building, how it is being built, and how it is posted. On the other hand they have no idea what might of happened (or by whom even) if artifacts are posted manually.

Yeah that's a problem. Maybe we should post PGP signatures of releases as well. I was under the impression that GitHub makes it clear who uploaded a particular artefact.



> Even if we were to get that going, it is also possible to sign CI built packages. The CI can post them attached to draft releases, somebody can verify and sign, then mark as published.

Yes this would be idea. But if we are going to use meson and there be no artefact to upload to begin with, maybe is not worth it.

Anyway, I'm happy to accept your work as is and be able to make zero-effort releases moving forward. Thanks!

**Comment by alerque** [comment]
> Yeah that's a problem. Maybe we should post PGP signatures of releases as well. I was under the impression that GitHub makes it clear who uploaded a particular artefact.

I'm kind of surprised by the lack of paper trail there myself, but the only thing the UI shows is how initially posted the tag **or** who marked a pushed tag as a "Release". There is seemingly nothing more useful:

* There is no telling if the artifacts were uploaded by the person who marked the release.
* There is no telling if the release history has been edited by others than the person who tagged.
* There is no telling if the artifacts have been tampered with after initial posting, you can delete and repost them. Presumably (I haven't tested) the download count would reset, but that would be easy to fake
* Etc.

> Anyway, I'm happy to accept your work as is and be able to make zero-effort releases moving forward. Thanks!

If you really want zero effort releases then what we should actually do is remove the version number from the source altogether and make the build system generate source packages that include it based on the Git tag. Literally the only thing that would be required to cut a release is to tag it, which can even be done from the web. CI would take over, build source distributions, post them, even post release notes as a changelog. The downsides are you can only build from a git full clone or a source dist zip/tarball (not a `git archive` zip/tarball), and you can't have changelog notes in the source (because the source can't change at release time).

A slightly hybrid approach is to have a simple build target for cutting a release that does any necessary version bumping & changelog generation — which means releases have to be cut by somebody using their own machine, but they don't need to build any targets other than the one that does the version bumping / changelog stuff.
