### ISSUE TITLE
Incorrect shaping with frac feature turned on for some fonts

### ISSUE THREAD

**Issue by thomasp85** [harfbuzz/harfbuzz#2672]
I am unable to figure out if this is an error in the encoding of some fonts or if it is a bug in HarfBuzz. If it is the former I apologise for the noise.

I have (or a user has) become aware that turning on the fractions OT feature will for some fonts result in incorrect shaping of non-fraction number. One of the fonts where it happens is with Fira Sans. Below is a shaping done with Spectral with fractions turned on (top) and Fira Sans with fractions turned on (bottom).

![image](https://user-images.githubusercontent.com/1775316/92390477-34c5a300-f11b-11ea-87e9-f57dd79e32cd.png)

The behaviour can be reproduced outside of my own HarfBuzz pipeline (e.g. with XeLaTex) but not in some proprietary software such as Affinity Designer.

**Comment by khaledhosny** [comment]
`frac` feature should be enabled only for the fraction not globally. Some fonts try to make it work only for fractions even if enabled globally, but this is not guaranteed (it requires complex contextual substitutions).

Alternatively, if the input uses fraction slash (U+2044, e.g. 12⁄27) HarfBuzz will take care of applying `frac` (and `numr`/`dnom`) only on number(s), fraction slash, number(s) sequence, but you must **not** manually enable `frac` feature in this case.

**Comment by khaledhosny** [comment]
AFAIK, no OpenType implementation implements it this way (may be except Affinity Designer), and for good reasons.  Suppose the font supports also alphabetic characters and other symbols in fractions (e.g.  1+a/2), one wont be able to make use of this support if the feature was always restricted to numbers by the layout engine. Since it is a typographic feature, it needs to applied selectively by the user (unless there is no ambiguity as in the case of using numbers with fraction slash).
