### ISSUE TITLE
Clarify whether buffer context must have same script/language

### ISSUE THREAD

**Issue by astiob** [harfbuzz/harfbuzz#2730]
https://harfbuzz.github.io/adding-text-to-the-buffer.html says:

> For longer text runs, such as full paragraphs, it might be tempting to only add smaller sub-segments to a buffer and shape them in piecemeal fashion. […] The safest approach is to add all of the text available, then use `item_offset` and `item_length` to indicate which characters you want shaped, so that HarfBuzz has access to any context.

How much does this apply when the text contains multiple scripts and languages? Is it right to split on a script boundary and pass each part as context to the other, or must each script part be placed in the shaping buffer in full isolation?

(This is a question, but it would be great to have an answer in the manual, rather than only on the issue tracker.)

**Comment by khaledhosny** [comment]
Ideally, the full paragraph text is passed to HarfBuzz each time with the specific run boubdry being shaped, regardless of the script/language/direction/font.

**Comment by khaledhosny** [comment]
I thonk the manual text is clear enough, but feel free to suggest improvements (pregerably as a PR).

**Comment by Eli-Zaretskii** [comment]
If passing the full paragraph is preferred, does that mean the direction, the script, and the language should *not* be set, but instead left to HarfBuzz's discretion?  What if HarfBuzz decides on one of these incorrectly?

**Comment by khaledhosny** [comment]
The [`hb_buffer_add_*()`](https://harfbuzz.github.io/harfbuzz-hb-buffer.html#hb-buffer-add-codepoints) functions take a text string and a length, this should ideally be a full paragraph of text, then item offset and length, this is the single script/language/direction/font run that is being shaped.

So instead of itemizing then splitting paragraph into items and passing only the text of that item to HarfBuzz, you itemize then store item offsets and lengths and pass to HarfBuzz the full text, then item offset and length one by one.

The first way still works, but it is a sub-optimal use of HarfBuzz API and you loss some functionality, like HarfBuzz detecting the proper Arabic joining behavior of the item boundary based on the context, so when say “ال**ع**ربية” is shaped (with the ayn set in bold or a fallback font), you don’t get a unjoined word (Chrome and Firefox will show the word above differently, possibly illustrating this very issue of HarfBuzz API use).

**Comment by Eli-Zaretskii** [comment]
I am probably missing something, because I don't see how that answers my question.  Perhaps if you could show some example code which does what you describe I will understand.  My question is specifically about using `hb_buffer_set_direction`, `hb_buffer_set_script` and `hb_buffer_set_language`, and how they should be used when the entire paragraph is sent to HarfBuzz.

And, btw, what is the definition of "paragraph" for this purpose?

**Comment by astiob** [comment]
Thanks, Khaled! I think that the manual text is clear _if you already know the answer,_ but a reader like me could be excused for wondering whether shaping might actually break if I pass text from other scripts as context, seeing as script is so important for shaping. Just a little note like “(even if the paragraph contains text in other scripts, directions and languages)” would be perfect. Perhaps I’ll make a PR.

@Eli-Zaretskii `hb_buffer_set_direction` etc. set the properties of each single-direction-and-script-and-language segment. This is true in any case. You split the whole text in segments and do the full set of HarfBuzz calls for each segment separately. But when you set up each segment’s buffer for HarfBuzz, you should do _not_ this:

```c
hb_buffer_set_direction(buffer, segment_direction);
hb_buffer_set_script(buffer, segment_script);
hb_buffer_set_language(buffer, segment_language);
hb_buffer_add_utf8(buffer, full_text + segment_start, segment_length, 0, segment_length);
```

but rather this:

```c
hb_buffer_set_direction(buffer, segment_direction);
hb_buffer_set_script(buffer, segment_script);
hb_buffer_set_language(buffer, segment_language);
hb_buffer_add_utf8(buffer, full_text, full_text_length, segment_start, segment_length);
```

This will tell HarfBuzz to _shape_ only that particular segment, but at the same time allow it to know what other text exists outside of that segment, so it can do better shaping at the segment boundaries.

**Comment by Eli-Zaretskii** [comment]
Thanks.

I thought `hb_buffer_set_*` functions set the property for the whole buffer, but you seem to say it only affects the segment that *will* be added by the following `hb_buffer_add_*` call?  Also, I will next call `hb_shape_full`, but there doesn't seem to be a way of telling which part of the buffer should be shaped.

So I still think I'm missing something important here...

**Comment by astiob** [comment]
The buffer proper only contains the part that was passed as the segment, that is, in the last two arguments to `hb_buffer_add_*`. That is what the buffer properties are set for, and that is what the subsequent `hb_shape*` will shape.

The full text is not part of the “buffer”, but HarfBuzz makes a special note of several characters before and after the buffer (if you supply them to `hb_buffer_add_*`) and remembers them as context. As far as I can tell, this context memory is not exposed in the API, and calling `hb_buffer_add_*` is the only way to set it.

**Comment by Eli-Zaretskii** [comment]
So that means one cannot use `hb_buffer_add` to add one character at a time, but instead one needs to use `hb_buffer_add_codepoints`, after collecting the entire paragraph in an array of codepoints.  That's quite a requirement...

Thanks, I think this is clear now.  (But I still would like to know what is a "paragraph" in this context.)

**Comment by astiob** [comment]
To be clear, if you make multiple calls to `hb_buffer_add`, I believe it remembers the characters that _precede the first_ part and the characters that _follow the last_ part. But of course, if you’re adding them one character at a time because you don’t have an array of characters in the first place, then you won’t get any context. So in that sense, yes, you should collect the whole paragraph in an array and then call `hb_buffer_add` on that array.

A paragraph, as I understand it, is a somewhat abstract concept denoting all text until a high-level break point where shaping must make a full stop. In plain text, it would be delimited by explicit line breaks. In HTML/CSS, also by block boundaries (but continue across inline elements). It could be called a “line”, but if the application does line _wrapping,_ it wants to shape the whole paragraph together and _then_ wrap the lines. Besides shaping, paragraphs are also relevant for the bidirectional algorithm, which should be applied to each paragraph in isolation.

**Comment by astiob** [comment]
@khaledhosny Do explicit line breaks in text actually necessitate shaping paragraph breaks, or does having a U+00A0 in the text effectively achieve the same?

**Comment by khaledhosny** [comment]
I’m not sure what is the relation between U+00A0 and paragraph breaks. But HarfBuzz does not have any special paragraph-limiting rules, any character in the text will be shaped (Default-Ignorable characters will be replaced by space glyph eventually, but any font rules involving them will be applied).

**Comment by astiob** [comment]
Err. U+000A, of course. The line break. I knew I should’ve just called it by the name. 🤦‍♂️

**Comment by khaledhosny** [comment]
HarfBuzz will shape U+000A like any other character, so you are most likely to end with glyph index 0 (`.notdef`).
