### ISSUE TITLE
How to fix `hb_ot_tags_from_script` deprecation warning?

### ISSUE THREAD

**Issue by lemzwerg** [harfbuzz/harfbuzz#2737]
Please have a look at

  https://savannah.nongnu.org/bugs/index.php?59288

The central warning message is
```
.../src/autofit/afshaper.c: In function ‘af_shaper_get_coverage’:
.../src/autofit/afshaper.c:135:5: warning: ‘hb_ot_tags_from_script’ is deprecated: \
  Use 'hb_ot_tags_from_script_and_language' instead [-Wdeprecated-declarations]
  135 |     hb_ot_tags_from_script( script,
      |     ^~~~~~~~~~~~~~~~~~~~~~
```
I've already tried to fix this, but unfortunately it is not trivial, so I ask for guidance how to do that.

**Comment by dscorbett** [comment]
What have you tried?

`hb_ot_tags_from_script` is a simple wrapper around `hb_ot_tags_from_script_and_language`. It should be straightforward to copy its logic into your program.
https://github.com/harfbuzz/harfbuzz/blob/5091ea7e247b118009c719076650a93b3e2dde6d/src/hb-ot-tag.cc#L124-L128

A better fix is to check the `script_count` output parameter for how many scripts were returned, instead of forcing it to be always 2. Some Indic scripts like Devanagari have three possible script tags.
