### ISSUE TITLE
Harfbuzz fails to apply multiple features having feature value > 1

### ISSUE THREAD

**Issue by be5invis** [harfbuzz/harfbuzz#2741]
It looks like when having many feature with feature value > 1 (typically used in alternate GSUB substitution, used by `salt`, `aalt`, `ss##` and `cv##` features), Harfbuzz failed to apply some of them. It looks like it is similar to #2317 but much easier to reproduce. Such failure is not reproducible in other shaping systems like Apple's CT or DWrite. From the observation I got, Harfbuzz seems hit some internal length limit of feature/value combinations, and drops features added later.

Test font (TTF and TTX; modified from [Adobe's FDArray test font](https://github.com/adobe-fonts/fdarray-test), which has nice double-digit-hexadecimal glyphs): [hb-gsub-alternate-bug.zip](https://github.com/harfbuzz/harfbuzz/files/5515903/hb-gsub-alternate-bug.zip).

The font encodes character `0`, `1`, `2`, ..., `9`, `A`, ..., `F` to GID 1, 17, 33, ..., 241, and have feature `cv01`, `cv02`, ..., `cv16` to control the variant of each character. Each `cv` feature has one GSUB alternate lookup, substituting the default GID (denoted as *n*) substituted into *n* + 1, *n* + 2, ..., *n* + 15. Therefore, applying `cv02 = 2` for character `0` will get GID 3.

Here are results from `hb-shape`:

```
$ hb-shape hb-bug.ttf '0123456789ABCDEF'
[gid1=0+1000|gid17=1+1000|gid33=2+1000|gid49=3+1000|gid65=4+1000|gid81=5+1000|gid97=6+1000|gid113=7+1000|gid129=8+1000|gid145=9+1000|gid161=10+1000|gid177=11+1000|gid193=12+1000|gid209=13+1000|gid225=14+1000|gid241=15+1000]

$ hb-shape --features "cv01=1,cv02=1,cv03=1,cv04=1,cv05=1,cv06=1,cv07=1,cv08=1,cv09=1,cv10=1,cv11=1,cv12=1,cv13=1,cv14=1,cv15=1,cv16=1" hb-bug.ttf '0123456789ABCDEF'
[gid2=0+1000|gid18=1+1000|gid34=2+1000|gid50=3+1000|gid66=4+1000|gid82=5+1000|gid98=6+1000|gid114=7+1000|gid130=8+1000|gid146=9+1000|gid162=10+1000|gid178=11+1000|gid194=12+1000|gid210=13+1000|gid226=14+1000|gid242=15+1000]

$ hb-shape --features "cv01=2,cv02=2,cv03=2,cv04=2,cv05=2,cv06=2,cv07=2,cv08=2,cv09=2,cv10=2,cv11=2,cv12=2,cv13=2,cv14=2,cv15=2,cv16=2" hb-bug.ttf '0123456789ABCDEF'
[gid3=0+1000|gid19=1+1000|gid35=2+1000|gid51=3+1000|gid67=4+1000|gid83=5+1000|gid99=6+1000|gid115=7+1000|gid131=8+1000|gid147=9+1000|gid163=10+1000|gid179=11+1000|gid195=12+1000|gid211=13+1000|gid225=14+1000|gid241=15+1000]

$ hb-shape --features "cv01=15,cv02=15,cv03=15,cv04=15,cv05=15,cv06=15,cv07=15,cv08=15,cv09=15,cv10=15,cv11=15,cv12=15,cv13=15,cv14=15,cv15=15,cv16=15" hb-bug.ttf '0123456789ABCDEF'
[gid16=0+1000|gid32=1+1000|gid48=2+1000|gid64=3+1000|gid80=4+1000|gid96=5+1000|gid112=6+1000|gid113=7+1000|gid129=8+1000|gid145=9+1000|gid161=10+1000|gid177=11+1000|gid193=12+1000|gid209=13+1000|gid225=14+1000|gid241=15+1000]

$ hb-shape --features "cv08=15,cv09=15,cv10=15,cv11=15,cv12=15,cv13=15,cv14=15,cv15=15,cv16=15" hb-bug.ttf '0123456789ABCDEF'
[gid1=0+1000|gid17=1+1000|gid33=2+1000|gid49=3+1000|gid65=4+1000|gid81=5+1000|gid97=6+1000|gid128=7+1000|gid144=8+1000|gid160=9+1000|gid176=10+1000|gid192=11+1000|gid208=12+1000|gid224=13+1000|gid225=14+1000|gid241=15+1000]
```

The results are:
 * If you apply 16 `cv##` with value 1, all features worked well.
 * If you apply 16 `cv##` with value 2, `cv15` and `cv16` failed to apply.
 * If you apply 16 `cv##` with value 15, then features starting `cv08` failed to apply.
 * If you apply `cv08` ... `cv16` with value 15, then only `cv08` ... `cv14` are applied. `cv15` and `cv16` failed to apply.

**Comment by khaledhosny** [comment]
I can reproduce. Using `--shaper=coretext` give the expected glyph IDs, ruling out a bug in the command line tools.

**Comment by AlsoScratch** [comment]
> * If you apply `cv08` ... `cv16` with value 15, then only `cv08` ... `cv14` are applied. `cv15` and **`cv15`** failed to apply.

@be5invis Did you mean `cv16`?

**Comment by jfkthame** [comment]
I assume what's happening is simply that it's running out of bits to allocate for the various features [in the loop here](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-map.cc#L210-L278), and so it starts dropping them.

**Comment by be5invis** [comment]
@AlsoScratch Oh yeah, typo :) Fixed in description

**Comment by behdad** [comment]
What Jonathan said.

**Comment by be5invis** [comment]
@jfkthame If you specify feature value to larger number like 255, the "bits" may ran out in 4 features. Since `hb_ot_map_t` is not in the document (did a search and not found in any "doc"-related files; correct me if I am wrong), and the bitmap fields are private, it should be fine to fix this and allow users to apply more features.

**Comment by jfkthame** [comment]
To fix this without breaking compatibility, we'd need to come up with a way to add more feature/value bits without altering the size (or "public" fields, at least) of `hb_glyph_info_t`, as this is part of the public interface.

Maybe we could do something involving a "feature-bits-overflowed" flag that would indicate we need to look at a separately-maintained auxiliary record where the real feature bits are stored; this would not be part of the array of glyph_infos that are exposed to the client.

**Comment by be5invis** [comment]
@jfkthame I saw there's already `hb_glyph_flags_t`, so the mask is already duplexed. Then, it should be safe to add a new flag and store more complicated feature masking information.

**Comment by behdad** [comment]
> Maybe we could do something involving a "feature-bits-overflowed" flag that would indicate we need to look at a separately-maintained auxiliary record where the real feature bits are stored; this would not be part of the array of glyph_infos that are exposed to the client.

Yep.

**Comment by behdad** [comment]
In general, for Graphite integration as well, we need to sometimes keep an extra auxiliary array. Same can be used for this purpose as well.

**Comment by behdad** [comment]
> Maybe we could do something involving a "feature-bits-overflowed" flag that would indicate we need to look at a separately-maintained auxiliary record where the real feature bits are stored; this would not be part of the array of glyph_infos that are exposed to the client.

I thought more about this. Given that the bit overflow mostly / only happens with user-provided features, and those are all applied in one stage at the end of GSUB (I'll discuss GPOS later below), it's fairly easy to reuse the mask bits between applying multiple lookups. That is, the code that sets up all masks right now:
```
hb_ot_shape_setup_masks (const hb_ot_shape_context_t *c)
{
  hb_ot_map_t *map = &c->plan->map;
  hb_buffer_t *buffer = c->buffer;

  hb_ot_shape_setup_masks_fraction (c);

  if (c->plan->shaper->setup_masks)
    c->plan->shaper->setup_masks (c->plan, buffer, c->font);

  for (unsigned int i = 0; i < c->num_user_features; i++)
  {
    const hb_feature_t *feature = &c->user_features[i];
    if (!(feature->start == HB_FEATURE_GLOBAL_START && feature->end == HB_FEATURE_GLOBAL_END)) {
      unsigned int shift;
      hb_mask_t mask = map->get_mask (feature->tag, &shift);
      buffer->set_masks (feature->value << shift, mask, feature->start, feature->end);
    }
  }
}
```
will have to be spread and interleaved with lookup applications.

I think the above is much easier / faster implementation than the alternative discussed, but needs some internal reshuffling of how the feature-map is compiled and used.

GPOS is inherently easier since the shapers don't use non-global GPOS features. But in our implementation we allow any shaper feature to be used either as GSUB or GPOS. So that causes a bit of problem. But nothing that cannot be taken care of... Why this is different concern from GSUB, is this: I want to split the above function such that the `c->plan->shaper->setup_masks` is always called as is now, and the `user_features` loop broken into rounds that are applied later. If the `c->plan->shaper->setup_masks` affects GPOS features, that would be interleaved after GSUB's `user_features` portion so their interaction and reused bits need to be negotiated...

**Comment by behdad** [comment]
Will get to this in a distant future...

**Comment by debianivanov** [comment]
Sorry for the inconvenience, is there any information about this enhancement to be implemented? Of course, I came across this thread because I am using Iosevka with several font-feature cv overwrites, but I hit the limit described here.

I have a workaround as @be5invis said to bake and generate the font with the features I want, but it will be far easier for the user to just describe the long list with features in fontconfig or css and use them directly.

Thank you very much and sorry for bringing up this thread. I hope this will be done in the near future. Greetings!
