### ISSUE TITLE
Can not disable kerning between CJK characters

### ISSUE THREAD

**Issue by kaiwk** [harfbuzz/harfbuzz#2745]
Hi, all,

I'm using 'HeiTi SC' font, even though I disabled kerning, it still gives:

<img width="183" alt="Screen Shot 2020-11-16 at 10 05 22 PM" src="https://user-images.githubusercontent.com/10190397/99261866-3a94de80-2858-11eb-9f54-42d9903f7624.png">

Note that I'm using [harfbuzz_rs](https://github.com/manuel-rhdt/harfbuzz_rs), and I have tested it with 'PT Serif' font with English words, it works fine.

I'm not sure if it's the problem of font, or should I specify letter spacing?

**Comment by alerque** [comment]
What is the UTF-8 string you are using? What would an unkerned pair look like in this case? Does `hb-shape`/`hb-view` exhibit the same problem?

**Comment by behdad** [comment]
The font doesn't do what *you* expect. Doesn't mean is a font bug even.

What did you expect?

Definitely not a HarfBuzz issue.

**Comment by jfkthame** [comment]
Right. The screenshot does show noticeably tighter spacing than I get if I render a sequence of 风风风风风 characters using Heiti SC here (e.g. in Firefox or Chrome), but I don't believe it's a harfbuzz (or font) problem; these browsers also shape the text using harfbuzz. This is almost certainly a bug in whatever client code is involved. Maybe it's mis-scaling glyph advances or something like that.

**Comment by kaiwk** [comment]
> Maybe it's mis-scaling glyph advances or something like that.

@jfkthame I set font_size to 16px (in web), and invoke `font.set_scale(font_size, font_size)`. I found an old post about `set_scale`: https://lists.freedesktop.org/archives/harfbuzz/2009-August/000359.html

> Now, what the hb_font_set_scale() call accepts right now is a 16.16 pair of 
scales mapping from font design space to device space ...... So, 
set_scale should be changed to accept em-to-user-space scale.  Not 
surprisingly, that's the same as the font size in the user-space.

So I think `set_scale(font_size, font_size)` is all right?

**Comment by jfkthame** [comment]
Sorry, I don't know enough about how you're using harfbuzz or handling fonts to tell where the problem is. But this isn't anything to do with kerning or other features within harfbuzz.

Here's an image that compares your screenshot (above) with the rendering I see in Firefox, which is using harfbuzz (below):

![image](https://user-images.githubusercontent.com/1706499/99375573-cbe96c80-28bb-11eb-9228-91961e1ccd0b.png)

It's clear there is a spacing difference. But the "tight" spacing you're seeing is not how harfbuzz shapes this font. Somewhere else in your code there's a scaling error, or a mismatch between the scale used for shaping and what's used when the glyphs are painted, or something like that.

**Comment by kaiwk** [comment]
Thank you @jfkthame , I think i found what's going wrong, from servo: 

https://github.com/servo/servo/blob/ae1055207475e0fdbefb25e43cdd519f4c0070c1/components/gfx/text/shaping/harfbuzz.rs#L165

I should pass `font_size` in `fixed-point` number to `set_scale` instead of plain `float` number. 

The doc seems https://harfbuzz.github.io/harfbuzz-hb-font.html#hb-font-set-scale failed to clarify that?
