### ISSUE TITLE
2.7.3 configure doesn't support --enable-introspection

### ISSUE THREAD

**Issue by rworkman** [harfbuzz/harfbuzz#2779]
and this breaks quite a few things depending on HarfBuzz-0.0.typelib remaining in place from 2.7.2 to 2.7.3

**Comment by rworkman** [comment]
Solution appears to be "use meson to build" and that's fine *if* there's some notification that it's necessary...

**Comment by alerque** [comment]
We started recommending distros packagers switch to Meson in the 2.7.0 announcement. We don't have an end date for completely deprecating autotools support yet, but it's been mentioned many times.

I don't think the `--enable-introspection` breakage was intentional though. I agree such a removal would have deserved an announcement. However I don't think there was a removal. Possibly a regression, but one can't exactly expect announcement of unintentional regressions.

Also I'm not convinced the only solution is to use Meson (although that is recommended). Discussion on #1202 suggests to me that you *can* still do this with autotools, but that you need to explicitly enable GObject support too. Given how many other issues mention this with various other iterations of confusion it does sound like at the very least documentation about this feature might be lacking.

**Comment by rworkman** [comment]
Seems like a good time to officially kill the autotools support :-)

**Comment by khaledhosny** [comment]
This is fixed in 2.7.4 release.
