### ISSUE TITLE
Emacs rendering of combining characters

### ISSUE THREAD

**Issue by sje30** [harfbuzz/harfbuzz#2790]
Hi,
Thank you for a great tool.  I'm using Emacs 27.1 from manjaro, which comes compiled with harfbuzz support.  I've found an issue with rendering of diacritials (notably x0305 for combining overline).

A description of the issue has been placed on the JuliaMono font issue page already,
https://github.com/cormullion/juliamono/issues/87

 where you can see I can't get proper rendering of "x bar" (the mean of x, in statistical terms) in the JuliaMono font in Emacs, but it does work in both xfce4-terminal and Chromium, which I believe also uses harfbuzz.  It also works for Monaco font in Emacs.  I therefore suspect Emacs.

I'm strugglling a bit to work out how best to debug this rendering, any hints appreciated! 

And please of course close this immediately if you think it noise!

Thanks very much

Stephen

**Comment by jfkthame** [comment]
My guess is that it's working in cases where the font has a precomposed glyph such that the (base letter, diacritic) pair gets mapped -- either by Unicode normalization within harfbuzz or by a GSUB ligature rule e.g. in the 'ccmp' feature -- to a single glyph; but fails when no precomposed glyph is present, so that the font is relying on mark positioning to place the diacritic correctly on the base letter.

In this case, there are still -- after shaping -- two glyphs to be rendered, and I suspect that somewhere in the emacs rendering code there's an insistence that each glyph needs to take up one character position in the display, so it effectively overrides the mark positioning that harfbuzz would have done.

Some fonts have a lot more precomposed accented forms than others, so which combinations fail would depend on the specific font being used.

(Note that the above is speculation; I have not tested or investigated it.)
