### ISSUE TITLE
Harfbuzz has started trying to render emoji variation selectors

### ISSUE THREAD

**Issue by kovidgoyal** [harfbuzz/harfbuzz#2804]
This is unexpected behavior. I first noticed it in 2.7.2 but I am not certain that is when it started. To demonstrate the issue:

```
hb-shape --show-extents --cluster-level=1 --shapers=ot /usr/share/fonts/noto/NotoColorEmoji.ttf -u 1f431,fe0f  
[gid541=0+2550<0,0,0,0>|gid3=1+0<0,0,0,0>]
```

Why is U+fe0f being rendered at all? It should only modify what glyph is chosen for the preceding codepoint.

**Comment by behdad** [comment]
We are not "rendering" them. HB inserts a space glyph with no advance width instead of those. Has always been doing that. (that's what gid3 is in most TrueType fonts).  If the font doesn't have a glyph for U+0020 SPACE, then HB just shows nothing for those.

The reason is for better mapping between glyphs and characters. But this should have no visible artifact. So, can you tell us how it is manifesting as a problem?

Also check `hb_buffer_set_invisible_glyph()`.

**Comment by kovidgoyal** [comment]
It's a problem because with Noto Color Emoji loading that glyph fails
with invalid size handle. I have worked around the problem in kitty
already, but there is still the issue of the failed load generating a
error print that I would like to get rid of.

**Comment by kovidgoyal** [comment]
In any case, I have worked around it completely by simply not loading the space glyph at all, since in kitty it is not required.

**Comment by behdad** [comment]
> It's a problem because with Noto Color Emoji loading that glyph fails
> with invalid size handle.

That points to possibly another problem in your code. If Noto Color Emoji claims to support U+0020, then is a problem if can't be loaded. And if it's a problem with the font, then your code should be changed to ignore such errors. That's how cairo etc work.

Anyway. My 0.02 CAD.
