### ISSUE TITLE
Apple Color Emoji font, in the SBIX table found glyph's graphicType = 'emjc' not 'png '

### ISSUE THREAD

**Issue by xiushaomin** [harfbuzz/harfbuzz#2808]
my iOS version：iOS 14.2.1

![image](https://user-images.githubusercontent.com/16091906/103970514-66bb4480-51a3-11eb-98da-c0bea74a9f5c.png)

**Comment by khaledhosny** [comment]
This is not documented in either [Apple](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html) nor in [Microsoft spec](https://docs.microsoft.com/en-us/typography/opentype/spec/sbix). Either way, HarfBuzz support PNG data only, as indicated by the name of the relevant API.

**Comment by twardoch** [comment]
The OpenType sbix table supports graphics in the JPEG, PNG and TIFF formats.

The TrueType sbix table also specifies PDF, but the mechanism also allows other formats. Since Apple recently switchedy much of its built-in bitmap processing to HEIC, I wouldn’t be surprised if the new Apple emoji font uses that — or some other format that is more effective in compression than PNG.

**Comment by twardoch** [comment]
Ah, OK — emjc is LZFSE-based: 

https://github.com/cc4966/emjc-decoder/blob/master/src/sbix_emjc_decode.c

https://github.com/lzfse/lzfse

**Comment by xiushaomin** [comment]
ok,  sbix create and reference 120mb of memory in iOS 14...is it just to get PNGHeader information?

**Comment by khaledhosny** [comment]
Please report such issue to Flutter, most memory allocations are not done by HarfBuzz itself.

**Comment by behdad** [comment]
Back to the original issue, I think we should add API to return the bitmap blob as well as whatever tag was attached to it.

**Comment by KrasnayaPloshchad** [comment]
This would allow any client application to call for itʼs own image decoders to render these glyphs, and make HarfBuzz freely to process the SBIX table.
