### ISSUE TITLE
How should HB handle "mutually exclusive" features?

### ISSUE THREAD

**Issue by kojiishi** [harfbuzz/harfbuzz#2830]
From a discussion with @drott, we thought we would like to hear experts' opinions.

In the OpenType spec, features such as [`palt`](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-palt) are defined as:
> Feature interaction: This feature is mutually exclusive with all other glyph-width features (e.g. 'fwid', 'halt', 'hwid', 'qwid' and 'twid'), which should be turned off when it’s applied. If 'palt' is activated, there is no requirement that 'kern' must also be activated. If 'kern' is activated, 'palt' must also be activated if it exists. See also 'vpal'.

When client apps enable these features together, fonts may not work correctly. Example, using [Noto Sans JP](https://fonts.google.com/specimen/Noto+Sans+JP):
```bash
$ N=NotoSansJP-Regular.otf
$ hb-shape --script=hani $N -u FF08
[gid15281=0+1000]
$ hb-shape --features="+halt" --script=hani $N -u FF08
[gid15281=0@-500,0+500]
$ hb-shape --features="+palt" --script=hani $N -u FF08
[gid15281=0@-464,0+500]
$ hb-shape --features="+halt,palt" --script=hani $N -u FF08
[gid15281=0@-964,0+0]
$ hb-shape --features="+palt,halt" --script=hani $N -u FF08
[gid15281=0@-964,0+0]
```
Both features shrink the advance by half-em (-500), so applying both features makes the advance to 0.

As you can see, this occurs when multiple GPOS features apply to the same glyph. The `halt` and `palt` features in Noto are one such example.

Should HB resolve such "mutually exclusive" features automatically?

Note, somehow the `halt` feature does not work in browsers (Blink/Gecko/WebKit, [test@jsbin here](https://jsbin.com/vicoqok/edit?html,output)), so I cannot reproduce this in browsers yet. Most likely some issue in Noto, I'll investigate separately.

Note 2: I reviewed some of the spec text, it looks like the definitions there are sometimes not very accurate at this moment. For example, "If 'kern' is activated, 'palt' must also be activated if it exists." does not look like what users would expect because they serve different purposes, and probably not compatible with existing apps. I'll make separate feedback to OpenType spec on these points. But I hope we can discuss general approach in HB separately from this issue.

**Comment by drott** [comment]
CC @jfkthame

**Comment by jfkthame** [comment]
I don't think harfbuzz should be responsible for this. The generic shaping engine should not need to know anything about the intended interactions or interdependencies between features, it should simply apply whatever the client requests and execute the resulting lookups as defined in the font.

If a client application is simply exposing arbitrary individual features (equivalent to CSS `font-feature-settings`), then the responsibility for what is applied (and whether the combination makes sense/works well) lies primarily with the user. If an application is applying various features automatically as a result of higher-level styling choices, or via custom UI for certain categories (such as spacing or casing options) then it'd be up to the application to determine which combinations are appropriate. The "feature interactions" guidance in the spec is aimed at the application (IMO), not at the shaping engine.

**Comment by behdad** [comment]
I agree with Jonathan.


> Both features shrink the advance by half-em (-500), so applying both features makes the advance to 0.

A well-crafted font can (and should) avoid this, by invoking the same lookup from both features. A GPOS lookup is never applied more than once, no matter how many features enable it.

**Comment by drott** [comment]
Thanks @behdad and @jfkthame for the quick feedback and consideration. I understand that you're both suggesting for the application level to decide on feature interaction.

Bear with me for limited understanding of the differences between `halt` and `chws`. One situation, in which I thought it would make sense for the shaper to decide is if a font has one or the other feature. Would it be a meaningful case if the application receives `halt` and `chws` ON from the content, sends down `halt` and `chws` as ON down to the shaper, and the shaper can just decide which one to apply based on what's in the font? In that case, no feature interaction decisions needs to be made at the application level, as the font only has one of the features. 

So, in determining feature interaction at the application level, do we need to probe for available font features as well? Or am I constructing an unrealistic case?

**Comment by jfkthame** [comment]
I think "feature interaction" can/should be handled at both the application level, if it maps higher-level abstractions or user interface options to specific OpenType features, and at the font level.

If I'm using an application that exposes "Numeral spacing: Default / Proportional / Tabular" in its user interface, it makes sense for these to be mutually exclusive UI options (e.g. radio buttons). So the application is aware of the interaction between these features and ensures that whenever one is activated, the other is not; and such an application will therefore avoid passing "conflicting" features to the shaper.

On the other hand, if the application simply accepts arbitrary feature controls from "content" and passes them to the shaper, like the CSS `font-feature-settings`, it should do so transparently; the author/user is allowed to request whatever combination of features they like, whether or not it "makes sense". If I write `font-feature-settings: "pnum" on, "tnum" on;`, I expect both of those features to be passed to the font. What it does with them, given that each is supposed to "override" the other, is up to the font designer.

The same would apply to your `halt` vs `chws` example. In general, the decision to apply these features would be the responsibility of the application, depending on whether it implements sophisticated CJK layout rules. ("If a layout engine supports advanced layout for CJK text as described in CLREQ, JLREQ or KLREQ, this feature should not be used. Otherwise, this feature should always be applied in horizontal layout of CJK text.")

An application wanting to use half-width forms where available (or maybe offering a UI option "Use half-width forms") might choose to first probe for `chws`, and if it is not supported, then apply `halt`. Blindly applying both features seems unwise; given that the spec says things like "This feature is mutually exclusive with all other glyph-width features [...], which should be turned off when this feature is applied", font designers may not take care to handle unexpected combinations nicely.

But if the user is given direct low-level control of individual OpenType features, and chooses to apply both `chws` and `halt`, that's on them. The results may be weird, depending what the font designer did.

As for harfbuzz, it should just apply whatever is requested by the client.

**Comment by kojiishi** [comment]
Thanks @behdad and @jfkthame from me too, this is really helpful. We'll discuss more based on your inputs.

@behdad:
> A well-crafted font can (and should) avoid this, by invoking the same lookup from both features. A GPOS lookup is never applied more than once, no matter how many features enable it.

Oh, that's a great idea I've never thought about. Thank you, that's a great suggestion to font developers.

In this specific case, both features shrink the width to half, but they have different `XPlacement` values. From its ttx, `halt` for `cid58999` has:
```xml
<Value XPlacement="-500" XAdvance="-500"/>
```
while `palt` has:
```xml
<Value index="23" XPlacement="-464" XAdvance="-500"/>
```
and therefor `hb-shape` outputs show different offsets:
```sh
$ hb-shape --features="+halt" --script=hani $N -u FF08
[gid15281=0@-500,0+500]
$ hb-shape --features="+palt" --script=hani $N -u FF08
[gid15281=0@-464,0+500]
```
Do I seem to understand your suggestion correctly that the method works when both features apply the same adjustments to the same glyph, but not otherwise?

I'm not meaning against suggestions from you and @jfkthame, rather I think they're all reasonable and appreciate. I just wanted to confirm whether font developers can always prevent such issue, or there are some cases where they can't.

**Comment by behdad** [comment]
> Do I seem to understand your suggestion correctly that the method works when both features apply the same adjustments to the same glyph, but not otherwise?

Each feature can invoke multiple lookups; some of which can be shared amongst different features to achieve what you describe. Eg. all `XAdvance` adjustments in one lookup referenced by two features, and all the `XPlacement` adjustments in separate lookup referenced by only one of those features.

**Comment by yisibl** [comment]
> A well-crafted font can (and should) avoid this, by invoking the same lookup from both features. A GPOS lookup is never applied more than once, no matter how many features enable it.

@behdad This is very interesting, I'm adding `chws / halt` features to our fonts, can you write an example in fea syntax?

**Comment by behdad** [comment]
I'm not well-versed in the fea syntax. Something like this I think:
```
lookup advances {
    # rules to be grouped
} advances;

feature chws {
  lookup advances;
} chws;

```
