### ISSUE TITLE
Automate harfbuzzjs/uharfbuzz releases

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2839]
On a Harfbuzz release, update the git modules in uharfbuzz / harfbuzzjs, build, run tests, tag and release if they pass.

**Comment by khaledhosny** [comment]
Is there a way to trigger an action in one repo based on a change in another repo?

**Comment by alerque** [comment]
There is in GitLab and I have to imagine GitHub has similar abilities, but the trigger API is quite different and I'm not sure off the top of my head how it needs to be setup.

**Comment by anthrotype** [comment]
Not sure it's a good idea to fully automate release of py/js wrappers based on the cadence of the release schedule of the upstream HB library. There may be other issues that may block a new release for downstream projects (unrelated bugs, pending PRs, etc.).
It's better that some human (ideally the same one releasing hb upstream, but not necessarily) takes reponsibility to also keep the downstream wrappers up to date on a best-effort basis.

**Comment by simoncozens** [comment]
GitHub actions can *draft* a release.

**Comment by anthrotype** [comment]
personally, i think this is a bit overengineering but feel free to ignore me

**Comment by anthrotype** [comment]
speaking of overengineering.. Another way could be that we separate uharfbuzz cython wrapping from the harfbuzz C++ library itself. That is, we'd have uharfbuzz only link dynamically at runtime with the harfbuzz library, instead of the current statically linked built-from-amalgam-source harfbuzz library that is embedded in the distributed python wheel package.

We could create a separate (e.g.`charfbuzz` or `harfbuzz-sys`) psuedo-python package that only contains this harfbuzz shared library and distribute that via PyPI, then have uharfbuzz dynamically load from that one at import time (or if that is not installed, try loading from the system harfbuzz).

Then we could automate the release of the upstream harfbuzz with this pre-compiled shared library, and provided there are no breaking changes the current uharfbuzz module should continue to work with the updated library.

**Comment by behdad** [comment]
Still relevant or not?

**Comment by khaledhosny** [comment]
I currently update uharfbuzz manually, harfbuzzjs is stuck with 3.0.0 and I tried to unstuck it but failed. I don't think any automation is going to save us much.
