### ISSUE TITLE
[gen-hb-version.py] Ignore samefile error

### ISSUE THREAD

**Issue by Neumann-A** [harfbuzz/harfbuzz#2870]
original vcpkg issue: https://github.com/microsoft/vcpkg/issues/16262

Error:
```
\\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\meson.build:1:0: ERROR: Running configure command failed.

Traceback (most recent call last):
  File "\\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\gen-hb-version.py", line 36, in <module>
    shutil.copyfile (OUTPUT, os.path.join (CURRENT_SOURCE_DIR, os.path.basename (OUTPUT)))
  File "shutil.py", line 241, in copyfile
shutil.SameFileError: '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h' and '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\hb-version.h' are the same file
```

Probably a meson issue but there is actually no reason to error on samefile in `gen-hb-version.py`

**Comment by Krzmbrzl** [comment]
To me it seems like this could easily prevented by checking whether source and destination in this call
https://github.com/harfbuzz/harfbuzz/blob/769a21aab6a2b1c43cc10d56de3861a3add723de/src/gen-hb-version.py#L35-L36
are equal and if so, don't attempt to copy.

Do you want a more sophisticated fix or shall I create a PR?

**Comment by khaledhosny** [comment]
I think the proper fix is to find why the source and destination are the same, as it does not make sense. We are generating the file in the build directory, then copying it also to the source directory, but I don’t think meson allows in-tree builds so I don’t see how this error would happen. The paths in the error message look different, so I don’t see either how the are the same file, some kind of symlink?

**Comment by Krzmbrzl** [comment]
> I think the proper fix is to find why the source and destination are the same, as it does not make sense

Agreed. My suggestion was meant more as a quick workaround until that has been figured out.

I encountered this issue using vcpkg (see link in original post) and it starts out from a clear build directory. Thus currently the best guess we have is that for some reason meson is configuring the file twice: https://github.com/mesonbuild/meson/issues/8375

**Comment by khaledhosny** [comment]
A quick fix might be hiding the real issue.

[shutil.SameFileError](https://docs.python.org/3/library/shutil.html#shutil.SameFileError) “is raised if source and destination in `shutil.copyfile()` are the same file”, so even meson configuring multiple times wouldn’t cause this, and the paths shown in the error message are different so we aren’t copying the file to itself. This seems to me like something specific to your setup or vcpkg.

On macOS, I get this error from `shutil.copyfile()` if I try to copy a file to itself or a to a link to it, but not a different file with the exact same content.

**Comment by behdad** [comment]
Is there some symlinking (the Windows equivalent?) involved? How can the two filenames be the same?
`'\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h'`
`'\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\hb-version.h'`

**Comment by Krzmbrzl** [comment]
There is Symlinking involved, but probably not in the way that you were referring to.

I am running vcpkg in a Windows VM from a Linux machine. My vcpkg directory is located on an external hard-drive so in order for the VM to be able to access this directory, I symlinked the vcpkg directory into the referenced `Shared` directory that is then accessible from within the VM (running via VirtualBox).

However I did not create any SymLinks within the vcpkg directory myself. I don't know what vcpkg itself does though. This is something that @Neumann-A can probably answer.

**Comment by Neumann-A** [comment]
>However I did not create any SymLinks within the vcpkg directory myself. I don't know what vcpkg itself does though. This is something that @Neumann-A can probably answer.

vcpkg does not symlink unless your build script is symlinking. As it turns out `shutil.copyfile()` will symlink if the source is a symlink. So something here seems to be running twice.

**Comment by eli-schwartz** [comment]
I can trivially reproduce this issue with:


```
git clone https://github.com/harfbuzz/harfbuzz
cd harfbuzz
ln -s builddir/src/hb-version.h src/hb-version.h
meson setup builddir
```

The crucial point here is that the git source code needs to have been overwritten with a symlink pointing to the build directory, but that symlink will never have been created by meson or by harfbuzz. I don't know why it ever would be created by hand, though.

The alternative is that the builddir was configured, and then builddir/src/hb-version.h was overwritten with a symlink pointing to ../../src/hb-version.h, and then meson.build's `project(..., version: '...')` was also updated in order to force a reconfigure with a different version, and then, finally, ninja was run again and meson was forced to reconfigure. But this seems entirely implausible.

Both files are 100% created by harfbuzz, never by meson. And harfbuzz does not create either *file* as a symlink object. 

Whether there are symlinks elsewhere is irrelevant, unless somehow:

- `\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\`
-  `\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\`

both resolve to the same directory, which should be impossible. meson will report: "ERROR: Source and build directories must not be the same."

**Comment by khaledhosny** [comment]
#3508 might fix this by not copying the file at all when its content is not changed (which is what happens in normal builds).
