### ISSUE TITLE
Combinging tilde character not rendering correctly

### ISSUE THREAD

**Issue by julianbarg** [harfbuzz/harfbuzz#2880]
I am running firefox on ubuntu 20.04. Harfbuzz version 2.6.4 which I _belief_ does the text rendering.

The binding tilde above the word Semel in this tweet does not render correctly: https://twitter.com/kochkunstRecook/status/1364926379431768068?s=20

Rendering correctly on macos: 
![image](https://user-images.githubusercontent.com/40502144/109163718-9fa97b80-7747-11eb-8fae-d39b1f438e1b.png)

Rendering incorrectly on my machine:
![image](https://user-images.githubusercontent.com/40502144/109163772-af28c480-7747-11eb-982a-df6c2fa6f61a.png)

Letter is U+0303 combining tilde, which is supposed to be a non-spacing mark:
https://www.fileformat.info/info/unicode/char/0303/index.htm

**Comment by julianbarg** [comment]
Text is in UTF-8, unicode source is ```00000000: 5365 6dcc 8365 6c0a                      Sem..el.```

**Comment by jfkthame** [comment]
Looks to me like you're getting *correct* rendering (the combining tilde is positioned nicely on the "m", which is its base character), whereas on macOS it's misplaced to the right.

That happens because on macOS the tweet is displayed using the macOS system font, which has a GPOS table (so fallback positioning isn't applied) but lacks the proper positioning data for this combination.

So I think there's nothing wrong with harfbuzz here; but the results are dependent on the font being used.

**Comment by julianbarg** [comment]
Thanks, sounds plausible to me.
