### ISSUE TITLE
Meson doesn't cross compile mingw missing link flag libstdc++?

### ISSUE THREAD

**Issue by mehmooda** [harfbuzz/harfbuzz#2978]
On fedora 34:

Using default flags output from `rpm --eval "%{mingw64_meson}"`
```
CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4
LDFLAGS=-fstack-protector -lssp
CXXFLAGS=$CFLAGS

meson --cross-file /usr/share/mingw/toolchain-mingw64.meson --buildtype release halfbuzzbuild harfbuzz
```
Unable to build as missing symbol __gxx_personality_seh0

Should there be a libstdc++ in the meson.build?

**Comment by behdad** [comment]
We try not linking to libstdc++ by disabling exceptions and rtti. I don't know meson so I can't help here.

**Comment by jpakkane** [comment]
I'd be inclined to say that `-fexceptions` is wrong there. That is the default on all other platforms so why is it there in the first place? That is Fedora packagers saying "all code built with MinGW must have exceptions enabled" which seems a bit strange. Not to mention it should not even be in `CFLAGS`, but `CXXFLAGS` because it is only useful for C++ code.

**Comment by khaledhosny** [comment]
I think this is the same as https://github.com/gentoo/gentoo/pull/20849, so I think we need to fix meson to follow what the autotools build does here.

**Comment by khaledhosny** [comment]
Though I have no idea how to tweak this:
https://github.com/harfbuzz/harfbuzz/blob/5e0ec33b3d9379b78084cd59a9ebed3fc583eed6/meson.build#L46-L51

**Comment by behdad** [comment]
So what needs to be done here?

**Comment by khaledhosny** [comment]
Have the equivalent of the following in meson:
https://github.com/harfbuzz/harfbuzz/blob/62a535f154a9453c7d16c669094c254666a6caac/configure.ac#L86-L88

**Comment by khaledhosny** [comment]
I guess, assuming that it works with autotools. But based on https://github.com/harfbuzz/harfbuzz/issues/2978#issuecomment-842680594, I’d say it is a Fedora bug and nothing should be done here.

**Comment by khaledhosny** [comment]
Autotools build is simply overriding `-fexceptions` flag set in CXXFLAGS, meson is respecting it but setting it was wrong to begin with. May be we can bring back `with_libstdcxx` removed in 0151da23d605c7709d432ebfb17a337a5f662839, if we really care about fixing this, otherwise seems we are going to require libstdc++ soonish.
