### ISSUE TITLE
Synthesizing variable width spaces should maybe be optional

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3053]
I was recently trying to fix an old pango bug: https://gitlab.gnome.org/GNOME/pango/-/issues/249 .
I implemented Behdad's suggestion to always put spaces in the run with the better font match, and ... it didn't help, since harfbuzz is happily synthesizing spaces with different widths for the different Unicode spaces. Judging from that bug,
some might find this behavior surprising, in particular when the font that is used is monospace.

harfbuzz doesn't really have a notion of monospace fonts, so I wouldn't expect it to be smart about this, but
maybe there could be a buffer option to make all synthesized spaces have the same width?

An alternative position (and maybe the better one) is to say: If you want a grid, don't rely on PangoLayout
and monospace fonts, use something like vte.

**Comment by alerque** [comment]
> use something like vte.

This is probably the right answer, with emphasis on something **like** VTE (VTE itself being [a terrible base](https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty).

I could see a use case for asking for shaping with specific size synthesized spaces rather than completely deducing them, but for the case of the other bug it sounds like even that would be a bandaid on misplaced user expectations, no?

**Comment by khaledhosny** [comment]
You can override HarfBuzz fallback by returning true in Pango’s `get_nominal_glyph` for the missing space charcters function and handle the fallback in Pango (either conditionally for monospace fonts only, or unconditionally if you prefer more control)

**Comment by matthiasclasen** [comment]
ah, good point. thanks
