### ISSUE TITLE
[subset] Use a central API for various sets

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3130]
Reviewing the subset library API (as part of https://github.com/harfbuzz/harfbuzz/issues/3078) I see:
```
0000000000046ac0 T _hb_subset_input_create_or_fail
0000000000046fe0 T _hb_subset_input_destroy
00000000000471d0 T _hb_subset_input_drop_tables_set
0000000000047210 T _hb_subset_input_get_flags
00000000000473e0 T _hb_subset_input_get_user_data
0000000000047150 T _hb_subset_input_glyph_set
00000000000471b0 T _hb_subset_input_layout_features_set
0000000000047170 T _hb_subset_input_nameid_set
0000000000047190 T _hb_subset_input_namelangid_set
00000000000471f0 T _hb_subset_input_no_subset_tables_set
0000000000046f10 T _hb_subset_input_reference
0000000000047230 T _hb_subset_input_set_flags
0000000000047250 T _hb_subset_input_set_user_data
0000000000047130 T _hb_subset_input_unicode_set
00000000000c2060 T _hb_subset_or_fail
```

we merged all boolean flags into one flags API. I suggest we also merge all the "set" APIs into one `hb_subset_input_???_set` with an enum. We will keep adding such sets for sure (for variation axes, other aspects).

**Comment by behdad** [comment]
WDYT? @garretrieger @bungeman

**Comment by behdad** [comment]
So, of these sets:

> 0000000000047130 T _hb_subset_input_unicode_set
> 00000000000471d0 T _hb_subset_input_drop_tables_set
> 0000000000047150 T _hb_subset_input_glyph_set
> 00000000000471b0 T _hb_subset_input_layout_features_set
> 0000000000047170 T _hb_subset_input_nameid_set
> 0000000000047190 T _hb_subset_input_namelangid_set
> 00000000000471f0 T _hb_subset_input_no_subset_tables_set

Garret expressed that my proposed unifying them doesn't make the API easier to use. I still like to do it because it makes the various sets enumerable.

A couple naming issues: "layout_features" and "no_subset_tables" and "drop_tables" are plural but shouldn't be.

I'm fine having direct API for glyph set and unicode set as well, treating them above others, but the rest to me should go in an enum. We can make the names also identify whether it's a tag set or index set. Like: `layout_feature_tag` `name_lang_index` etc.

**Comment by garretrieger** [comment]
That works for me, most existing uses only use the glyph_set/unicode_set so leaving those as is will avoid introducing more breakage. Shall I make a draft pr for the changes?

**Comment by behdad** [comment]
> Shall I make a draft pr for the changes?

That would be great. Do a draft API proposal and we tweak the naming a lot first, then implement :)).

**Comment by bungeman** [comment]
Just wanted to make a user observation that putting function behind enums makes it really difficult to write code that works across any transition which adds new enum values.

In C one needs to always do conditional compilation with macros, so it's nice to use macros instead of enum names. Those only ever updating to tagged releases can use the HB_VERSION_* macros to imply the existence of new API, but currently those trying to keep a bit more up to date may have issues here.

In C++ so long as there is a dependent type taken by a function (and there more or less always is) then one can use templates to do detection and code selection. However, enum values cannot be tested for existence.

In other words, from someone who tries to keep up with API changes and additions, it would be nice if these 'enums' were actually a collection of macros (works with C and C++), or everything were a dependent function (works with C++), or maybe have a more finely grained version macro `HB_VERSION_PICO` which bumps every time any public API at all changes during development. Basically, anything that could be used to ease rollout of new or changed API.

Also, the flag API change made some sense, but still seems like an awkward exposure of internals for not much gain. This API change makes even less sense from a user perspective, it looks like random functions are being collapsed because they happen to have a similar return value, not because they're actually related. Also, it's actually easier for users to conditionally use a new function than a new enum value, since it's possible to test for new functions but not new enum values.

**Comment by behdad** [comment]
@bungeman @drott In the future just ask us to tag a release if you want to rely on new HB API in Chrome / Skia.
