### ISSUE TITLE
Build failure on macos

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3208]
Since the ragel subproject appeared in harfbuzz, the GTK ci build has been failing on macos:

https://gitlab.gnome.org/GNOME/gtk/-/jobs/1517300

**Comment by khaledhosny** [comment]
I might have accidentally depended on too new meson version, as the meson version you are using does not seem to like the second `ragel.found()` call. Unfortunately I’m not able to investigate further at the moment. We probably should also add an option not to build ragel at all and may be make it the default since most harfbuzz builders don't need it.

A quick fix for you is probably to install ragel on the CI job.

**Comment by behdad** [comment]
Let's get 3.0.0 out after this is settled.
