### ISSUE TITLE
Is it possible to implement SVG table

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#332]
Several days ago, I found OT specification added 'SVG ' table to introduce SVG formatted glyph.

**Comment by behdad** [comment]
SVG was added in 2013.

**Comment by behdad** [comment]
(to the OpenType spec that is.)

**Comment by jfkthame** [comment]
Does this have anything to do with harfbuzz? It's an alternative glyph description for rasterization, but AFAIK has no relation to shaping.

**Comment by behdad** [comment]
> Does this have anything to do with harfbuzz?

Right.  Not with shaping.

Recently it has become quite compelling to implement tables that will be needed on every platform into HarfBuzz instead of FreeType.  MATH table is the latest one, but there's been request for COLR/CPAL and now SVG as well (just exposing table data).

Similarly, a variable-fonts instancer can be useful on every platform (to instance and feed glyf outlines to older OS rasterizers), and I've been thinking about putting that in HarfBuzz.

If these happen, then we probably need a more granular config system to allow building without those.  Or, maybe I should go ahead and compile them into a separate library.  harfbuzz-extra.so or something.

**Comment by Jolg42** [comment]
Hi,

Do you think that now after Adobe's and Microsoft's move on OpenType SVG it would be implemented? I think that 2017 can be the color font year :)

**Comment by KrasnayaPloshchad** [comment]
EmojiOne bring a font for test.
https://github.com/Ranks/emojione/tree/master/extras/fonts

**Comment by KrasnayaPloshchad** [comment]
> Recently it has become quite compelling to implement tables that will be needed on every platform into HarfBuzz instead of FreeType. MATH table is the latest one, but there's been request for COLR/CPAL and now SVG as well (just exposing table data).

OK, I think you’re right, several web browers, word processors already supported SVG, so HarfBuzz can just add (at least expemental) API to expose the who data from SVG table, then the client can get glyphs and rendering them when necassary, also making them proper aligned within the text.

**Comment by KrasnayaPloshchad** [comment]
Close.
