### ISSUE TITLE
hb-subset changes shaping behavior

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#3328]
This is probably similar to #3323:

```
simon@Simons-Air ~/work/nastaliq/gulzar .*$ hb-subset --unicodes='*' --glyph-names fonts/ttf/Gulzar-Regular.ttf --layout-features="*"  -o Gulzar-Subset.ttf
simon@Simons-Air ~/work/nastaliq/gulzar .*$ hb-shape fonts/ttf/Gulzar-Regular.ttf 'سعگگے' --ned --no-positions
[BARI_YEf1|endOfBariYe|GAFm7|GAFm3|AINm8|SINi2]
simon@Simons-Air ~/work/nastaliq/gulzar .*$ hb-shape Gulzar-Subset.ttf 'سعگگے' --ned --no-positions
[BARI_YEf1|endOfBariYe|GAFm7|GAFm3|AINm1|SINi2]
```

But the resolution there (raising `HB_MAX_LOOKUP_INDICES`) does not help. Instead it causes `error: Operation failed. Probably a bug. File github issue.`. So I'm doing that. Font available on request.

**Comment by garretrieger** [comment]
This is a failure of the overflow resolver. There's two issues it runs into:

1. The resolver hits max rounds (10) before it's finished subdividing the spaces. I'll increase the max rounds.
2. With a higher max rounds, it finishes the subdividing but runs into overflows within a single extension lookup that's been isolated to it's own space. I'll need to look further into that subgraph to see what the problem is.

**Comment by garretrieger** [comment]
Ok I was able to get this to pack, it just needs a more aggressive priority raising step. Right now as priority is raised on a children it just incrementally reduces the distance by up to the vertices data size. At max priority this will move the children to the start of their layer, but no further. To get this to pack successfully it's necessary to move the children to be packed immediately after the parent node. This can be done by setting the children's distance to '0' which forces them to pack as soon as the parent has been packed.

This is likely a case where it makes sense to move the parent down instead of the children up, but that's not implemented yet. For now I'll update the children priority handling code.

**Comment by simoncozens** [comment]
This now successfully repacks, and there are no errors! But the shaping behaviour is still different:

```
$ hb-shape Gulzar-Subset.ttf 'سعگگے' --ned --no-positions
[BARI_YEf1|endOfBariYe|GAFm7|GAFm3|AINm1|SINi2]
$ hb-shape fonts/ttf/Gulzar-Regular.ttf 'سعگگے' --ned --no-positions
[BARI_YEf1|endOfBariYe|GAFm7|GAFm3|AINm8|SINi2]
```

and the ...m8 glyphs are still gone from the rules.

**Comment by simoncozens** [comment]
Yeah, the rules which create the m8 glyphs are all being pruned from the big reversesub:

```diff
-        <ReverseChainSingleSubst index="119" Format="1">
-          <Coverage>
-            <Glyph value="LAMm1"/>
-          </Coverage>
-          <!-- BacktrackGlyphCount=0 -->
-          <!-- LookAheadGlyphCount=1 -->
-          <LookAheadCoverage index="0">
-            <Glyph value="GAFm3"/>
-            <Glyph value="KAFm3"/>
-          </LookAheadCoverage>
-          <!-- GlyphCount=1 -->
-          <Substitute index="0" value="LAMm8"/>
-        </ReverseChainSingleSubst>
```

**Comment by simoncozens** [comment]
Urgh, this is brittle. I took out an unneeded lookup (lookup 56) from the original font, and now I'm getting `overflow resolution failed` again.

**Comment by garretrieger** [comment]
I'll take another look.

**Comment by garretrieger** [comment]
https://github.com/harfbuzz/harfbuzz/pull/3333 should fix the new failure.
