### ISSUE TITLE
Expose what is needed to do italic correction

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3346]
Here is an ancient Pango issue discussing italic correction. It suggests using slant angle and font ascent:
https://gitlab.gnome.org/GNOME/pango/-/issues/37

I wonder if there's anything else that could or should be used here, in the font data that harfbuzz has.

**Comment by alerque** [comment]
Some fonts (at least in source formats, not sure where this is in the OpetType or other specs) actually have an italic correction value that can be tweaked by the designers. Not context aware that I know of, just a single value for the font.

**Comment by jfkthame** [comment]
> Some fonts (at least in source formats, not sure where this is in the OpetType or other specs) actually have an italic correction value that can be tweaked by the designers. 

The most common place this is found is the .tfm (TeX Font Metric) files generated by Metafont and used by TeX. There are also .tfm files available for various non-Metafont fonts, although the quality of the italic-correction metrics may be a bit variable, depending how they were derived (carefully set by a font designer, or derived by some automated tool).

> Not context aware that I know of, just a single value for the font.

A single value per character, not a single value for the font.

In OpenType, I think the only "italic correction" values are those in the MATH table (see https://docs.microsoft.com/en-gb/typography/opentype/spec/math#mathitalicscorrectioninfo-table); there are no such values in normal text fonts.

**Comment by jfkthame** [comment]
> Here is an ancient Pango issue discussing italic correction. It suggests using slant angle and font ascent

This would be a fairly crude approximation of what italic correction is supposed to do, though perhaps better than nothing in many cases.

The trouble is that it completely fails to take account of the actual shape of the glyph "ink", and just works with the overall bounding box. Consider the difference between `“<i>H</i>”` and `“<i>L</i>”` (“*H*” and “*L*”). An "italic correction" derived from "slant angle and font ascent" will add space between the *H* and the following (non-italicized) quote mark, which is exactly what is desired; but it will add the same space between the *L* and the following quote mark, where it is not needed and will look quite bad.

To handle this properly, the italic correction value needs to be based on the actual shape of the glyph, not merely on the slant of its bounding box.

**Comment by matthiasclasen** [comment]
Right, I'm aware of the precedent in TeX (from a prior life).

I was more interested to learn what (if anything) other systems do

**Comment by khaledhosny** [comment]
There are several ways to “guess” italic correction since OpenType (outside of MATH table) has no way for the font designer to set it:
1. XeTeX uses the [difference between advance width and the bounding box width](https://sourceforge.net/p/xetex/code/ci/master/tree/source/texk/web2c/xetexdir/XeTeXFontInst.cpp#l461) (if the glyph protrudes outside its advance width).
2. luaotfload (for LuaTeX) seems to do [something similar](https://github.com/latex3/luaotfload/blob/c2b9a02c5e6a2c40f317f02881f4bed86658b4ab/src/fontloader/misc/fontloader-font-con.lua#L836-L840), but adds [1/2 the underline width to the value](https://github.com/latex3/luaotfload/blob/c2b9a02c5e6a2c40f317f02881f4bed86658b4ab/src/fontloader/misc/fontloader-font-imp-italics.lua#L47) (!).
3. FontForge seems to do [something similar but adds UPEM/16 to the value](https://github.com/fontforge/fontforge/blob/a9c96f5e03ad260db3b28f474fa5455304e3c32a/fontforgeexe/charinfo.c#L3591-L3593) (!)

None of these seems to handle RTL text, but for RTL text left side bearing (if it is negative) can be used instead.

**Comment by jfkthame** [comment]
Yes, these sort of guesses may work reasonably well in many cases; that's why I originally implemented such a heuristic in xetex. But it's important to be aware that they will sometimes be badly wrong. E.g. letters like [the "q" and "k" in Berkshire Swash](https://fonts.google.com/specimen/Berkshire+Swash?category=Handwriting&preview.text=the%20quickest%20brown%20fox&preview.text_type=custom) would be assigned a large italic correction as a result of their projecting "tails", but this is not actually wanted.

**Comment by behdad** [comment]
> E.g. letters like [the "q" and "k" in Berkshire Swash](https://fonts.google.com/specimen/Berkshire+Swash?category=Handwriting&preview.text=the%20quickest%20brown%20fox&preview.text_type=custom) would be assigned a large italic correction

We can limit those...

I still think half of slant * ascent is a better default than nothing.
