### ISSUE TITLE
Font name parsing error (hb_ot_name_get_utf8)

### ISSUE THREAD

**Issue by mealdy** [harfbuzz/harfbuzz#3465]
The function `hb_ot_name_get_utf8` doesn't return complete name info for some font files.

Sample code:
(No external unicode lib used, just built-in ucd)
```
unsigned int text_size = 10240;
char name[text_size];
hb_ot_name_get_utf8 (face, name_id, lang, &text_size, name);
```

The copyright field ouput: `1.01  Hee Haw Casual `
The expected ouput: `1.01  Hee Haw Casual  ©1993         By Richard William Mueller`

Font file was attached below.
[HeeHawRegular.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/8172255/HeeHawRegular.ttf.zip)
[Kramer-Regular.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/8172290/Kramer-Regular.ttf.zip)

The copyright field in Font Book app:
![Snip20220302_1](https://user-images.githubusercontent.com/2469602/156430629-246bd13d-cb0c-4068-a0fa-fa7bcfd384c7.png)

**Comment by jfkthame** [comment]
This is an issue with the font file. A hex dump of part of the `name` table shows:
```
00000240  00 01 04 09 00 06 00 1c  01 eb 31 2e 30 31 20 20  |.........Î1.01  |
00000250  48 65 65 20 48 61 77 20  43 61 73 75 61 6c 20 20  |Hee Haw Casual  |
00000260  a9 31 39 39 33 20 20 20  20 20 20 20 20 20 42 79  |©1993         By|
00000270  20 52 69 63 68 61 72 64  20 57 69 6c 6c 69 61 6d  | Richard William|
00000280  20 4d 75 65 6c 6c 65 72  00 31 00 2e 00 30 00 31  | Mueller.1...0.1|
00000290  00 20 00 20 00 48 00 65  00 65 00 20 00 48 00 61  |. . .H.e.e. .H.a|
000002a0  00 77 00 20 00 43 00 61  00 73 00 75 00 61 00 6c  |.w. .C.a.s.u.a.l|
000002b0  00 20 00 20 00 00 00 31  00 39 00 39 00 33 00 20  |. . ...1.9.9.3. |
000002c0  00 20 00 20 00 20 00 20  00 20 00 20 00 20 00 20  |. . . . . . . . |
000002d0  00 42 00 79 00 20 00 52  00 69 00 63 00 68 00 61  |.B.y. .R.i.c.h.a|
000002e0  00 72 00 64 00 20 00 57  00 69 00 6c 00 6c 00 69  |.r.d. .W.i.l.l.i|
000002f0  00 61 00 6d 00 20 00 4d  00 75 00 65 00 6c 00 6c  |.a.m. .M.u.e.l.l|
00000300  00 65 00 72 48 65 65 48  61 77 00 48 00 65 00 65  |.e.rHeeHaw.H.e.e|
```
Here we see the two versions of the "copyright" string. One is in MacRoman encoding, and includes the copyright symbol; this must be what Font Book is showing. However, the Unicode version of the string does not have the copyright symbol at all; instead, it has a NULL character (`00 00`, at offset `000002b4` in the file).

Likewise in the Kramer-Regular font.

I guess this was simply a bug in Fontographer 3.5, which was used to generate both these fonts.

One question: does the `text_size` returned by `hb_ot_name_get_utf8` correspond to the full name *including* the embedded NULL character (and you're seeing it truncated because you're printing it as a C string), or does it return a truncated version? That would be a bug, I believe -- but I think it's more likely the truncation is being done by subsequent code that treats it as a NULL-terminated C string.

**Comment by mealdy** [comment]
@jfkthame Thanks for your info. I checked the code and it is indeed a NULL-terminated c string. I think I need to handle this myself. By the way, is there anyway to get both the two versions of copyright with HarfBuzz?

**Comment by behdad** [comment]
> By the way, is there any way to get both the two versions of copyright with HarfBuzz?

No.
