### ISSUE TITLE
What's the macos gcovr build failure about?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3540]
Example:
https://github.com/harfbuzz/harfbuzz/runs/6099834243?check_suite_focus=true

**Comment by khaledhosny** [comment]
I can’t reproduce it locally (but I get a different error). Web search leads to this https://github.com/gcovr/gcovr/issues/586

**Comment by latk** [comment]
Hi, I'm a maintainer for gcovr. Very sorry that you are affected by this bug, but it's proving difficult to address without ripping out otherwise useful features.

You are seeing the failures only on macOS because your different environments seem to be using wildly different gcovr versions.

* `apt-get install gcovr` on Ubuntu 18.04 Bionic gives you gcovr 3.4, which was the first release I did back in 2018.
* `brew install gcovr` currently gives you gcovr 5.1, which introduced the failing assertion.

Please consider installing gcovr via Python's PIP package manager, which also lets you pin a particular version, e.g. `pip install 'gcovr==5.0'`.

**Comment by behdad** [comment]
Thanks @latk.
