### ISSUE TITLE
Tarball size

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3802]
Our release tarball size has grown to over 14MB. I suppose most of these are test font files?

test/subset/data seems to be 48MB. @garretrieger any way we can trim that down?

**Comment by behdad** [comment]
Alternatively, we don't have to distribute these all.

Or maybe this is a non-issue.

**Comment by garretrieger** [comment]
Size appears to be taken up be both the expected files and the input font files for the tests.

For the input font files: we include quite a few full font files, we could potentially try to subset down some of the larger ones to just the interesting parts for the tests.

For the expected files: reducing the size of the input font files may help here for tests that include the "*" subset, but otherwise not much to be done.

As you suggest, just not distributing them is probably reasonable, or just distribute a set of small basic test fonts rather than the full set.
