### ISSUE TITLE
Incorrect deltaGlyphId type

### ISSUE THREAD

**Issue by DmLvkvch** [harfbuzz/harfbuzz#3814]
HI

according to ms spec https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#11-single-substitution-format-1

deltaGlyphId should be Signed 16 bit integer value

**Comment by behdad** [comment]
It doesn't make a difference in this case, and signed 16 bit is a bit misleading, so I decided to declare it unsigned.

All that matters is that the summation is done modulo 0xFFFF; which we do. That's the same for signed vs unsigned. Since the initial glyph-id and final result are both unsigned, it makes more sense to define the delta as unsigned as well.
