### ISSUE TITLE
another odd HB_GLYPH_FLAG_UNSAFE_TO_BREAK case

### ISSUE THREAD

**Issue by caolanm** [harfbuzz/harfbuzz#3888]
Similar to issue 3824 and with the same font, and with the fix there applied, I have another case where we get different results when we verify that the cached results match what we would get if we didn't cache. (But maybe the problem is in the expectations)

In this test case with string " »!”" we get HB_GLYPH_FLAG_UNSAFE_TO_BREAK set on the ! of that input, but no HB_GLYPH_FLAG_UNSAFE_TO_BREAK set on the ! with "»!”" Any guidance on if that's expected?

[harfbuzz-demo.zip](https://github.com/harfbuzz/harfbuzz/files/10075847/harfbuzz-demo.zip)

**Comment by behdad** [comment]
I can reproduce this:
```
behdad:hb 0 (main)$ build/util/hb-shape XBRoya34.ttf ' »!”' --show-flags --script=arab
[quotedblright=3+736|exclam=2+621#1|guillemotleft=1+895|space=0+600]
behdad:hb 0 (main)$ build/util/hb-shape XBRoya34.ttf '»!”' --show-flags --script=arab
[quotedblright=2+736|exclam=1+621|guillemotleft=0+895]
```

**Comment by behdad** [comment]
> But maybe the problem is in the expectations

I think this is a case of the expectation being wrong. The previous fix speculatively turned on unsafe-to-break for some positions. The unsafe-to-break in this case is turned on because we cannot guarantee that it's safe to break on that position when you shape with a space at the beginning. But when you shape without a space, we do realize that it is indeed safe to break there.

The only guarantee of the unsafe-to-break flag is that if it's not present, if you break at that point and shape the two sides, you get the same glyph results. As you demonstrated now, it doesn't guarantee that you get the same flags. It's something that maybe was the case before, but not after the recent change.

**Comment by behdad** [comment]
I am surprised that passing `--verify` to hb-shape passes though, since our verification code expects what you expected indeed.

**Comment by behdad** [comment]
> I am surprised that passing `--verify` to hb-shape passes though, since our verification code expects what you expected indeed.

It happens by pure luck I think.

**Comment by behdad** [comment]
> > I am surprised that passing `--verify` to hb-shape passes though, since our verification code expects what you expected indeed.
> 
> It happens by pure luck I think.

No. The buffer-diff code specifically allows glyph flags to be a subset of the reference buffer glyph flags.

**Comment by behdad** [comment]
> The buffer-diff code specifically allows glyph flags to be a subset of the reference buffer glyph flags.

That seems like a bug though. Fixing.

**Comment by caolanm** [comment]
I relaxed the verification to ignore HB_GLYPH_FLAG_UNSAFE_TO_BREAK but then ran into another case

```
hb-shape XBRoya34.ttf " الأشزّاء. " --direction=r --script=arab --language=ar --show-flags
[space=10+600|period=9+621#1|afii57409=8+943|afii57415=7+460#1|afii57457_alt=5+1#1|uniFEB0=5+877#1|uniFEB7=4+1432|uniFEF7=2+1235#1|afii57415=1+460|space=0+600]

hb-shape XBRoya34.ttf "الأشزّاء. " --direction=r --script=arab --language=ar --show-flags
[space=9+600|period=8+621#1|afii57409=7+943|afii57415=6+460#1|afii57457_alt=4+1#1|uniFEB0=4+877#1|uniFEB7=3+1432#1|uniFEF7=1+1135#1|afii57415=0+460]
```

**Comment by behdad** [comment]
Indeed, --verify fails on those strings. I have to debug. sigh.

**Comment by behdad** [comment]
I see what's going on.

**Comment by behdad** [comment]
> I see what's going on.

It's the same issue with GPOS PairPos when ValueFormat2 is not zero.  The only valid way I see is to mark the entire string as unsafe to break, since the even/odd position of the glyph in the string is going to determine whether pairpos is applied to it or not.  Before trying that I'm going to apply another patch.

**Comment by behdad** [comment]
Okay I fixed that. Hope it doesn't pop up another way again.
