### ISSUE TITLE
[docs] There's three undocumented symbols

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3957]
First one seems to have docs but not picked up. Don't know why.
```
HB_OT_NAME_ID_INVALID 
hb_ot_tag_from_language 
hb_ot_tags_from_script 
```

**Comment by khaledhosny** [comment]
gtk-doc limitations I don’t know how to handle:

* `HB_OT_NAME_ID_INVALID`:
   All values for `hb_ot_name_id_t` are actually undocumented. I think this is because of the weird way this is declared (an enum but not so much enum).
* `hb_ot_tag_from_language` and `hb_ot_tags_from_script`:
  They were undocumented indeed, fixed in f9e1192d58e54f6719993a1694aee0a73198d63d, gtk-doc does not like our `HB_DEPRECATED_FOR()` so all deprecated symbols using it don’t end up in the generated documentation. I tried to make gtk-doc ignore it in 734e5f7cf412e421568963e5a5fe3ee51365163e but it isn’t making any difference.

**Comment by khaledhosny** [comment]
For 2, it seems that gtk-doc 1) wants `HB_DEPRECATED_FOR()` to come first and be on a line of its own, so instead of the current:
```
HB_EXTERN HB_DEPRECATED_FOR (hb_ot_tags_from_script_and_language) hb_tag_t
hb_ot_tag_from_language (hb_language_t language);
```

it wants:
```
HB_DEPRECATED_FOR (hb_ot_tags_from_script_and_language)
HB_EXTERN hb_tag_t
hb_ot_tag_from_language (hb_language_t language);
```

Is such reordering OK?

**Comment by behdad** [comment]
If gobject-introspection and tests are fine, fine with me. Thanks.

**Comment by khaledhosny** [comment]
gobject-introspection seems to be fine, it apparently uses a more intelligent parser that is OK either way.

**Comment by khaledhosny** [comment]
Only `HB_OT_NAME_ID_INVALID` is left now, but I have no idea what to do with this one.
