### ISSUE TITLE
absolute paths in cmake config

### ISSUE THREAD

**Issue by sapiippo** [harfbuzz/harfbuzz#4025]
Change db292f6f0238581a489aa8cddc585129b6e920cd makes cmake config use absolute paths and this breaks things for cross-compilations when harfbuzz is in a sysroot and not in the absolute path used at configure time.

Compilations will then try to use the lib and includes from the host system paths, when they should use everything only from the sysroot.

**Comment by sapiippo** [comment]
Would you accept revert for the commit and let @2xsaiko retry to fix their issue without breaking more things.

**Comment by 2xsaiko** [comment]
Ouch, apologies. Feel free to revert the commit in the meantime, I'll see if I can come up with a solution that works for both cases.

**Comment by albaguirre** [comment]
Ideally CMake config files should be relocatable so that if you compile the library in say one cloud node, you can deploy the binary artifact and its corresponding cmake config file in another without having to change any paths; see https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages

**Comment by behdad** [comment]
Can anyone knowing cmake help here?

**Comment by 2xsaiko** [comment]
Let me take a look again. (Sorry for not doing this until now)
