### ISSUE TITLE
TLB-TTHemalatha - some character incorrect rendered

### ISSUE THREAD

**Issue by marekgruszewski** [harfbuzz/harfbuzz#4032]
Hi,
I ran into a problem with proper rendering some character.
In attached file you can see 2 images showing rendering by Notepad2 and by Harfbuzz (v6.0).
TTF font is in zip file, and text for display is in bi-ligial.txt file.
 My question: 

**Is there any workaround this bug?**

![notepad](https://user-images.githubusercontent.com/122651094/212435984-65b93e27-8b45-4b60-b387-87407df9aced.png)
![harfbuss](https://user-images.githubusercontent.com/122651094/212435951-c086b38f-f64f-430e-aa41-14e3df076830.png)
[TLBHM0NT.zip](https://github.com/harfbuzz/harfbuzz/files/10416005/TLBHM0NT.zip)
[bi-ligial.txt](https://github.com/harfbuzz/harfbuzz/files/10416003/bi-ligial.txt)

**Comment by dscorbett** [comment]
This font puts Telugu glyphs in the non-ASCII half of windows-1252. The glyph HarfBuzz fails to render is mapped to U+00AD SOFT HYPHEN, which is a default ignorable code point. HarfBuzz intentionally suppresses its glyph by default. If `HB_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES` is set (e.g. via hb-view’s `--preserve-default-ignorables` option) then HarfBuzz produces the desired output:
![ó­´ý”–ý](https://user-images.githubusercontent.com/1124347/212442094-e8fc472b-cfbd-4dd2-ad5f-e9c252d695d0.png)
I don’t think there’s anything we can do to fix this in HarfBuzz. Maybe it can be fixed in the font. @behdad, is it possible to tweak 'cmap' or something to get HarfBuzz to recognize this as a font hack and skip all Unicode-aware processing?

**Comment by behdad** [comment]
Thanks David. I see. This should probably have used the symbol cmap instead. This one is not about the font; the input is NOT unicode and I don't see a way to detect / support that.

**Comment by marekgruszewski** [comment]
Work great! Thank you very much!
