### ISSUE TITLE
Upgrade windows msvc CI bot to use a newer version of msvc

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#4137]
I've been investigating the msvc-2019-x86 CI failure on this PR https://github.com/harfbuzz/harfbuzz/pull/4121. I was able to get it to reproduce on a 32 bit windows machine using MSVC 2019. I also tested with a newer version of MSVC (2022) and the test no longer fails. Could we update the CI setup to use the more recent version of MSVC?

**Comment by khaledhosny** [comment]
We generally try to support as old compilers as possible, but I don’t know if MSVC 2019 is still widely used or now, may be @fanc999 have some insight.

**Comment by khaledhosny** [comment]
Both msvc and msys2 32-bit builds are failing from #4121, but msys2 CI job does not use MSVC, it mingw-w64-i686-gcc (gcc 12.2.0). Not sure what to do with this one.

**Comment by behdad** [comment]
That is indeed suspicious. Wonder if there's actually a bug lurking.

**Comment by behdad** [comment]
Okay so there's the MSVC-only fail, which disappears with more recent MSVC. But both MSVC and mingw 32bit bots show a fuzzer failure. That's possibly real... @garretrieger Let me think.

**Comment by behdad** [comment]
I can reproduce the "1 subset fuzzer test failed" on Linux 32bit build as well. So, that one I'll debug.

**Comment by behdad** [comment]
> I can reproduce the "1 subset fuzzer test failed" on Linux 32bit build as well. So, that one I'll debug.

Okay found the root cause. Garret is on it.

**Comment by fanc999** [comment]
> We generally try to support as old compilers as possible, but I don’t know if MSVC 2019 is still widely used or now, may be @fanc999 have some insight.

Hi,

Sadly, I won't be able to give a good answer on that, but I do assume that since Visual Studio 2015 and later link to the same UCRT DLLs, and that intermixing between Visual Studio 2015~2022 shared builds is normally fine, I would presume that people that can't use Visual Studio Community editions due to licensing reasons (since, for instance, they are developing proprietary programs in a sizable team), I would guess that Visual Studio 2019 is still quite prevalent.

Nowadays, I build HarfBuzz with Visual Studio 2017, and is able to reproduce this issue on 32-bit builds as well.

For this one, I think the places that we need to look out for are:
* pointers (since Windows is a LLP64 system)
* Whether we are using APIs that are designated `APICALL`/`__stdcall`.

I will also look into things here.

With blessings, and cheers!

**Comment by fanc999** [comment]
Hi,

I tried testing with the latest Visual Studio 2017, 2019 and 2022 x86, and the test failed, sadly...

Looks like the failure was introduced in commit c0fac016dc017596e2d979e19e1eb8f88df38ea3.

With Visual Studio 2017 x64, the test passed

With blessings, and cheers!

**Comment by fanc999** [comment]
> There was a bug in that commit which was fixed here: [2d33a6b](https://github.com/harfbuzz/harfbuzz/commit/2d33a6b4dfdcd751eba242637c863d810a4a803c) are you still seeing the failure with that commit?

The failure is remedied by Behdad's update (as in my previous post), which is the commit you mentioned.

**Comment by behdad** [comment]
Looks like https://github.com/harfbuzz/harfbuzz/commit/e471ef77f93eeafff2701a31e6c042054ea4f7e1 fixed this after all?
