### ISSUE TITLE
Subsets omit BASE table

### ISSUE THREAD

**Issue by skef** [harfbuzz/harfbuzz#4161]
I'm not seeing the BASE table in subsets with fairly generic arguments, including when I include `HB_SUBSET_FLAGS_PASSTHROUGH_UNRECOGNIZED` (which shouldn't change things as BASE is in the list of `known_tables`. 

(I understand there may be cases where BASE is tricky to subset, including removing or reducing axes in a variable font, but it seems like there are many safe cases where it could just be moved over as-is.)

source-serif has a BASE table if you want reference material: https://github.com/adobe-fonts/source-serif/tree/release/OTF

**Comment by garretrieger** [comment]
BASE is in the default drop tables list: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset-input.cc#L53 So to get it to passthrough you'll need to remove it from the drop tables list. Since we don't yet have subsetting code for BASE you'll also need to enable retain gids so the gid references in the table remain valid.

Let's leave this issue open to track implementation of BASE subsetting support.

**Comment by skef** [comment]
Thanks, that's helpful.

It sounds like it would be fairly low-effort to start passing it through when there's no axis subsetting and when RETAIN_GIDS is specified.

**Comment by behdad** [comment]
BASE subsetting doesn't look that complicated. Maybe @qxliu76 can work on it after she's done with partial-instancing.

**Comment by garretrieger** [comment]
Instancing support was added in #4697
