### ISSUE TITLE
[GI] Serialization of HB_LANGUAGE_INVALID

### ISSUE THREAD

**Issue by jayaddison** [harfbuzz/harfbuzz#4263]
Hi folks,

This is mostly a notification about an issue reported in downstream [Debian bug 1035669](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1035669).  It relates to `harfbuzz` v6.0.0, and from taking a look at the problem, I _think_ it's still likely to be relevant as of v7.3.0, but I have to admit that I haven't confirmed that.

Basically: the `HarfBuzz-0.0.typelib` file built from source doesn't serialize to GIR XML due to unusual handling of the `HB_LANGUAGE_INVALID` constant.

```
ERROR:../girepository/girwriter.c:784:write_constant_value: code should not be
reached
    <constant name="LANGUAGE_INVALID" value="Bail out!
ERROR:../girepository/girwriter.c:784:write_constant_value: code should not be
reached
Aborted
```

My understanding so far is that most languages codes in `harfbuzz` are handled as strings, but that the `HB_LANGUAGE_INVALID` constant (NULL/zero) is a special case: it's not a string, it's not an empty string, in fact it's simply zero (basically a null pointer), for fast and simple comparison purposes, as used in the tests.

The bug appears to be something in the build that results in `HB_LANGUAGE_INVALID` being treated as a [GObject 'interface'](https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/37bde613a7cb77e7399dafb25731e13208f0ae0b/girepository/gitypes.h#L410
) (class-like) instead of a basic, serializable integer type.  The unsupported type results in a [serialization failure here](https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/37bde613a7cb77e7399dafb25731e13208f0ae0b/girepository/girwriter.c#L784).

Based on that, I've offered a patch to Debian (echo'd below) that removes the typecast.  The Debian build and tests pass (this includes most/all of the `harfbuzz` test suite), and serialization to GIR XML succeeds.

I have near-zero practical experience with GTK bindings and the GObject Introspection, so this is mostly based on some trial-and-error and reading [some relevant documentation](https://gi.readthedocs.io/en/latest/annotations/giannotations.html).

```diff
 hb_language_to_string (hb_language_t language);
 
 /**
- * HB_LANGUAGE_INVALID:
+ * HB_LANGUAGE_INVALID: (value 0)
  *
  * An unset #hb_language_t.
  *
  * Since: 0.6.0
  */
-#define HB_LANGUAGE_INVALID ((hb_language_t) 0)
+#define HB_LANGUAGE_INVALID 0
 
 HB_EXTERN hb_language_t
 hb_language_get_default (void);
```

Quite a lengthy ramble for a small detail -- and as the reporter notes, perhaps this is arguably a bug in the `gobject-introspection`.  If so, I'm happy to redirect the conversation over there (and should probably mention it to them anyway).

**Comment by behdad** [comment]
What's different about how Debian builds HB GI? Why do we not see this problem upstream?

**Comment by behdad** [comment]
Thank you. That sounds like a gobject-introspection bug to me? I have successfully used `LANGUAGE_INVALID` in Python, so I don't think the typelib is corrupt. cc @ebassi

Side question: why generate the gir and not use the gir provided by HarfBuzz?

**Comment by dilinger** [comment]
> 
> Side question: why generate the gir and not use the gir provided by HarfBuzz?

The reason to generate the GIR is to satisfy requirements of the debian free software guidelines. For things that we ship in the main archive that are compiled (whether binaries, minified javascript, or generated xml files), we must also provide the source code. If we're shipping a generated xml file that people can't build exactly the same using the provided compilers and source in the archive, then that's a major bug for us. There are ways to verify reproducibility, but it's far easier for package maintainers to just not ship prebuilt stuff from our upstreams, and instead build those additional components during the package build.

(Just FYI. I have nothing to add about why this bug cropped up or whether it's actually a bug in gobject-introspection or not.)

**Comment by reneengelhard** [comment]
Hi,

> ```diff
>  hb_language_to_string (hb_language_t language);
>  
>  /**
> - * HB_LANGUAGE_INVALID:
> + * HB_LANGUAGE_INVALID: (value 0)
>   *
>   * An unset #hb_language_t.
>   *
>   * Since: 0.6.0
>   */
> -#define HB_LANGUAGE_INVALID ((hb_language_t) 0)
> +#define HB_LANGUAGE_INVALID 0
>  
>  HB_EXTERN hb_language_t
>  hb_language_get_default (void);
> ```
> 

Note that this patch is an API change and at least breaks buildng C++ stuff against it. In Debian this was added and (thankfully) reverted (though a workaroundd would have been viable), see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040872.

So adding this should not be done lightly.

**Comment by jayaddison** [comment]
Thanks @reneengelhard - and my apologies for the breakage.  The `sid` suite seems like the correct place for any relevant patches until things here become clearer (or the changes are reverted).

The [workaround](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1035669#39) looks like it only defines the constant for 8.0.0 onwards, and continues to use the typecast.. so I think `g-ir-generate` would continue to fail; does that seem true?

I think I should open a related issue on the [`gobject-introspection` bugtracker](https://gitlab.gnome.org/GNOME/gobject-introspection/).

**Comment by smcv** [comment]
> The reason to generate the GIR is to satisfy requirements of the debian free software guidelines

This doesn't require generating the GIR from the typelib, though! The normal way to handle GObject-Introspection in Debian is the same way it would be done upstream:

```
source code --> binary }
     |                 } --> GIR XML --> typelib --> dynamic language bindings (Python, JS)
     \---------------> }        \--> static language bindings (C++, Rust)
```

This is completely fine from Debian's point of view, as long as we generate the GIR XML from source code ourselves, rather than using some sort of pre-generated GIR XML from elsewhere and hoping that it matches.

I don't know why, but apparently the reporter of Debian#1035669 wants to do this:

```
                             done by Debian | done by them
                                            |
source code --> binary }                    |
     |                 } --> GIR XML --> typelib --> back to GIR XML? --> language bindings
     \---------------> }                    |
```

which until recently I didn't know was even possible. This is a highly unusual use-case and Debian does not normally do it.

**Comment by ebassi** [comment]
Also, general reminder: the GIR → typelib "compilation" is lossy by design; there's no expectation that going from typelib back to GIR fully roundtrips with the original GIR.

Having said that, if there are issues going from typelib to GIR, filing them [upstream](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues) is recommended.

**Comment by smcv** [comment]
> Also, general reminder: the GIR → typelib "compilation" is lossy by design

Right, that's why I hadn't expected it to be possible at all...

**Comment by smcv** [comment]
> Having said that, if there are issues going from typelib to GIR, filing them [upstream](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues) is recommended.

Opened https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/469. I *think* this is a problem with g-ir-generate rather than g-ir-compiler, but I could be wrong.

I don't think the patch proposed in https://github.com/harfbuzz/harfbuzz/issues/4263#issue-1740402546 is correct. Even if it didn't break the C++ API as noted by @reneengelhard, it misleads g-ir-compiler into thinking that `HB_LANGUAGE_INVALID` is an integer rather than a null pointer, which happens to be something that g-ir-generate can cope with, but seems like the wrong thing to have in the GIR XML.

> My understanding so far is that most languages codes in harfbuzz are handled as strings, but that the HB_LANGUAGE_INVALID constant (NULL/zero) is a special case: it's not a string, it's not an empty string, in fact it's simply zero (basically a null pointer), for fast and simple comparison purposes, as used in the tests.

If I'm reading the header correctly, `hb_language_t` is a typedef for `const struct hb_language_impl_t *`, an opaque struct, and not a string.

> The bug appears to be something in the build that results in HB_LANGUAGE_INVALID being treated as a GObject interface (class-like) instead of a basic, serializable integer type

But HB_LANGUAGE_INVALID *isn't* a basic, serializable integer type: it's a null pointer, pointing to (the absence of) an opaque struct. Representing that in GObject-world as an integer seems like it would be wrong, and representing it as an opaque pointer (or something more closely resembling a boxed or class-like type) seems more appropriate.

**Comment by khaledhosny** [comment]
Does not look like there is anything to fix on our side.
