### ISSUE TITLE
test-hb-subset-parsing.c is missing from the release tar.xz

### ISSUE THREAD

**Issue by kwhat** [harfbuzz/harfbuzz#4649]
The `test-hb-subset-parsing.c` file is missing form the release tar.xz file but is required by `util/meson.build` line 72 when experimental_api is enabled. I am not sure if I shouldn't be building with experimental_api or if this file should exist.

**Comment by behdad** [comment]
cc @khaledhosny

**Comment by khaledhosny** [comment]
We still build release tarballs with autotools, so this was probably not added to the automake files. I think we should also enable the `experimental_api` in the distcheck CI job, to catch issues like this.

**Comment by khaledhosny** [comment]
This was added in d30c1dacf5bfc9f48cc4181e208a5c0d509d5c2d, so it is been like this for a while. But I also don’t understand why a test file is under `util` not `test`.

I’m also worried why people are now building with experimental APIs (this and #4571), packagers should not be enabling this.

**Comment by garretrieger** [comment]
For tests we typically put things akin to unit tests directly along side the code being tested (eg. see: ls src/test-*.cc). Since this is testing parsing code from util/ the test file is also under util. The tests under test/ are typically larger scale integration like tests against the public api's (eg. shaping or subsetting).
