### ISSUE TITLE
CGJ and ZWNJ in USE

### ISSUE THREAD

**Issue by Richard57** [harfbuzz/harfbuzz#483]
There should be no problem with using CGJ and ZWNJ in USE away from stackers and viramas.  However, I get dotted circles in the display from hb-view (and Firefox 53.0) for the Tai Tham sequence <U+1A3E, U+1A66, U+1A63, U+0020, U+1A3E, U+1A66, U+034F, U+1A63, U+0020, U+1A36, U+1A63 U+0020, U+1A36, U+200C, U+1A63>:
![cgj](https://cloud.githubusercontent.com/assets/23389913/25784758/70f1aecc-336a-11e7-9e4e-56a8fe3ed634.png)
The first pair is without and with CGJ between the vowels, and the second pair is without and with ZWNJ in the middle.  The first pair should look identical, whereas the first word of the second pair should have a ligature and the latter should not.  The font is Da Lekh Seri, available at http://wrdingham.co.uk/lanna/dalekh_seri.ttf (and also '.woff').

The first pair is the start of the real word ᨾᩦᩣ᩠ᨠ and the second is an actual word which can appear unligated in teaching material.

**Comment by dscorbett** [comment]
I can think of three ways to ignore CGJ. We can add `CGJ?` between every pair of expressions in hb-ot-shape-complex-use-machine.rl. We can change the `getkey` statement to have the side effect of skipping CGJ. We can make a copy of the buffer without CGJ and pass the copy to `find_syllables`. What do you think, @behdad?

**Comment by behdad** [comment]
Two more ways:

1. Originally my plan was to use Ragel error-handling to skip.  But that doesn't work / or I couldn't get it to work, because when it sees error, if it has already found a match, it would then stop.

2. `getKey` is not the right place.  Instead, we should add a class to be used instead of the integer index, and overload its `operator++`, `operator--`, as well as a few other operators, to do the skipping.  Here's a similar example, for such a class to make Ragel work on a UTF-16 string:

https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/platform/fonts/utf16_ragel_iterator.h?autodive=0%2F%2F%2F%2F#73

**Comment by behdad** [comment]
Thanks for working on this!

**Comment by dscorbett** [comment]
How can I get the code point at a certain index? `buffer->info[p].codepoint` gets the glyph ID.

**Comment by behdad** [comment]
> How can I get the code point at a certain index? `buffer->info[p].codepoint` gets the glyph ID.

We can't.  Check `use_category() == USE_CGJ`.
