### ISSUE TITLE
Update to Unicode 16

### ISSUE THREAD

**Issue by xadxura** [harfbuzz/harfbuzz#4858]
USE override files for IPC and ISC are in PR here:
https://github.com/microsoft/font-tools/pull/52

I appreciate and feedback on the PR prior to updating in Harfbuzz.

Thank you!

Andrew

**Comment by dscorbett** [comment]
@NorbertLindenberg was right in https://github.com/microsoft/font-tools/issues/17#issuecomment-2346952091 that the override for U+113CF TULU-TIGALARI SIGN LOOPED VIRAMA doesn’t work because it has InPC=Right. I overrode it in #4859 to InPC=Bottom. It doesn’t matter that U+113D2 TULU-TIGALARI GEMINATION MARK already has InPC=Bottom because USE allows any number of CMAbv, CMBlw, or SUB in any order: they are effectively indistinguishable.
