### ISSUE TITLE
Inconsistent Behavior of `chws` Feature with Punctuation Spacing in HarfBuzz

### ISSUE THREAD

**Issue by tjw123hh** [harfbuzz/harfbuzz#4937]
# Description  
When enabling the `chws` (contextual horizontal spacing) feature through fontconfig (using [this font](https://github.com/tjw123hh/noto-cjk-chws-patch)) on Arch Linux with Firefox (HarfBuzz-based rendering), the contextual spacing between certain punctuation marks occasionally behaves unexpectedly.  

For example:  
- In the string `“silkworm”（意为“丝虫”）`, the spacing between the last two punctuation marks (`”` and `）`) disappears.  
- However, in the string `（“”）`, the spacing appears as expected.  
- Additionally, even for the same string, the punctuation spacing may behave differently across different renderings (e.g., after editing or rendering the string in different contexts).

This behavior seems to follow specific but unclear patterns, which could point to an underlying bug in HarfBuzz's implementation of the `chws` feature.  

# Expected Behavior  
The contextual horizontal spacing (provided by the `chws` feature) should apply consistently to all relevant punctuation marks without omission or irregularities.  

# Actual Behavior  
- Contextual spacing between specific punctuation marks (`”` and `）`) is missing in certain cases.  
- The behavior appears inconsistent and follows unclear rules.  

# System Details  
- **Operating System**: Arch Linux  x86_64
- **Rendering Environment**: Firefox (HarfBuzz-based rendering)  
- **Font Configuration**: fontconfig with `chws` enabled
- **HarfBuzz Version**: AUR 10.1.0-1
- **Font Used**: [noto-cjk-chws-patch](https://github.com/tjw123hh/noto-cjk-chws-patch))

# Additional Notes  
- The issue is reproducible across different strings, but the exact conditions under which the spacing disappears are unclear.  
- This may involve interaction between HarfBuzz, the font, and fontconfig settings.  

# Attachments  
## Screenshots
![image](https://github.com/user-attachments/assets/37425c27-e4c4-4537-8838-70097cc232a2)

**Comment by jfkthame** [comment]
To help reproduce/investigate this, please specify *exactly* which font file you're using; looking at the "latest release" at https://github.com/tjw123hh/noto-cjk-chws-patch, there are a large number of different font resources for various formats/languages/regions.

**Comment by tjw123hh** [comment]
[NotoSansCJKChwsPatch-Regular.zip](https://github.com/user-attachments/files/17775506/NotoSansCJKChwsPatch-Regular.zip)

The family name used is `Noto Sans CJK CHWS Patch SC`.

**Comment by jfkthame** [comment]
I think what you're seeing (in Firefox specifically; I haven't checked how other browsers behave) is an artifact of the script-run itemization process, so it's an issue with how Gecko handles the text rather than a harfbuzz bug.

In your example of `“silkworm”（意为“丝虫”）`, the text begins with a Latin-script run that includes the English word (and its surrounding quote marks), and also includes the opening parenthesis (because that has Script=COMMON in Unicode, and so is considered to continue the current script run).

Then we encounter the ideographs, which create a Han-script run; this includes the quote marks around `丝虫`, which are Script=COMMON and so resolve to the current script. But the closing parenthesis is assigned script=Latin because the script itemizer attempts to pair opening and closing characters and ensure they are assigned the same script.

This means that the last two characters, `”）`, end up assigned to different script runs, and so are shaped separately; and font features like `chws` do not work across script-run boundaries.

**Comment by tjw123hh** [comment]
I've created a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1931561) on bugzilla. Closing this.
