### ISSUE TITLE
Different vertical glyph positions between ot and ft font functions

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#537]
right (ot):
```
hb-view DejaVuSans.ttf "GgXx" --direction=t --font-funcs=ot
```
left (ft):
```
hb-view DejaVuSans.ttf "GgXx" --direction=t --font-funcs=ft
```

![ot funcs](https://user-images.githubusercontent.com/93914/30253233-7686afd6-9689-11e7-8778-0748d50f03b1.png) ![ft funcs](https://user-images.githubusercontent.com/93914/30253221-56c3047e-9689-11e7-8081-86f6268db804.png)

**Comment by behdad** [comment]
FT doesn't implement VORG.  It should some day.  HB too.  But that only affects CFF.

For TrueType vertical, we should fetch tsb from glyf table and use it for to implement `v_origin` func.  That's currently missing.

**Comment by behdad** [comment]
VORG is https://github.com/behdad/harfbuzz/issues/544

**Comment by HinTak** [comment]
https://github.com/harfbuzz/harfbuzz/issues/1248 is not about glyph positioning, but font extents. FWIW. One of the values has a completely opposite sign!

**Comment by HinTak** [comment]
The font concerned - msmincho - does not have a VORG table. It has a vhea table.

**Comment by HinTak** [comment]
Also, my arriving at this issue is not that the two sets of functions behave differently, but that different set is the default, depending on **how** you open your file.

**Comment by behdad** [comment]
> FWIW. One of the values has a completely opposite sign!

You're amazing at writing useless bug reports. ;)

**Comment by HinTak** [comment]
FWIW, the descender changed sign from -36 to +36 (hence the 216 to 288 difference) between the ot/ft font funcs.

(1) writing/editing from mobile phone, don't always have all the details, (2) msmincho is common enough that it is easy for most people to see it themselves.

**Comment by behdad** [comment]
Still different.  Reopening.

**Comment by behdad** [comment]
For the rest, it looks like if `vmtx` and `vhea` tables are missing, FreeType uses horizontal ascent+descent as vertical advance, whereas we use upem.  That I'm not sure I want to fix, as it's tricky in the code.

**Comment by HinTak** [comment]
Also I don't really think the issue I reported is same as khaley's. His concerns glyph extents, mine concerns font extents. Though I agree it is likely related. Anyway, now you know the **font** descender changes sign between ft and ot.

**Comment by behdad** [comment]
> Also I don't really think the issue I reported is same as khaley's.

Then file a new issue!

**Comment by behdad** [comment]
My testing gives me same results for msmincho under the two font-funcs.  If you want your report to be taken seriously, you need to paste actual characters and ft vs ot hb-shape outputs.

**Comment by HinTak** [comment]
The command line, etc was in https://github.com/harfbuzz/harfbuzz/issues/1248 , which Khakey closed as duplicate and redirected here, and now reopen.

**Comment by Tavmjong** [comment]
Re-running the initial test shows a much smaller difference between of and ft font functions. Has something changed?

pango-view (and PangoLayout), which appears to use ft font functions, still shows badly positioned glyphs when gravity is 'east' and gravity hint is 'strong'.

**Comment by khaledhosny** [comment]
Latest Pango does not use FT font functions any more, but it has a [different issue](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/168).

**Comment by behdad** [comment]
@Tavmjong wrote in:

  https://gitlab.gnome.org/GNOME/pango/-/merge_requests/297

> The problem is that the shift calculated by HarfBuzz is not the inverse of the shift calculated by Cairo (HarfBuzz seems to match "HarfBuzz OpenType functions" glyph positioning where glyphs are moved so the top of their ink-rectangle is aligned with the top of the em-box while Cairo matches "HarfBuzz FreeType functions" glyph positioning which centers glyphs inside the em-box).

If we can identify the exact difference, we can try to close the gap.

**Comment by Tavmjong** [comment]
Here's a figure showing the different ways vertical glyphs are placed.

![vertical_upright_glyph_placement](https://user-images.githubusercontent.com/8554441/111788956-f4609200-88c0-11eb-8bc8-10c6cc5fefe8.png)
Note, I haven't studied the code to see how HarfBuzz or FreeType are actually calculating the positions but the equations agree with what I have observed dumping x_offset and y_offset with different fonts.

I believe matching the behavior of fonts with vertical metrics is the most desired behavior. If one adds the 'vmtx' table to a font with Fontforge by checking the "Has Vertical Metrics" box, it will calculate the top-side bearing so that the sum of the top-side-bearing and the top of the glyph is equal to the font ascent. Other fonts with vertical metrics I've looked at seem to do the same thing. Another way of looking at it is that horizontal baselines should be consistently positioned relative to the vertical alignment point.

The "FreeType" behavior of centering the glyph vertically inside the em-box grid using the ink-rectangle is the next best option in my opinion. I don't think the current "OpenType" behavior would please anyone.

**Comment by behdad** [comment]
@Tavmjong Thank you for your analysis. I finally managed to sit down and fix this: https://github.com/harfbuzz/harfbuzz/pull/3497
