### ISSUE TITLE
Kannada U+0CE2 and U+0CE2 vowel diacritics reordering

### ISSUE THREAD

**Issue by MayuraVerma** [harfbuzz/harfbuzz#620]
|--|--|--|--|--|
|Vowel |diacritic form | Cons+diacr | Cons conj+diacr | double Cons conj+diacr|
|ಌ | ೢ |ಕೢ | ಕ್ನೢ | ಕ್ನ್ದೢ|
|ೡ | ೣ | ಕೣ | ಕ್ನೣ | ಕ್ನ್ದೣ|
|ಌ಼ | ೢ | ಕ಼ೢ | ಕ಼್ನೢ | ಕ಼್ನ್ದೢ|
|ೡ಼ | ೣ | ಕ಼ೣ | ಕ಼್ನೣ | ಕ಼್ನ್ದೣ|
|--|--|--|--|--|

U+0CE2 (ೢ) and U+0CE2 (ೣ) have to sit outside any below form consonants similar to vowel form U+0CC3 (ೃ) and U+0CC4 (ೄ)

But U+0CE2 (ೢ) and U+0CE2 (ೣ) overlaps the below form conjugates.

Related report in noto sans https://github.com/googlei18n/noto-fonts/issues/999

But after check this with other Kannada fonts. It looks like harfbuzz, uniscribe and Apple coretext all fail to render these characters correctly.

**Comment by behdad** [comment]
If HarfBuzz and Uniscribe agree, then it's not a HarfBuzz bug.

**Comment by sridatta1** [comment]
These are hypothetical combinations, never actually occur in the language ( Sanskrit in this case). Also adding nukta to a vowel is not permitted in script grammar.

**Comment by PeterCon** [comment]
@MayuraVerma Do you happen to know what the correct positioning should be for the correspond two vowel marks in Telugu (0C62, 0C63) and Malayalam (0D62, 0D63) scripts?

**Comment by lianghai** [comment]
@MayuraVerma Kannada vowel sign vocalic L/Ll are currently consistently (across all major text engines) treated as below-base and pre-C2 marks. (While Kannada vowel sign vocalic R/Rr being pose-C2 marks.) I agree that vowel sign vocalic L/Ll's reordering behavior might need to be changed to match vowel sign vocalic R/Rr's, but this is rather an issue on the level of the OpenType spec instead of HarfBuzz, and all major text engines need to implement this change (if approved) consistently. Maybe @PeterCon has some idea about how such a change should be proposed and discussed.

@PeterCon Fyi, my current practice (as a result of some not necessarily reliable consulting…) in fonts is to reorder (through GSUB hacks) like this (in terms of final glyphs instead of logical structures — note if a normally below-base C2 mark is moved to the right side instead of stacking below, then it's considered a post-base mark here):

```
<BASE>  <post> <post>
<below> <post>
<below>
```

- Telugu and Malayalam vowel sign vocalic L/Ll: under all below-base C2 marks.
- Telugu Ai length mark: under all below-base C2 marks, unless — if a below-base Ra.C2 is immediately under the base then between the base and Ra.C2.

**Comment by PeterCon** [comment]
For Kannada, at least, I think there needs to be a distinction between marks positioned after sub-joined consonants and before post-joined consonants versus after post-joined consonants.

**Comment by lianghai** [comment]
@PeterCon Also Bangla, Odia, etc. Typically if script's post-joined consonant forms don't serve as the base for above/below marks (see ट्यु vs ট্যু), the above/below marks attach to the top/below-most whatever structure.

**Comment by lianghai** [comment]
Hypothetically a USE-alike text engine reorders all above/below-base vowel signs after `abvf`/`blwf` glyphs but before `pstf` glyphs, font developers can control the reordering by only forming the true-post-base forms (the ones that don't serve as base for marks at all, eg Bangla and Odia's C2 reduced Ya) in `pstf` and forming the pseudo-post-base forms (Devanagari's C2 reduced Ya) in `blwf`.

**Comment by MayuraVerma** [comment]
@PeterCon I don't know about Telugu and Malayalam

I sincerely request to avoid any gsub hacks in Kannada fonts. It is best to resolve all nuisances in shaping engine and expect the font to contain generic features with no exceptions.

**Comment by behdad** [comment]
Anyone wants to summarize what needs to be done here?

**Comment by MayuraVerma** [comment]
U+0CE2 (ೢ) and U+0CE2 (ೣ) have to sit outside any below form consonant conjugate similar to vowel form U+0CC3 (ೃ) and U+0CC4 (ೄ)
Currently, they sit next to the base letter and overlap with the consonant conjugates

**Comment by dscorbett** [comment]
There is nothing to do in HarfBuzz because the spec is clear and the various shaping engines are consistent. This needs to be worked around in fonts.
