### ISSUE TITLE
Tarball missing CMakeLists.txt file

### ISSUE THREAD

**Issue by jtojnar** [harfbuzz/harfbuzz#662]
When trying to build 1.7.4 from tarball using CMake, I get the following error:

```
CMake Error at CMakeLists.txt:690 (add_subdirectory):
  The source directory

    /tmp/nix-build-harfbuzz-1.7.4.drv-0/harfbuzz-1.7.4/test

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

Inspecting the downloaded [tarball](https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.7.4.tar.bz2) confirms the file is indeed missing.

**Comment by ebraminio** [comment]
Thank you very much! Glad that cmake build had any use to you also! :)

The fix will be on next release. Can you check whether the fix is working correctly by `./autogen && make distdir && cd harfbuzz-* && [rest of your cmake build and test command]` like https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L61-L63

Also https://circleci.com/gh/harfbuzz/harfbuzz/1598 shows the whole harfbuzz build takes only 5 seconds on cmake/ninja combination, comparing to one minute on make (which includes some more tests of course). @behdad I guess that is somehow interesting.

**Comment by jtojnar** [comment]
Thanks, I can confirm it builds fine now. But it seems to be far from ready at the moment. On NixOS we often install development headers to a separate directory tree but this project does not seem to allow this. It could be fixed by relying on https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html but that is for another bug.

**Comment by ebraminio** [comment]
@jtojnar That makes sense, does #665 improve your use case? Feel free to propose fixes for any other cases also. Thanks!

**Comment by ebraminio** [comment]
Merged, have a look. Of course the default build system is autotools but we (or, I, personally) like to have cmake quality on par so feel free to bring up other issues also. Thanks
