### ISSUE TITLE
[Question] Handling Tamil Sign Visarga as Consonant?

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#848]
Again trying to run down a small loose end in the Indic shaper's syllable-id logic. The Tamil visarga (U+0B83) is classified as the sole "Modifying Letter" in IndicSyllabicCategory.txt — and thus in the HB Indic table (ISC_ML). It gets combined into OT_X for the Indic syllable machine, which means it doesn't get matched against in syllable identification patterns. 

Unicode Ch12 refers to U+0B83 as, these days, "a normal spacing letter", which seems like the category should just get lumped in with consonants. Especially because it always attaches to a consonant.

It seems like not having it match OT_C would break any syllables it occurs in — but clearly no one has reported that as a bug. E.g., 'Consonant,Halant,Visarga,Consonant,'. Am I misunderstanding the codepoint, or the syllable-identification algorithm?

**Comment by dscorbett** [comment]
U+0B83 TAMIL SIGN VISARGA takes no diacritics and forms no conjuncts, so `OT_X` is appropriate.

**Comment by n8willis** [comment]
That doesn't answer the question about matching syllables in regular expressions.

**Comment by dscorbett** [comment]
Characters in `OT_X` are treated as their own syllables. In your example of ⟨consonant halant visarga consonant⟩, the OpenType syllables would be ⟨consonant halant⟩, ⟨visarga⟩, and ⟨consonant⟩. Linguistically speaking, you can’t tell which syllable U+0B83 belongs to, without more context: in Sanskrit, it is a visarga and goes with the preceding syllable; in modern Tamil, it is a foreign sound mark (like a nukta) and goes with the following syllable.

**Comment by lianghai** [comment]
I second @dscorbett's analysis.

`<consonant, virama, visarga, consonant>` being segmented into three orthographic syllables is the expected behavior.

The sentence —

> It is historically related to the visarga in other Indic scripts, but has become an ordinary spacing letter in Tamil.

— in the Core Spec can be a bit confusing but it's meant to explain that this character is should not be considered a combining mark. This doesn't mean the Tamil visarga should be treated as an Indic consonant letter — being a phonetic consonant and a spacing letter doesn't entail an Indic consonant letter. Indic consonant letters participate in the shaping behavior of Indic orthographic syllables, but the Tamil visarga doesn't.
