### ISSUE TITLE
All 2 data tests failing on Arch Linux

### ISSUE THREAD

**Issue by daavve** [harfbuzz/harfbuzz#873]
Hi,

I when building the arch-linux version of [harfbuz](https://www.archlinux.org/packages/extra/x86_64/harfbuzz/)  Both of the data tests fail for me with the following log:

[test-suite.log](https://github.com/harfbuzz/harfbuzz/files/1795870/test-suite.log)

I reported the issue downstream [here](https://bugs.archlinux.org/index.php?do=details&task_id=57764)

-Dave

**Comment by ebraminio** [comment]
Hi @daavve, thanks for the report. It was because of py3 compatibility which we care about as we have a ArchLinux bot runner that just didn't run that test and I just fixed it both on the source and the bot this is the part you should apply 9206762. I don't know however how we can provide that as a patch for ArchLinux project @behdad (or whether we need to?), I hope downstream however will be able to maintain that patch till the next release.
