### ISSUE TITLE
Add a helper to load SVGZ table

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#882]
To load SVGZ table, HarfBuzz need to be allowed to build with a decompression library, then calling it to get the glyph.

**Comment by ebraminio** [comment]
Hi Krasnaya. Thanks for the interest :) There is no SVGZ table, maybe I mislead you, it is just "SVG " that its blobs are gzipped. We can almost skip handling it as we don't do the SVG rendering also in a foreseeable future so no wonder if we force our clients in order to use a returned SVG of SVG table they should also decompress it with their own libraries. Fun fact, the SVG table was initially proposed to support animations on Emojis also so no wonder its rendering needs very tight coupling with the rest of the stack (say a browser), so its rendering is something beyond capability of harfbuzz anyway and we should do our best just to parse the font for our clients and leave the rest to theirs. Thank you

**Comment by KrasnayaPloshchad** [comment]
Oh I was totally misunderstand. So I think HarfBuzz shouldn't treated SVGZ glyphs in SVG table as invalid, and allowing clients using a decompressing library to render them, isn't it?

**Comment by ebraminio** [comment]
Fortunately the table itself is not compressed but its individual SVGs :)
